# -*- coding: utf-8 -*-
"""
Data for Domains 21 to 30 (300 cases: 701 to 1000)
"""

DOMAINS_21_TO_30 = [
    {
        "id": 21,
        "name": "Kültür, Sanat, Tarihi Miras ve Ayasofya",
        "source": "Kültür ve Turizm Bakanlığı",
        "char1": "char_cumhurbaskani",
        "char2": "char_sehir_plancisi",
        "kw": "Kültür ve Tarihi Miras",
        "cases": [
            ("Ayasofya-i Kebir Cami-i Şerifi'nin İbadete Açılması (2020)", "Danıştay 10. Dairesi'nin 1934 tarihli müzeye dönüştürme kararını iptaliyle Ayasofya 86 yıl sonra cami oldu."),
            ("Ayasofya'da 86 Yıl Sonra Kılınan İlk Cuma Namazı", "350 bin vatandaşın Sultanahmet Meydanı'nı doldurduğu tarihi günde Diyanet İşleri Başkanı kılıçla hutbe verdi."),
            ("Kariye Camii'nin Restorasyon Sonrası İbadete Açılması", "Fatih'teki tarihi mozaikleriyle ünlü Kariye 79 yıllık müze statüsünden çıkarılarak yeniden ibadete açıldı."),
            ("Şanlıurfa Göbeklitepe'nin UNESCO Dünya Mirası Listesine Girmesi", "Tarihin sıfır noktası olarak kabul edilen 12 bin yıllık tapınak kompleksi tüm dünyada arkeoloji devrimi yaptı."),
            ("Karahantepe ve Taş Tepeler Neolitik Çağ Keşifleri", "Şanlıurfa platosunda Göbeklitepe'den daha eski yerleşim kalıntıları bulunarak dünya arkeolojisi Türkiye'ye aktı."),
            ("Zeugma 'Çingene Kızı' Mozaiğinin ABD'den İadesi", "Gaziantep'ten kaçırılan paha biçilmez mozaik parçaları Kültür Bakanlığı'nın diplomatik zaferiyle yurda döndü."),
            ("Yorgun Herakles Heykelinin Boston Müzesi'nden Getirilmesi", "Antalya Perge kazılarında altı bulunan heykelin üst yarısı ABD'den getirilerek müzede birleştirildi."),
            ("Kaçırılan Binlerce Tarihi Eserin Kültür Bakanlığınca İadesi", "İsviçre, Almanya ve İngiltere müzelerinden yüzlerce lahit, sikke ve heykel diplomatik baskıyla geri alındı."),
            ("Atatürk Kültür Merkezi'nin (AKM) Yıkılıp Yeniden İnşası", "Taksim Meydanı'ndaki eski bina yıkılarak modern opera salonu ve kültür kompleksi olarak 29 Ekim'de açıldı."),
            ("Büyük Çamlıca Camii'nin İstanbul Boğazı Tepesinde Açılışı", "63 bin kişilik kapasitesi ve 6 minaresiyle Cumhuriyet tarihinin en büyük camisi ibadete açıldı."),
            ("Nuri Bilge Ceylan'ın 'Kış Uykusu' ile Cannes Altın Palmiye Zaferi", "Kapadokya'da geçen filmle yönetmen Türk sinemasına Yılmaz Güney'den sonra ikinci Altın Palmiye'yi kazandırdı."),
            ("Fatih Akın'ın 'Duvara Karşı' ile Berlin Altın Ayı Ödülü", "Almanya ve Türkiye arasındaki göçmen kimliğini anlatan film Berlin Film Festivali'nin en büyük ödülünü aldı."),
            ("Orhan Pamuk'un 2006 Nobel Edebiyat Ödülü'nü Kazanması", "Türk edebiyat tarihinin ilk Nobel ödülü 'kentinin melankolik ruhunun izlerini süren' yazara verildi."),
            ("Prof. Dr. Aziz Sancar'ın 2015 Nobel Kimya Ödülü", "Mardin Savur doğumlu bilim insanı DNA onarımı mekanizması keşfiyle Nobel ödülünü Anıtkabir'e hediye etti."),
            ("Prof. Dr. Daron Acemoğlu'nun 2024 Nobel Ekonomi Ödülü", "Kurumların refah ve demokrasi üzerindeki etkisini kanıtlayan tarihi çalışmasıyla Nobel ödülünü kazandı."),
            ("Fazıl Say'ın Besteleri ve Hakkında Açılan Davaların Beraati", "Dünyaca ünlü piyanist hakkında sosyal medya paylaşımları sebebiyle açılan davalar beraatle sonuçlandı."),
            ("Türk Dizi Sektörünün Dünyada İhracat İkincisi Olması", "Latin Amerika'dan Orta Doğu'ya 150 ülkeye ihraç edilen Türk dizileri 1 milyar seyirciye ulaştı."),
            ("TRT Kurdî (TRT Şeş) Kanalının Yayına Başlaması", "Devlet televizyonunda 24 saat Kürtçe yayın dönemi başlayarak tarihi bir kültürel tabu yıkıldı."),
            ("TRT World ve TRT Arapça Uluslararası Yayın Ağları", "Türkiye'nin tezlerini dünyaya İngilizce ve Arapça anlatan küresel haber televizyonları kuruldu."),
            ("RTÜK'ün Dijital Platformları (Netflix, Prime, Disney) Denetimi", "İnternet yayıncılığına getirilen RTÜK lisans zorunluluğu ve içerik denetimleri tartışmalara yol açtı."),
            ("Sinemada 'Mısır Krizi' ve Yeni Sinema Kanunu", "Film yapımcıları ile mısır promosyonu dayatan sinema salon zincirleri arasındaki kriz yasayla çözüldü."),
            ("Müzik Meslek Birlikleri (MESAM, MSG, MÜYAP) Telif Krizleri", "Dijital müzik gelirlerinin dağıtımı konusunda sanatçılar arasında yaşanan telif kavgaları mahkemeye taşındı."),
            ("Cumhurbaşkanlığı Senfoni Orkestrası'nın (CSO) Yeni Binası", "Ankara'da 23 yıl süren inşaatın ardından fütüristik mimarisiyle dev konser salonu açıldı."),
            ("Altın Portakal Film Festivali'nde Belgesel Sansürü Tartışması", "Kanun Hükmü belgeselinin seçkiden çıkarılması sonrası sinemacıların boykotuyla festival iptal edildi."),
            ("Boğaziçi Caz Korosu'nun Dünya Koro Olimpiyatları Şampiyonluğu", "Genç koro müzisyenleri Çin ve ABD'deki yarışmalarda Türkiye'ye altın madalyalar getirdi."),
            ("Aşık Veysel'in Vefatının 50. Yılının UNESCO Anma Yılı İlanı", "Büyük halk ozanının türküleri ve dostluk felsefesi tüm dünyada düzenlenen konserlerle anıldı."),
            ("Gaziantep ve Hatay Mutfağının UNESCO Gastronomi Şehri Seçilmesi", "Türk mutfağının eşsiz lezzetleri Birleşmiş Milletler tarafından tescillenerek dünya markası oldu."),
            ("Sümela Manastırı'nın Kaya Düşmesi Önleme Restorasyonu", "Trabzon Maçka'daki sarp kayalıklara asılı tarihi manastır çelik ağlarla örülerek ziyarete açıldı."),
            ("Ani Harabeleri ve Kars Kalesinin UNESCO Mirası Olması", "İpek Yolu üzerindeki bin yıllık Ermeni ve Selçuklu kenti Ani koruma altına alındı."),
            ("Mardin Tarihi Dokusunun Korunması ve Betonarme Yıkımları", "Taş konakların silüetini bozan yüzlerce kaçak betonarme kat dozerlerle yıkılarak tarihi doku kurtarıldı.")
        ]
    },
    {
        "id": 22,
        "name": "Tüketici Hakları, Pazar Yeri, Esnaf ve Ticaret Hayatı",
        "source": "Ticaret Bakanlığı & Rekabet Kurumu",
        "char1": "char_ticaret_bakani",
        "char2": "char_tuketici_dernekleri_baskani",
        "kw": "Tüketici ve Ticaret",
        "cases": [
            ("6502 Sayılı Tüketicinin Korunması Hakkında Kanun Reformu", "İnternet alışverişlerinde 14 günlük koşulsuz cayma hakkı ve ayıplı mal güvencesi yasalaştı."),
            ("Kredi Kartı Aidatlarının İadesi Talepleri ve Hakem Heyetleri", "Tüketicilerin bankalardan geriye dönük 10 yıllık kart aidatı talebi hakem heyetlerinde rekor başvurulara yol açtı."),
            ("Tüketici Hakem Heyetleri Başvuru Parasal Sınırının Artışı", "Yıldan yıla artırılan sınırla on binlerce liralık tüketici uyuşmazlığı mahkemesiz çözülür hale geldi."),
            ("Kredi Kartlarında Taksit Sınırlamaları ve Elektronik Yasağı", "Cari açığı frenlemek amacıyla cep telefonu alımlarında kredi kartına taksit yapılması yasaklandı."),
            ("5 Büyük Zincir Markete Rekabet Kurumu'ndan 2.7 Milyar TL Ceza", "Ortak fiyat belirleyerek kartel oluşturdukları tespit edilen perakende devlerine tarihi ceza kesildi."),
            ("Hal Yasası Reformu: Tarladan Sofraya Komisyoncu Zinciri", "Aracı komisyoncuların sebze ve meyve fiyatlarını katlamasını önleyecek yeni hal modeli meclise taşındı."),
            ("Tanzim Satış Noktaları: Sebze-Meyve Çadırları (2019)", "Büyükşehirlerde fahiş fiyatları kırmak için belediyeler meydanlara çadır kurup maliyetine patates sattı."),
            ("Tarım Kredi Marketleri Ağı ve Temel Gıdada İndirimler", "Cumhurbaşkanı talimatıyla kar amacı gütmeyen kooperatif marketlerinin sayısı 3 bin şubeye çıkarıldı."),
            ("Kırmızı Et Fiyatları Artışı ve Et ve Süt Kurumu (ESK) Kuyrukları", "Piyasanın yarı fiyatına kıyma ve kuşbaşı satan ESK mağazaları önünde sabahın erken saatlerinde kuyruklar oluştu."),
            ("İthal Canlı Hayvan ve Karkas Et İthalatıyla Piyasa Müdahalesi", "Yetersiz yerli besicilik karşısında piyasayı dengelemek için Uruguay ve Brezilya'dan angus ithal edildi."),
            ("Ayçiçek Yağı Stok Dedikodusu ve Marketlerde Yağ Yağması", "Ukrayna savaşıyla gemilerin limanda kaldığı dedikodusu market raflarının bir gecede boşalmasına yol açtı."),
            ("Otomotivde '6 Ay ve 6 Bin Kilometre' Satış Sınırı", "Sıfır araçları alıp liste fiyatının üstünde 'sıfır gibi' ikinci el satan al-satçılara kanuni set çekildi."),
            ("Sıfır Araç Bayilerine Aksesuar Zorlama ve Liste Üstü Satış Cezaları", "Müşterilere seramik kaplama ve cam filmi adı altında fahiş ekstra ücret dayatan bayilere kapatma cezası geldi."),
            ("Elektronik İlan Doğrulama Sistemi (EİDS) ile Sahte İlan Yasağı", "Emlak ve otomobil sitelerinde yetkisiz kişilerin spekülatif ilan girmesi e-Devlet kimlik doğrulamasıyla engellendi."),
            ("Konut Kiralarında 2 Yıl Süreyle Uygulanan %25 Artış Tavanı", "Enflasyon karşısında kiracıları korumak için getirilen sınır ev sahipleri ile kiracılar arasında kavgalara yol açtı."),
            ("Kira Uyuşmazlıklarında Zorunlu Arabuluculuk Sistemine Geçiş", "Mahkemeye gitmeden önce arabulucuya gitme şartıyla yüz binlerce kira krizi uzlaşmayla çözüldü."),
            ("Noterlerde Gayrimenkul Alım-Satım Sözleşmesi Yapılabilmesi", "Tapu dairelerindeki yoğunluğu azaltmak amacıyla noterlere gayrimenkul satışı yapma yetkisi verildi."),
            ("Tapu ve Kadastro Web-Tapu Sistemi ve Parsel Sorgu Altyapısı", "Vatandaşların tapu dairesine gitmeden taşınmazlarını internetten yönetebileceği güvenli sistem kuruldu."),
            ("Plastik Alışveriş Poşetlerinin Ücretli (25 Kuruş) Yapılması", "Çevre kirliliğini önlemek amacıyla başlatılan uygulamayla poşet kullanımı bir yılda %75 azaldı."),
            ("Sıfır Atık Hareketi ve Kamu Binalarında Ayrıştırma Kutuları", "Emine Erdoğan himayesinde başlatılan projeyle kamu kurumlarında geri dönüşüm seferberliği yapıldı."),
            ("Depozito İade Sistemi (DİS): İçecek Şişelerine Para İadesi", "Cam ve pet şişelerin sokak otomatlarına atılarak nakit para iadesi alınmasını sağlayan altyapı kuruldu."),
            ("Yurt Dışından Getirilen Cep Telefonlarının IMEI Harç Artışı", "Harç ücretinin 30 bin TL seviyelerine çıkarılmasıyla bavul ticareti ve sınır ötesi telefon alımları bıçak gibi kesildi."),
            ("Yurt Dışı Hızlı Kargo Muafiyet Sınırının 30 Euro'ya Çekilmesi", "Çinli e-ticaret sitelerinden yerli üreticiyi korumak amacıyla gümrüksüz alışveriş limiti düşürüldü."),
            ("E-Ticaret Kanunu Reformu: Pazaryerlerinin Kendi Markasını Satma Yasağı", "Trendyol, Hepsiburada ve Amazon gibi platformların küçük satıcıları ezmesini önleyen tarihi düzenleme çıktı."),
            ("Moto-Kurye Meslek Standartları ve Fırtınalı Havada Çalışma Yasağı", "Kuryelerin can güvenliği için kask, yelek zorunluluğu ve kar fırtınasında sipariş teslimat yasağı getirildi."),
            ("Pandemi Dönemi Küçük Esnafa Hibe, Kira ve Kredi Destekleri", "Kepenk kapatan kahvehane, berber ve lokanta esnafına doğrudan Hazine nakit desteği sağlandı."),
            ("Basit Usulde Vergilendirilen 850 Bin Küçük Esnafın Gelir Vergisi Muafiyeti", "Taksici, berber, terzi ve bakkalların gelir vergisi beyannamesi verme zorunluluğu tamamen kaldırıldı."),
            ("Elektronik Ticarette Güven Damgası Sistemi", "İnternetten satış yapan sitelere güvenlik ve tüketici haklarına riayet kriteriyle güven damgası verildi."),
            ("Mesafeli Sözleşmelerde Cayma Hakkında Kargo Ücreti Tartışması", "İade edilen ürünlerin kargo masrafının kime ait olacağı konusundaki ertelemeler tüketici derneklerini böldü."),
            ("Garanti Belgesi Yönetmeliği ve Yetkili Servis Denetimleri", "Beyaz eşya ve otomotivde sahte yetkili servis açıp tüketicileri dolandıran internet korsanları mühürlendi.")
        ]
    },
    {
        "id": 23,
        "name": "Enerji Piyasası, Tabii Kaynaklar ve Madencilik Mevzuatı",
        "source": "Enerji ve Tabii Kaynaklar Bakanlığı",
        "char1": "char_hazine_bakani",
        "char2": "char_sanayi_bakani",
        "kw": "Madencilik ve Enerji Mevzuatı",
        "cases": [
            ("Akaryakıtta Eşel Mobil Sistemi ile Pompa Fiyatı Kalkanı", "Uluslararası petrol fiyatları ve kur arttığında ÖTV'den feragat edilerek akaryakıt zammı vatandaşa yansıtılmadı."),
            ("Elektrik Faturalarında Kademeli Tarife Uygulaması", "Aylık 240 kilovatsaate kadar olan düşük elektrik tüketimi sübvanse edildi, fazlasına yüksek tarife uygulandı."),
            ("Organize Sanayi Bölgelerinde (OSB) Kış Doğalgaz Kısıntıları", "Boru hatlarındaki basınç düşüşü sebebiyle sanayi tesislerine gaz kısıntısı uygulanarak konutlar korundu."),
            ("Enerji Borsası EPİAŞ'ın Kurulması ve Şeffaf Piyasa", "Elektrik ve doğalgaz referans fiyatlarının serbest piyasa koşullarında anlık belirlendiği borsa faaliyete geçti."),
            ("Yenilenebilir Enerji Kaynak Alanları (YEKA) İhaleleri", "Yerli üretim güneş paneli ve rüzgar türbini şartıyla devasa enerji sahaları ihale edildi."),
            ("Konya Karapınar Güneş Enerjisi Santrali (GES) Tamamlanması", "Avrupa'nın en büyük tek parça güneş santrali çölde parlayarak 2 milyon haneyi aydınlattı."),
            ("Çatılarda Lisanssız Güneş Santrali Kurulum Kolaylığı", "Vatandaşların binalarının çatısına güneş paneli koyup fazla elektriği TEDAŞ'a satması kanunlaştı."),
            ("Rüzgar Enerjisinde (RES) 12 Bin Megavat Barajının Aşılması", "Çanakkale, İzmir ve Balıkesir tepelerindeki dev pervaneler Türkiye'nin elektrik ihtiyacının %11'ini üretti."),
            ("Aydın Büyük Menderes Jeotermal Enerji (JES) Çevre Raporları", "Jeotermal santrallerin incir ve zeytin bahçelerine etkisi konusunda üniversite teftiş heyetleri kuruldu."),
            ("Maden ve Petrol İşleri Genel Müdürlüğü (MAPEG) Denetimleri", "Türkiye genelindeki binlerce maden ocağı iş güvenliği ve çevre tedbirleri yönünden sıkı denetime alındı."),
            ("Bandırma Bor Karbür Üretim Tesisinin Hizmete Alınması", "Eti Maden tonu 500 dolar olan bor madenini tonu 40 bin dolar olan zırh ve aşındırıcı tozuna dönüştürdü."),
            ("Eskişehir Beylikova Nadir Toprak Elementleri Keşfi", "Hafif ve ağır nadir elementlerde dünyanın en büyük ikinci sahası bulunarak pilot işleme tesisi açıldı."),
            ("Kömür Madenlerinde Yaşam Odası Zorunluluğu Yasası", "Soma ve Ermenek faciaları sonrası yer altı ocaklarında oksijen tüplü sığınma odaları zorunlu kılındı."),
            ("Soma Faciası Sonrası Madenci Ailelerine Kamuda İstihdam Yasası", "Şehit madencilerin bir yakınına kamuda sürekli memuriyet ve aileye bağlanan maaşlar kanunlaştı."),
            ("Maden İşçilerinin Emeklilik Yaşının 43'e Düşürülmesi", "Yerin yüzlerce metre altında kazma vuran madencilerin yıpranma payı artırılarak erken emeklilik sağlandı."),
            ("Türkiye Taşkömürü Kurumu (TTK) Zonguldak Maden İşçisi Kuraları", "Zonguldak kömür ocaklarına binlerce gencin istihdam edilmesi için noter huzurunda kura çekilişleri yapıldı."),
            ("Oruç Reis Sismik Gemisinin Somali Açıklarında Petrol Arama Seferi", "Somali ile yapılan hükümetlerarası anlaşmayla Türk donanması korumasında sismik arama başlatıldı."),
            ("Libya ile İmzalanan Petrol ve Doğalgaz Arama Protokolü", "Trablus açıklarında ortak hidrokarbon çıkarma mutabakatı Yunanistan ve AB'yi telaşlandırdı."),
            ("Kömürlü Termik Santrallere Filtre Takma Zorunluluğu Krizi", "Bacalarına filtre takmayan termik santrallere süre uzatımı getiren yasa Cumhurbaşkanı'nca veto edildi."),
            ("Biyokütle Enerji Santralleri ve Tarımsal Atıkların Dönüşümü", "Mısır koçanları ve orman atıklarının yakılarak elektriğe dönüştürüldüğü tesisler teşvik edildi."),
            ("Hidroelektrik Santrallerinde (HES) Can Suyu Denetimleri", "Karadeniz derelerindeki HES'lerin nehir yatağına bırakması gereken minimum su miktarı kameralarla izlendi."),
            ("Siyanürlü Altın Madenciliği İzinleri ve ÇED Süreçleri", "Maden ocaklarının atık havuzlarının deprem ve sızıntı güvenliği için bağımsız bilim kurulları kuruldu."),
            ("Tuz Gölü Yeraltı Doğalgaz Depolama Tesisinin Tam Kapasitesi", "Yerin 1.5 kilometre altındaki tuz blokları eritilerek açılan dev boşluklar gaz rezervuarı yapıldı."),
            ("Karadeniz Sakarya Gazının Karaya Çıkış Basınç Regülasyonu", "Filyos limanındaki tesislerde deniz dibinden gelen gaz kokulandırılıp ulusal şebekeye basıldı."),
            ("Gabar Petrolünün Rafinerilere Taşınması ve İkmal Hattı", "Gabar dağında çıkarılan ham petrol boru hattı ve tanker filosuyla Batman rafinerisine sevk edildi."),
            ("Nükleer Düzenleme Kurumu'nun (NDK) Faaliyete Başlaması", "Nükleer santrallerin güvenliği ve radyasyon denetimini yapan bağımsız düzenleyici kurul oluşturuldu."),
            ("Kaya Gazı (Şeyl Gazı) Arama Sondajları (Trakya ve Diyarbakır)", "Yatay sondaj ve hidrolik kırma yöntemleriyle kaya çatlaklarındaki gaz potansiyeli incelendi."),
            ("Akaryakıt İstasyonlarında Ulusal Taşıt Tanıma Sistemi (UTTS)", "Vergi kaçakçılığını önlemek için araçların depolarına ve pompa tabancalarına çipli tanıma zorunluluğu geldi."),
            ("Elektrikli Araç Şarj Ağı İşletmeci Lisansları Düzenlemesi", "81 ilde kurulan hızlı şarj istasyonları için EPDK standartları ve tavan tarife kuralları getirildi."),
            ("Enerji Tasarrufu ve Yalıtım Kredisi Desteği", "Binaların dış cephe mantolama ve ısı yalıtım masrafları için düşük faizli kamu bankası kredisi açıldı.")
        ]
    },
    {
        "id": 24,
        "name": "Şehir Hayatı, Ulaşım, Belediyeler ve Yerel Dinamikler",
        "source": "İçişleri Bakanlığı & Çevre Şehircilik",
        "char1": "char_sehir_plancisi",
        "char2": "char_esnaf_odasi_baskani",
        "kw": "Belediye ve Şehir Hayatı",
        "cases": [
            ("İstanbul Taksi Plakası Krizi: İBB ile Taksiciler Odası Çatışması", "Kalitesiz hizmet ve yetersiz taksi sayısı sebebiyle İBB'nin 5 bin yeni taksi teklifi UKOME'de defalarca reddedildi."),
            ("UKOME Yönetmeliği Değişikliği ve Hükümet Üyeleri Çoğunluğu", "Büyükşehir Ulaşım Koordinasyon Merkezleri'nde bakanlık temsilcilerinin sayısı artırılarak karar dengesi değişti."),
            ("UKOME Kararıyla 2.500 Yeni Uygulama Tabanlı Taksinin Onayı", "Yıllar süren krizin ardından sadece dijital uygulama üzerinden çalışacak 2.500 yeni taksi ihalesi onaylandı."),
            ("Taksilerde Güvenlik Kamerası ve Panik Butonu Zorunluluğu", "Şoför cinayetleri ve müşteri güvenliği için tüm taksilere iç kamera ve panik butonu takıldı."),
            ("Uber ile Sarı Taksiciler Arasındaki Kavgalar ve Mahkeme Yasağı", "Sarı taksicilerin adliye önündeki eylemleri ve darp olayları sonrası Uber haksız rekabetten kapatıldı."),
            ("Uber'in Sarı Taksilerle Entegre Olarak Türkiye'ye Dönüşü", "Mahkemenin erişim engelini kaldırmasıyla Uber sarı taksi çağırma platformu olarak geri döndü."),
            ("Elektrikli Scooter (Martı, BinBin) İstilası ve Kaldırım Krizleri", "Büyükşehir kaldırımlarını işgal eden binlerce scooter yayaların yürümesini engelleyince tepkiler patladı."),
            ("E-Scooter Yönetmeliği: Hız Sınırının 20 km/s'ye İndirilmesi", "Ölümlü kazaların ardından scooterlara hız sınırı, kask tavsiyesi ve park yasağı cezaları getirildi."),
            ("Melih Gökçek'in Ankara Büyükşehir Belediye Başkanlığından İstifası", "Cumhurbaşkanı'nın 'metal yorgunluğu' çağrısı sonrası 23 yıllık başkan istifa mektubunu okuyarak ayrıldı."),
            ("Mansur Yavaş'ın Ankara'da Belediye İhalelerini Canlı Yayınlaması", "Belediye meclis toplantıları ve asfalt ihalelerinin internetten canlı yayınlanması şeffaflık rüzgarı başlattı."),
            ("Ekrem İmamoğlu'na YSK Üyelerine 'Ahmak' Dediği İddiasıyla Ceza Davası", "İmamoğlu hakkında açılan hakaret davasında 2 yıl 7 ay hapis ve siyasi yasak kararı istinafa taşındı."),
            ("Ankara Ankapark (Wonderland Eurasia): 801 Milyon Dolarlık Enkaz", "Melih Gökçek döneminde yapılan dinozor temalı dev park işletilemeyince çürümeye terk edildi ve devredildi."),
            ("İzmir Körfezi Kirliliği ve Toplu Balık Ölümleri Krizi", "Körfezden yayılan kötü koku ve kıyıya vuran binlerce ölü balık Çevre Bakanlığı ile Büyükşehir'i karşı karşıya getirdi."),
            ("Bursa Tarihi Ulu Cami Çevresindeki Çarpık Binaların Yıkılması", "Tarihi hanlar ve cami silüetini kapatan çok katlı binalar yıkılarak devasa bir tarihi meydan açıldı."),
            ("Trabzon Uzungöl'de İmar Kirliliği ve Kaçak Yapıların Yıkımı", "Göl kıyısındaki kaçak oteller ve kaçak ahşap bungalovlar jandarma ve dozerler eşliğinde yıkıldı."),
            ("Rize Ayder Yaylası Kentsel Dönüşüm Projesi", "Salıncakların söndüğü, betonlaşmanın durdurulduğu yaylada otopark yer altına alınarak çimler kurtarıldı."),
            ("Kapadokya Alan Başkanlığı'nın Kurulması ve Kaçak Otel Yıkımları", "Peri bacalarının yanı başına yapılan kaçak otel ve havuzlar özel kanun yetkisiyle yıkıldı."),
            ("Pamukkale Travertenlerini Tehdit Eden Otellerin Yıkılması", "Beyaz travertenlerin üzerine kurulan ve suları tüketen eski oteller yıkılarak beyazlık kurtarıldı."),
            ("Bodrum ve Fethiye Koylarındaki Kaçak İskele ve Villaların Yıkımı", "Deniz kıyılarını işgal eden lüks sitelerin kaçak iskeleleri Sahil Güvenlik ve bakanlıkça dozerlerle söküldü."),
            ("Marmaris Datça Çevre Koruma Bölgelerinde Kaçak Yapı Baskını", "Doğal sit alanlarında imar barışına aykırı inşa edilen kaçak villalar tek tek mühürlendi."),
            ("İstanbul Metrobüs Hattında Yaşanan Kazalar ve Otobüs Yangınları", "Günde 1 milyon yolcu taşıyan hatta meydana gelen kazalar ve arızalar toplu ulaşımı felç etti."),
            ("İstanbul'da '150 Günde 150 Proje' ve Metro Açılışları", "İBB durdurulan metro hatlarını Avrupa fonlarıyla yeniden başlatarak peş peşe hizmete aldı."),
            ("Adana Kebap ve Gaziantep Baklavasının AB Coğrafi İşaret Tescili", "Geleneksel Türk lezzetleri Avrupa Birliği tarafından resmi coğrafi işaretle korumaya alındı."),
            ("Sokak Hayvanları Yasası (5199): Kısırlaştır, Aşıla, Barınak", "Sokak köpeklerinin saldırıları sonrası sahipsiz hayvanların toplanıp barınaklara alınması kanunlaştı."),
            ("Başıboş Sokak Köpekleri Saldırıları ve Çocuk Can Kayıpları", "Kuduz ve parçalanma tehlikesi karşısında ailelerin feryatları hayvansever dernekleriyle karşı karşıya geldi."),
            ("Millet Bahçeleri Projesi: Eski Stat ve Askeri Alanların Yeşile Dönüşümü", "Şehir merkezlerindeki eski stadyumlar yıkılarak park ve kütüphaneli millet bahçesi yapıldı."),
            ("Kentsel Dönüşümde 'Yarısı Bizden' Kampanyası (İstanbul)", "Riskli binalarını dönüştürmek isteyen vatandaşlara devlet yarısı hibe, yarısı uygun kredi desteği verdi."),
            ("Fikirtepe Kentsel Dönüşüm Kaosu ve Bakanlığın İşe El Koyması", "Müteahhitlerin yarım bıraktığı şantiyeler ve çadırlarda bekleyen mağdurlar için TOKİ devreye girdi."),
            ("Binalara Kimlik Kartı ve Karekod Levhası Asılması Zorunluluğu", "Her binanın girişine deprem testi, yapım yılı ve mimari projelerini gösteren çipli levhalar kondu."),
            ("Hazır Beton Santrallerinde Çipli Beton Takip Sistemi (EBİS)", "İnşaatlarda kullanılan betonun kalitesini anlık laboratuvara aktaran çipli numune sistemi zorunlu oldu.")
        ]
    },
    {
        "id": 25,
        "name": "Sosyal Güvenlik, Sendikalar, Emeklilik ve Çalışma Hayatı",
        "source": "Çalışma ve Sosyal Güvenlik Bakanlığı",
        "char1": "char_hazine_bakani",
        "char2": "char_esnaf_odasi_baskani",
        "kw": "Emeklilik ve İşçi Hakları",
        "cases": [
            ("Emeklilikte Yaşa Takılanlar (EYT) Hareketi ve Mitingleri", "1999 öncesi sigortalıların yaş şartına takılmasına karşı milyonlarca vatandaş dernekleşerek mitingler yaptı."),
            ("2023 Tarihli EYT Kanunu ile 2 Milyondan Fazla Vatandaşın Emekliliği", "Cumhurbaşkanı kararıyla yaş şartı tamamen kaldırılarak prim gününü dolduranlara emeklilik yolu açıldı."),
            ("SGK Merkezlerinde Yaşanan Tarihi EYT Başvuru Yoğunluğu", "Yüz binlerce vatandaşın aynı anda dilekçe vermesiyle SGK memurları gece yarılarına kadar fazla mesai yaptı."),
            ("Asgari Ücret Tespit Komisyonu'nun Temmuz Ara Zam Toplantıları", "Yüksek enflasyon sebebiyle komisyon yılda iki kez toplanarak asgari ücrete çifte zam uyguladı."),
            ("Asgari Ücretten Gelir ve Damga Vergisinin Tamamen Sıfırlanması", "Tüm çalışanların maaşının asgari ücrete kadar olan kısmından vergi kesintisi kalıcı olarak kaldırıldı."),
            ("696 Sayılı KHK ile 900 Bin Taşeron İşçinin Sürekli İşçi Kadrosuna Alınması", "Kamuda taşeron şirketler üzerinden çalışan temizlik, güvenlik ve işçiler devlet kadrosuna geçirildi."),
            ("3600 Ek Gösterge Yasası ile Memur Emekli İkramiyesi Artışı", "Öğretmen, polis, hemşire ve din görevlilerinin ek göstergeleri 3600'e çıkarılarak emekli maaşları artırıldı."),
            ("Memur ve Emekli Maaşlarına Enflasyon Farkı + Refah Payı İlavesi", "Toplu sözleşme zammının üzerine Hazine desteğiyle refah payı eklenerek maaşlar yükseltildi."),
            ("Ramazan ve Kurban Bayramlarında Emeklilere Bayram İkramiyesi", "Milyonlarca emekliye yılda iki kez ödenen bayram ikramiyesi geleneksel sosyal hak haline geldi."),
            ("En Düşük Emekli Maaşına Hazine Desteği ile Taban Tutar Belirlenmesi", "Kök maaşı tabanın altında kalan emeklilere aradaki fark Hazine kasasından doğrudan ödendi."),
            ("Kıdem Tazminatı Fonu Taslağı ve Sendikaların Grev Tehdidi", "Kıdem tazminatının fona devredilmesine karşı Türk-İş ve DİSK genel grev kararı alarak taslağı rafa kaldırttı."),
            ("6356 Sayılı Sendikalar ve Toplu İş Sözleşmesi Kanunu Düzenlemeleri", "Grev ve lokavt kuralları ile işkolu barajlarını belirleyen temel çalışma yasası güncellendi."),
            ("Metal Sektöründe MESS Grup Toplu İş Sözleşmesi Grev Kararları", "Yüz binlerce otomotiv ve beyaz eşya işçisinin grev kararları milli güvenlik gerekçesiyle ertelendi."),
            ("ÇAYKUR Çay Taban Fiyatı ve Destekleme Primi Açıklamaları", "Rize ve Karadenizli çay üreticilerinin yaş çay taban fiyatı her bahar hükümetçe duyuruldu."),
            ("Toprak Mahsulleri Ofisi (TMO) Fındık Taban Fiyatı ve Alımları", "Karadeniz fındık üreticisini yabancı tekellere ezdirmemek için TMO taban fiyatla müdahale alımı yaptı."),
            ("Hububatta TMO Randevulu Alım Sistemi ve Siloların Dolması", "Buğday ve arpa üreticileri mahsullerini TMO silolarına dökerek devlet garantili fiyat aldı."),
            ("Şeker Fabrikalarının Özelleştirilmesi Tartışmaları ve Kotalar", "14 kamu şeker fabrikasının özelleştirilmesi sonrası pancar üretimi ve Nişasta Bazlı Şeker (NBŞ) kotaları tartışıldı."),
            ("2010 Tekel İşçilerinin 78 Gün Süren Ankara Abdi İpekçi Parkı Direnişi", "Özelleştirme sonrası özlük haklarını korumak isteyen Tekel işçileri kış ortasında çadırlarda direndi."),
            ("Kurye ve Dağıtım İşçilerinin Maaş Zam Eylemleri ve Kontak Kapatma", "Trendyol, Hepsiburada ve Yemeksepeti kuryeleri yetersiz zamlara karşı motosikletlerini çekip eylem yaptı."),
            ("Kadın Çalışanlara Yönelik Doğum İzni, Süt İzni ve Yarım Zamanlı Çalışma", "Memur ve işçi annelere doğum sonrası maaşlı izin ve çocuk ilkokula başlayana kadar kısmi çalışma hakkı geldi."),
            ("Esnek Çalışma ve Uzaktan Çalışma Yönetmeliğinin Yürürlüğe Girmesi", "Pandemiyle yaygınlaşan evden çalışma modelinin mesai saatleri ve internet fatura giderleri kanunlaştı."),
            ("İş Sağlığı ve Güvenliği Kanunu (6331) ile Uzman İstihdamı", "Tüm işyerlerine tehlike sınıfına göre iş güvenliği uzmanı ve işyeri hekimi bulundurma zorunluluğu geldi."),
            ("Asbest ve Silikozis Hastalığına Yakalanan Kot Kumlama İşçileri", "Kot taşlama atölyelerinde toz yutarak ciğerleri iflas eden işçilere devlet malullük maaşı bağladı."),
            ("Madenlerde 6 Saatlik Mesai ve Çift Asgari Ücret Zorunluluğu", "Yer altı maden işçilerine haftada 36 saat çalışma ve en az 2 asgari ücret ödeme kuralı getirildi."),
            ("Ev Hizmetlerinde Çalışanların (Temizlikçi/Bakıcı) Sigortalılığı", "Evlerde gündelik temizliğe giden kadınların kolay SMS ile günlük sigortalanması sağlandı."),
            ("Tarım İşçilerinin Mevsimlik Göçü ve Çadır Alanları Standartları", "Fındık, pamuk ve kayısı toplamaya giden mevsimlik işçilerin çocukları için taşımalı okul ve sağlık çadırları kuruldu."),
            ("Mesleki Yeterlilik Kurumu (MYK) Belgesi Zorunluluğu", "İnşaat ustasından kaynakçıya kadar tehlikeli mesleklerde diploması olmayanlara sertifika şartı kondu."),
            ("İŞKUR Toplum Yararına Program (TYP) ile Geçici İstihdam", "Okul temizlikleri ve afet bölgelerine yüz binlerce vatandaşa geçici kamu istihdamı sağlandı."),
            ("Engelli Kamu Personeli Seçme Sınavı (EKPSS) ile Kamuya Atamalar", "Engelli vatandaşların kendi aralarında yarıştığı özel sınavla kamudaki engelli kotası dolduruldu."),
            ("Şehit Yakınları ve Gazilere Tanınan Kamuda İstihdam ve Haklar", "Vatan için can verenlerin emanetlerine sınavsız devlet memurluğu ve ücretsiz ulaşım hakları verildi.")
        ]
    },
    {
        "id": 26,
        "name": "Kamu Hukuku, Yargı Reformları, Noterlik ve Denetim",
        "source": "Adalet Bakanlığı & Danıştay",
        "char1": "char_adalet_bakani",
        "char2": "char_adli_yargi_hakimi",
        "kw": "Yargı Reformu ve Denetim",
        "cases": [
            ("Kamu Denetçiliği Kurumu'nun (Ombudsman) Kurulması", "Vatandaşların idareyle yaşadığı haksızlıklarda mahkemesiz tavsiye kararı veren denetim kurumu açıldı."),
            ("Sayıştay'ın Kurumsal Denetim Raporlarının TBMM'ye Sunulması", "Bakanlıklar ve belediyelerdeki usulsüzlük ve kamu zararlarını listeleyen raporlar meclisi hareketlendirdi."),
            ("Kamu Görevlileri Etik Kurulu ve Kamuda Hediye Alma Yasağı", "Bürokratların değerli hediye almasını yasaklayan ve etik sözleşme imzalatan standartlar getirildi."),
            ("Kamuda Tasarruf Tedbirleri Genelgesi: Lüks Makam Araçlarının Tasfiyesi", "Kamu kurumlarının yabancı menşeli lüks araç kiralaması ve bina kiralama harcamaları yasaklandı."),
            ("Kamuda Çift Maaş ve Yönetim Kurulu Huzur Hakkı Sınırlamaları", "Bürokratların birden fazla yönetim kurulundan astronomik huzur hakkı almasına tek maaş tavanı kondu."),
            ("KPSS Mülakatlarında Kamera Kaydı ve Objektif Puanlama Talebi", "Yüksek puan alıp mülakatta elenen gençlerin feryatları üzerine mülakat kriterleri tartışmaya açıldı."),
            ("Güvenlik Soruşturması ve Arşiv Araştırması Kanununun Yeniden Yazımı", "AYM'nin kişisel veriler gerekçesiyle iptal ettiği yasa meclis tarafından kriterler netleştirilerek kabul edildi."),
            ("Bölge İdare Mahkemeleri (İstinaf) Sisteminin Hizmete Girmesi", "İdari davalarda Danıştay'ın iş yükünü azaltmak amacıyla bölgesel istinaf mahkemeleri kuruldu."),
            ("Bölge Adliye Mahkemelerinin (Adli İstinaf) Faaliyete Başlaması", "Ceza ve hukuk davalarında Yargıtay'a gitmeden önceki ikinci derece temyiz mahkemeleri açıldı."),
            ("Zorunlu Dava Şartı Arabuluculuk Sisteminin İş Davalarına Gelmesi", "İşe iade ve kıdem tazminatı davalarında mahkemeye gitmeden önce arabulucu masası zorunlu kılındı."),
            ("Ticari Uyuşmazlıklarda Zorunlu Arabuluculuk ile Hızlı Çözüm", "Şirketler arasındaki alacak davalarında yıllar süren yargılama arabuluculukla haftalara indirildi."),
            ("Nöbetçi Noterlik Uygulaması: Hafta Sonları Noter İşlemleri", "Araç alım-satımı ve vekalet işlemlerinin cumartesi-pazar günleri de yapılabilmesi sağlandı."),
            ("Parmak İzi ile Noterlik Kimlik Doğrulaması ve Sahte Vekalet Engeli", "Sahte kimlikle gayrimenkul ve araç satmaya çalışan dolandırıcılara karşı parmak izi okuyucular kondu."),
            ("Ulusal Elektronik Tebligat Sistemi (UETS) ile Kağıtsız Dönem", "Şirketlere, avukatlara ve kamu görevlilerine tebligatların internet üzerinden anında tebliği zorunlu oldu."),
            ("Adli Sicil Kayıtlarının e-Devlet Kapısından Çok Dilli Alınabilmesi", "Adliyelerdeki sabıka kaydı kuyrukları bitirilerek vatandaşın cep telefonuna indirildi."),
            ("Ceza İnfaz Kanunu Değişiklikleri: Denetimli Serbestlik Esnetilmesi", "Cezaevlerindeki doluluğu hafifletmek için denetimli serbestlik süreleri ve açık cezaevi izinleri genişletildi."),
            ("Açık Cezaevi Pandemi İzinlerinin Meclis Yasası ile Kalıcılaşması", "COVID-19 döneminde evlerine gönderilen 100 bin mahkumun cezaları çıkarılan yasayla infaz edildi sayıldı."),
            ("6284 Sayılı Ailenin Korunması ve Kadına Karşı Şiddet Kanunu", "Kadınların beyanını esas alarak hızlı koruma ve uzaklaştırma kararları veren tarihi yasa yürürlükte kaldı."),
            ("Şiddet Vakalarında Elektronik Kelepçe ile GPS İzleme Merkezi", "Uzaklaştırma kararı verilen faillerin mağdura 500 metreden fazla yaklaşmasını engelleyen kelepçeler takıldı."),
            ("Hukuk Mesleklerine Giriş Sınavı (HMGS) Getirilmesi", "Avukat, hakim ve noter olabilmek için mezuniyet sonrası devlet sınavından en az 70 alma şartı getirildi."),
            ("Yargı Etiği Bildirgesi ve Hakimlerin Sosyal Medya Kullanım Kuralları", "Yargı mensuplarının siyasi paylaşım yapmasını ve tarafsızlığı gölgeleyecek temaslarını yasaklayan ilkeler çıktı."),
            ("Bilirkişilik Kanunu (6754) ile Sahte Raporlara Ağır Cezalar", "Mahkemeleri yanlış yönlendiren bilirkişilerin sicilden silinmesi ve hapis cezası getirilmesi sağlandı."),
            ("Uzlaştırmacılık Müessesesi ile Küçük Suçların Mahkemesiz Bitmesi", "Hakaret, basit yaralama ve tehdit suçlarında tarafların helalleşmesiyle davalar düşürüldü."),
            ("Elektronik Duruşma (e-Duruşma) ile Avukatların Bürodan Katılımı", "Avukatların adliyeye gitmeden bürolarından cübbeleriyle duruşmaya canlı bağlanması sağlandı."),
            ("Adalet Saraylarının Kampüs Modeline Geçişi ve Güvenlik Altyapısı", "Çağlayan, Kartal ve Ankara gibi dünyanın en büyük adliye kampüsleri inşa edildi."),
            ("Cezaevi Kampüslerinde İşyurtları Kurumu ve Mahkum Üretimi", "Cezaevlerindeki atölyelerde mahkumlar mobilyadan organik tarıma kadar üretim yaparak meslek edindi."),
            ("Çocuk İzlem Merkezleri (ÇİM) ve Mağdur Çocukların Korunması", "İstismara uğrayan çocukların adliyelerde örselenmeden hastane ortamında tek seferde ifadesi alındı."),
            ("Adli Tıp Kurumu'nun Dijitalleşmesi ve DNA Bankası", "Faili meçhul cinayetleri aydınlatmak için olay yeri biyolojik delilleri DNA veri tabanında eşleştirildi."),
            ("İcra Dairelerinin Modernizasyonu ve 'Yeni İcra Modeli'", "Eski tozlu icra dosyaları yerine UYAP entegreli şeffaf ve hacizsiz tahsilat ofisleri kuruldu."),
            ("Avukatlık Kanunu Değişikliği ve Çoklu Baro Tartışmaları (2020)", "Büyükşehirlerde 5 bin avukatı aşan illerde ikinci baronun kurulabilmesi meclisi ve sokakları hareketlendirdi.")
        ]
    },
    {
        "id": 27,
        "name": "Tarım, Gıda Güvenliği, Hayvancılık ve Köy Hayatı",
        "source": "Tarım ve Orman Bakanlığı",
        "char1": "char_ticaret_bakani",
        "char2": "char_tuketici_dernekleri_baskani",
        "kw": "Tarım ve Gıda Güvenliği",
        "cases": [
            ("Çiftçi Kayıt Sistemi (ÇKS) ve Tarımsal Desteklemeler", "Ekilmeyen tarım arazilerini kayıt altına alan sistemle çiftçilere doğrudan dekar başına gübre ve mazot desteği verildi."),
            ("Tarım Kredi Kooperatifleri Çiftçi Borç Yapılandırmaları", "Kuraklık ve don sebebiyle borcunu ödeyemeyen yüz binlerce çiftçinin traktör hacizleri ertelendi."),
            ("Tarımsal Kuraklık Eylem Planı ve Can Suyu Destekleri", "Yağış almayan İç Anadolu ovalarında çiftçilere Hazine destekli doğrudan kuraklık tazminatı ödendi."),
            ("TARSİM Tarım Sigortaları Havuzu ile Doğal Afet Tazminatları", "Dolu, don, fırtına ve yangından tarlası yanan çiftçilerin zararları devlet katkılı sigortayla karşılandı."),
            ("Mazot ve Gübre Desteğinin Çiftçi Kartlarına Doğrudan Yüklenmesi", "Nakit yerine sadece tarımsal bayilerde geçerli dijital Başak Kart sistemiyle suistimaller önlendi."),
            ("Konya Ovası Obruk Oluşumları ve Aşırı Yeraltı Suyu Tehlikesi", "Kaçak kuyular sebebiyle yer altı sularının çekilmesi mısır tarlalarında devasa obruklar açtı."),
            ("Mavi Tünel Projesi: Göksu Sularının Konya Havzasına Akıtılması", "Toros Dağları delinerek Akdeniz'e boşa akan nehir suları Konya Ovası'nın susuzluğunu dindirdi."),
            ("Çiğ Süt Tavsiye Fiyatı ve Ulusal Süt Konseyi (USK) Kararları", "Yem fiyatları artarken süt fiyatının baskılanması besicilerin damızlık inekleri kesime göndermesine yol açtı."),
            ("Besi Hayvancılığı Teşvikleri ve Damızlık Sığır İthalatı", "Et üretimini artırmak için Avrupa ve Amerika'dan yüksek verimli damızlık düveler köylülere dağıtıldı."),
            ("Şap ve Çiçek Salgınlarına Karşı İller Arası Hayvan Nakil Yasakları", "Hayvan pazarlarında yayılan virüse karşı karantina ilan edilerek kurbanlık sevkiyatları durduruldu."),
            ("Kurban Bayramı Şehir Girişlerinde Hayvan Sağlık Kontrolleri", "Büyükşehirlerin girişlerine kurulan barikatlarda küpesiz ve aşısız kurbanlıklar geri çevrildi."),
            ("Zirai İlaç Kalıntısı Olan Tarım Ürünlerinin İhracattan Geri Dönmesi", "Avrupa'ya ihraç edilen domates ve biberlerde pestisit kalıntısı bulunması tarlalarda teftiş başlattı."),
            ("Tohumculuk Kanunu: Sertifikalı Tohum Şartı ve Ata Tohumları", "Hibrit tohum zorunluluğu tartışılırken Cumhurbaşkanlığı öncülüğünde yerli Ata Tohumu seferberliği açıldı."),
            ("Milli Tohum Gen Bankasının Ankara'da Açılışı", "Anadolu'nun binlerce yıllık endemik bitki ve tahıl tohumları dondurularak gelecek yüzyıllara saklandı."),
            ("Jeotermal Isıtmalı Akıllı Seracılık Hamlesi (Dikili, Sandıklı)", "Yerin altından çıkan sıcak suyla kurulan modern seralarda topraksız tarımla rekor salkım domates üretildi."),
            ("Çiftçilere Sulama Elektriği Borçları Sebebiyle TEDAŞ Kesintileri", "Şanlıurfa ve Mardin'de elektrik dağıtım şirketlerinin trafoları mühürlemesi çiftçileri yollara döktü."),
            ("Tarımsal Sulamada Güneş Enerjisi (GES) Kullanım Hibeleri", "Elektrik faturasından bıkan çiftçilerin tarlalarına güneş paneli kurması devletçe %50 hibeyle desteklendi."),
            ("Balıkçılıkta Av Yasakları ve Trol Avcılığına Karşı Sahil Güvenlik", "Denizlerde balık neslini korumak için 15 Nisan - 1 Eylül arası dip trolüyle avlananlara ağır cezalar kesildi."),
            ("Hamsi Avı Kısıtlaması: Balık Boylarının Küçülmesi Kararı", "Karadeniz'de hamsilerin 9 santimin altına düşmesi üzerine balık neslini kurtarmak için 1 ay av yasağı kondu."),
            ("Sahte Ballara ve Tağşişli Zeytinyağlarına Karşı Bakanlık İfşası", "Glukoz şurubundan bal yapan, zeytinyağına tohum yağı katan hilekar firmaların listesi kamuoyuna açıklandı."),
            ("Gıda Güvenliği Bilgi Sistemi (GGBS) ile Barkodlu Denetim", "Vatandaşların yedikleri ürünün üreticisini ve laboratuvar raporunu karekodla görmesi sağlandı."),
            ("Şeker Pancarı Kotaları ve Fabrikaların Çiftçiye Avans Ödemeleri", "Pancar eken köylülerin tohum, gübre ve söküm paraları hasattan önce fabrikalarca ödendi."),
            ("Zeytinliklerin Madenciliğe Açılması Tartışması ve Danıştay Kararı", "Zeytinlik sahalarda maden aranmasına izin veren yönetmelik çevre davaları sonucu Danıştay'ca iptal edildi."),
            ("Organik Tarım ve İyi Tarım Uygulamaları Teşvikleri", "Kimyasal gübre yerine kompost ve biyolojik mücadele kullanan çiftçilere ekstra destek verildi."),
            ("Sözleşmeli Tarım Modeli ve Alım Garantili Üretim", "Fabrikalar ile çiftçiler arasında ekimden önce fiyat ve tonaj garantili sözleşmeler yasal güvenceye alındı."),
            ("Köyden Kente Göçü Önlemek İçin 'Uzman Eller' Projesi", "Ziraat mühendisi ve veteriner gençlere köyünde hayvancılık yapması için 250 bin TL hibe verildi."),
            ("Atıl Tarım Arazilerinin Kiralanması ve Tarıma Kazandırılması", "Miras yoluyla bölünmüş ve 2 yıldır ekilmeyen tarlaların devlet eliyle komşu çiftçiye kiralanması yasalaştı."),
            ("Kırsal Kalkınma Yatırımlarının Desteklenmesi (KKYDP) Hibeleri", "Süt işleme tesisi, soğuk hava deposu ve zeytinyağı fabrikası kuran üreticilere %50 hibe sağlandı."),
            ("Çaylıkların Yenilenmesi ve Budama Tazminatları", "Yaşlanan çay bahçelerinin gençleştirilmesi için budama yapan üreticilere Çaykur doğrudan gelir desteği verdi."),
            ("Milli Tarım Politikası: Havza Bazlı Üretim Destekleme Modeli", "Hangi ovada hangi ürünün en verimli yetiştiği haritalandırılarak su kaynaklarına uygun ürünler desteklendi.")
        ]
    },
    {
        "id": 28,
        "name": "Sivil Toplum, Çevre Eylemleri ve Kentsel Dayanışma",
        "source": "İçişleri Bakanlığı & Çevre Şehircilik",
        "char1": "char_sehir_plancisi",
        "char2": "char_icisleri_bakani",
        "kw": "Çevre ve Sivil İrade",
        "cases": [
            ("Gezi Parkı Eylemleri: Ağaç Kesimini Önleme Nöbeti (2013)", "Topçu Kışlası inşası için Taksim Gezi Parkı'ndaki ağaçların sökülmesiyle başlayan çadır nöbeti ülke geneline yayıldı."),
            ("Taksim Meydanı'na Çıkan Yolların Kapatılması ve Barikatlar", "Milyonların sokaklara döküldüğü olaylarda polis gaz fişekleri ve TOMA'larla müdahale etti; günlerce çatışmalar sürdü."),
            ("Taksim Dayanışması Heyeti ile Hükümet Arasındaki Zirve", "Başbakan ve bakanlar heyetle sabaha kadar müzakere yürüterek yargı kararı çıkana kadar projeyi durdurdu."),
            ("Gezi Davaları: Osman Kavala ve Çiğdem Mater Mahkumiyetleri", "Gezi Parkı olaylarını hükümeti devirmeye teşebbüs olarak niteleyen mahkeme ağırlaştırılmış müebbet cezaları verdi."),
            ("Bergama Köylüleri ve Eurogold Siyanürlü Altın Madeni Direnişi", "1990'larda yarı çıplak yürüyen köylüler Danıştay'da kazandıkları iptal kararlarıyla tarihe geçti."),
            ("Artvin Cerattepe Yeşil Artvin Derneği ve Maden Nöbeti", "Kafkasör yaylasında maden şirketi araçlarının geçişini önlemek için halk yollara barikatlar kurdu."),
            ("Muğla İkizköy Akbelen Ormanı Direnişi ve Köylü Kadınlar", "Yeniköy-Kemerköy termik santraline kömür sahası açmak için kesilen asırlık çam ağaçlarına köylüler sarıldı."),
            ("Kaz Dağları Kirazlı 'Su ve Vicdan Nöbeti' (2019)", "Altın madeni için yüz binlerce ağacın kesilmesi üzerine Çanakkale'de kurulan çadır kampına sanatçılar akın etti."),
            ("Rize İkizdere Taş Ocağı Eylemleri ve İşkencedere Vadisi", "Lojistik liman inşaatına taş temin etmek için vadide açılan ocağa karşı Karadenizli kadınlar ağaçlara çıktı."),
            ("İstanbul Kuzey Ormanları Savunması ve 3. Köprü Güzergahı", "Kentin akciğerleri olan kuzey ormanlarının otoyol projelerinden korunması için sivil dayanışma kuruldu."),
            ("Validebağ Korusu Nöbeti ve Yapılaşma İptali Davaları", "Üsküdar'daki tarihi korunun millet bahçesi adı altında betonlaşmasını önlemek için mahalleli nöbet tuttu."),
            ("Hevsel Bahçeleri Ekoloji Savunması ve Dicle Vadisi", "Diyarbakır surlarının altındaki 8 bin yıllık UNESCO mirası bahçelerin yapılaşmaya açılması durduruldu."),
            ("Munzur Gözeleri Koruma Alanı ve Peyzaj Projesi İtirazları", "Alevilerce kutsal kabul edilen Tunceli Munzur suyunun doğal yapısını bozan betonlaşma projeleri iptal edildi."),
            ("Hasankeyf Antik Kenti Sular Altında Kalmadan Önceki Mücadele", "Ilısu barajı gölü altında kalacak 12 bin yıllık tarihi kentin kurtarılması için uluslararası kampanyalar yapıldı."),
            ("Zeynel Bey Türbesi ve Artuklu Hamamının Raylar Üzerinde Taşınması", "Hasankeyf'in paha biçilmez tarihi türbesi hidrolik krikolarla 2 kilometre yukarıdaki yeni alana nakledildi."),
            ("Halfeti Batık Kenti ve Birecik Barajı Suları Altındaki Köyler", "Gaziantep ve Urfa arasındaki Fırat suları altında kalan minaresi batık cami dünya turizmine kazandırıldı."),
            ("Tuz Gölü Flamingo Ölümleri ve Vahşi Sulama Engelleri", "Gölü besleyen kanallara kaçak bent kurularak suyun tarlalara çekilmesi yavru flamingoları susuzluktan öldürdü."),
            ("Van Gölü Koruma Eylem Planı ve Dip Çamuru Temizliği", "Kirlilikten kararan göl tabanından yüz binlerce metreküp balçık çıkarılarak sahil kordonu kurtarıldı."),
            ("Kömürlü Termik Santrallerin Bacalarına Filtre Takılması Yasası", "Halk sağlığını zehirleyen santrallere tanınan muafiyetin uzatılması meclis ve Cumhurbaşkanlığı vetosuyla engellendi."),
            ("Marmara Denizi'nin Özel Çevre Koruma Bölgesi İlanı", "Müsilaj felaketi sonrası deniz kirliliğini önlemek amacıyla havzadaki tüm atık deşarjları bakanlığa bağlandı."),
            ("Sokak Hayvanlarını Koruma Dernekleri ve Yaşam Hakkı Eylemleri", "5199 sayılı kanun değişikliğinde ötanazi maddesine karşı yüz binlerce hayvansever meydanlara indi."),
            ("HAYDİ (Hayvan Durum İzleme) Polis Timlerinin Kurulması", "Emniyet bünyesinde kurulan özel birim sokak hayvanlarına eziyet edenleri cep telefonu ihbarıyla yakaladı."),
            ("Doğa Koruma ve Milli Parklar Kaçak Avcılıkla Mücadele", "Yaban keçisi, geyik ve ayı vuran kaçak avcılara rekor tazminatlar ve tüfek müsadere cezaları kesildi."),
            ("Kelaynak Kuşlarının Korunması ve Birecik Üretim İstasyonu", "Nesli tükenmekte olan kuşlar yarı vahşi kafeslerde çoğaltılarak doğaya serbest bırakıldı."),
            ("Kızılırmak Deltası Kuş Cenneti UNESCO Geçici Listesi", "Samsun'daki deltanın kaçak avcılık ve sazlık yangınlarından korunması için sivil çevre timleri kuruldu."),
            ("İğneada Longoz Ormanları ve Nükleer Santral İtirazları", "Avrupa'nın en büyük subasar ormanlarının nükleer ve kömür santrallerinden uzak tutulması sağlandı."),
            ("Büyükada ve Heybeliada Fayton Atlarının Kurtarılması (2020)", "Ruam hastalığı ve kötü muameleyle can veren fayton atları satın alınarak adalara elektrikli araçlar getirildi."),
            ("Dalyan İztuzu Plajı ve Caretta Caretta Deniz Kaplumbağaları", "Kaplumbağaların yumurtlama kumsallarına otel yapılması girişimleri Kaptan June ve halk direnişiyle önlendi."),
            ("Köy Okullarının Kütüphane Seferberliği ve Kitap Toplama Ağları", "Sivil toplum dernekleri Anadolu'daki binlerce köy okuluna yüz binlerce dünya klasiği ulaştırdı."),
            ("Kızılay Çadır Satışı Skandalı ve Yönetim İstifası", "6 Şubat depreminin 3. gününde AHBAP derneğine çadır sattığı ortaya çıkan Kızılay Başkanı istifa etmek zorunda kaldı.")
        ]
    },
    {
        "id": 29,
        "name": "Sokak Güvenliği, Kaçakçılık, Asayiş ve Suçla Mücadele",
        "source": "Emniyet Genel Müdürlüğü & Jandarma",
        "char1": "char_icisleri_bakani",
        "char2": "char_adli_yargi_hakimi",
        "kw": "Asayiş ve Narkotik",
        "cases": [
            ("Sahte İçki (Metil Alkol) Fabrikalarına Yönelik Dev Baskınlar", "Yılbaşı öncesi merdiven altı depolarda üretilen ölümcül içkiler polis ekiplerince ele geçirildi."),
            ("Etil Alkole Denatonyum Benzoat Katılması Zorunluluğu", "İçki yapımında kullanılan tarımsal alkolün içine dünyanın en acı maddesi katılarak içilemez yapıldı."),
            ("Kökünü Kurutma Operasyonları: Mahalle Mahalle Torbacı Avı", "Uyuşturucu satıcılarına karşı 81 ilde şafak vakti binlerce polisle helikopter destekli baskınlar yapıldı."),
            ("Ambarlı Limanı'nda Ele Geçirilen Rekor Kokain Sevkiyatı", "Muz konteynerlerinin soğutucu motorlarına gizlenmiş tonlarca kokain gümrük muhafaza dedektörlerince yakalandı."),
            ("Mersin Uluslararası Limanı Narkotik Operasyonları", "Güney Amerika'dan gelen gemilerde yapılan X-Ray taramalarında yüz milyonlarca liralık uyuşturucu bulundu."),
            ("Yasadışı Silah Kaçakçılığı ve Ruhsatsız Silahlara Ağır Ceza", "İnternetten kurusıkıdan çevrilen tabancaları satan şebekeler çökertildi; ceza alt sınırı artırıldı."),
            ("Düğün ve Asker Uğurlamalarında Havaya Ateş Açma Yasağı", "Kör kurşunla masum çocukların can vermesini engellemek için magandalara doğrudan tutuklama getirildi."),
            ("Çakar Lamba ve Siren Kullanan Yetkisiz Sivil Araçlara Ağır Ceza", "Trafikte emniyet şeridini ihlal eden ve çakar takan lüks araçlar trafikten men edilerek yüksek ceza kesildi."),
            ("Drift Yapan ve Makas Atan Trafik Magandalarına Ehliyet İptali", "Sosyal medyada video paylaşan magandaların ehliyetlerine el konularak psikoteknik teste sevk edildi."),
            ("Alkollü Araç Kullanımında Kademeli Ehliyet Geri Alma", "Promil sınırını aşan sürücülerin ehliyetleri 6 ay, 2 yıl ve 5 yıl süreyle geri alındı."),
            ("Motosiklet Kazalarındaki Artış Karşısında Kask ve Reflektif Yelek", "Özellikle moto-kuryelerin can güvenliği için gece sürüşlerinde fosforlu yelek zorunlu oldu."),
            ("Şehirlerarası Yolcu Otobüslerinde Emniyet Kemeri Zorunluluğu", "Virajda devrilen otobüslerde yolcuların fırlamasını önlemek için kemer takmayanlara ceza yazıldı."),
            ("Elektronik Denetleme Sistemleri (EDS) ve Ortalama Hız Koridorları", "Otoyollarda giriş-çıkış gişeleri arasındaki süreyi hesaplayan radarlarla aşırı hız cezalandırıldı."),
            ("Göçmen Kaçakçılığı Şebekelerine Kalkan Operasyonları", "Tır kasalarında ve teknelerde kaçak göçmen taşıyan organizatörler tutuklandı; araçlarına el konuldu."),
            ("Mobil Göç Noktası Araçları ve Büyükşehir Kimlik Denetimleri", "Meydanlara konuşlandırılan araçlarda parmak izi sorgusuyla düzensiz göçmenler anında tespit edildi."),
            ("Geri Gönderme Merkezleri (GGM) Kapasitesinin Genişletilmesi", "Yakalanan kaçak göçmenlerin sınır dışı edilene kadar barındığı modern kamplar kuruldu."),
            ("Suriye ve İran Sınırına İnşa Edilen Modüler Güvenlik Duvarı", "Sınıra çekilen 3 metre yüksekliğindeki beton bloklar, hendekler ve jiletli tellerle kaçak geçiş durduruldu."),
            ("Sınır Boylarında Elektro-Optik Akıllı Kuleler ve Termal Kameralar", "Gece görüşlü radar ve kameralarla sınır hattı 24 saat yapay zeka tarafından tarandı."),
            ("İnterpol Kırmızı Bültenli Uluslararası Mafya Liderlerinin Yakalanışı", "İstanbul ve Bodrum'da saklanan yabancı organize suç örgütü elebaşları Kafes operasyonlarıyla paketlendi."),
            ("Comanchero Uluslararası Motosiklet Çetesinin Çökertilmesi", "Avustralya merkezli uyuşturucu kartelinin Türkiye'deki milyarlarca liralık mal varlığına el konuldu."),
            ("Sarallar ve Şahinler Suç Örgütlerine Yönelik Şafak Baskınları", "Yıllardır süren yeraltı hesaplaşmalarının tarafları yüzlerce polisin katıldığı operasyonlarla cezaevine yollandı."),
            ("Daltonlar ve Casperlar Gençlik Çetelerine Darbe", "Sosyal medyadan tetikçi kiralayan ve motosikletli saldırı yapan sokak çeteleri çökertildi."),
            ("ATM Dolandırıcılığı ve Kart Kopyalama Şebekelerinin Çökertilmesi", "Banka ATM'lerine sahte kart yuvası ve mikro kamera yerleştiren uluslararası şebeke yakalandı."),
            ("Telefon Dolandırıcıları: 'Kendini Savcı ve Polis Olarak Tanıtanlar'", "Yaşlı vatandaşları arayıp 'adınız teröre karıştı' diyerek altınlarını alan şebekeler suçüstü yapıldı."),
            ("Yasadışı Bahis Sitelerinin Çağrı Merkezlerine Yapılan Baskınlar", "Lüks rezidanslarda kurulan kaçak bahis çağrı merkezlerindeki yüzlerce bilgisayara el konuldu."),
            ("Tarihi Eser Kaçakçılarına Miras Operasyonları", "Kaçak kazılarda bulunan sikkeleri ve heykelleri yurt dışına kaçırmaya çalışan şebekeler basıldı."),
            ("Gümrük Muhafaza Kaçak Akaryakıt ve 'Ulusal Marker' Denetimleri", "Sanayi solventini akaryakıta karıştıran kaçak benzin istasyonlarının pompaları mühürlendi."),
            ("Kaçak Sigara ve Elektronik Sigara (Puff) İstilası", "Sınırlardan sokulan milyonlarca paket kaçak sigara ve aromalı puf cihazı zabıta ve polisçe toplandı."),
            ("Fuhuş ve İnsan Ticareti Mağduru Yabancı Kadınların Kurtarılması", "Pasaportlarına el konulup zorla çalıştırılan yabancı uyruklu kadınlar operasyonla kurtarılıp ülkelerine gönderildi."),
            ("Çocuk Kaçırma ve Organ Mafyası Yalan Haberlerine Karşı Emniyet", "Sosyal medyada yayılan 'siyah minibüs çocuk kaçırıyor' asılsız dedikoduları siber devriyelerce yalanlandı.")
        ]
    },
    {
        "id": 30,
        "name": "Cumhuriyetin İkinci Yüzyılı, Türkiye Yüzyılı ve Gelecek Vizyonu",
        "source": "Cumhurbaşkanlığı & TBMM",
        "char1": "char_cumhurbaskani",
        "char2": "char_tbmm_baskani",
        "kw": "İkinci Yüzyıl ve Devlet Aklı",
        "cases": [
            ("29 Ekim 2023: Türkiye Cumhuriyeti'nin 100. Yılının Kutlanması", "Gazi Mustafa Kemal Atatürk'ün emaneti cumhuriyet 85 milyonun tek yürek olduğu tarihi törenlerle kutlandı."),
            ("İstanbul Boğazı'nda 100 Savaş Gemisinin Tören Geçişi", "Donanmanın amiral gemisi TCG Anadolu öncülüğünde 100 gemi Boğaz'da halkı ve Cumhurbaşkanı'nı selamladı."),
            ("SoloTürk ve Türk Yıldızları'nın Boğaz Semalarında Tarihi Uçuşu", "Boğaz köprüsü üzerinde yapılan nefes kesen akrobasi gösterileri milyonlarca İstanbulluyu büyüledi."),
            ("'Türkiye Yüzyılı' Vizyon Belgesinin Açıklanması", "Cumhuriyetin ikinci yüzyılında kalkınma, bilim, adalet ve savunma sanayii odaklı hedefler ilan edildi."),
            ("Yeni ve Sivil Anayasa Çağrıları: 1982 Darbe Metninden Kurtuluş", "TBMM Başkanı partilerle görüşerek milletin kendi eliyle yapacağı ilk sivil anayasa turlarını başlattı."),
            ("TBMM Anayasa Uzlaşma Turları ve Temel Haklar Maddeleri", "Meclisteki tüm siyasi grupların temsil edildiği komisyonla anayasa maddeleri üzerinde diyalog arandı."),
            ("Anayasa Mahkemesi Kararlarının Bağlayıcılığı İlkesinin Korunması", "Hukuk devleti ve anayasal düzenin temeli olan mahkeme kararlarına saygı devlette mutabakat oldu."),
            ("Yargı Bağımsızlığı ve Hakim Teminatının Güçlendirilmesi", "Coğrafi teminat ve liyakat kriterleriyle hakim ve savcıların bağımsızlığı anayasal güvenceye alındı."),
            ("Kamuda Mülakatın Kaldırılması ve Tam Liyakat Sistemi", "Kamuya personel alımlarında torpil iddialarını bitirecek yazılı sınav ve şeffaf kura sistemine geçildi."),
            ("Devlet Denetleme Kurulu'nun (DDK) Kamu Kurumlarındaki Teftişleri", "Cumhurbaşkanlığına bağlı DDK kamu kurumları, üniversiteler ve TFF üzerinde denetimlerini sıklaştırdı."),
            ("Milli İstihbarat Teşkilatı'nın (MİT) Yeni Kale Yerleşkesine Taşınması", "Etimesgut'taki yüksek güvenlikli modern istihbarat üssüyle MİT küresel bir teşkilat haline geldi."),
            ("MİT'in Sınır Ötesinde Yürüttüğü Nokta Operasyonlar", "Suriye ve Irak'ta terör örgütünün sözde yürütme konseyi üyeleri SİHA ve özel tim operasyonlarıyla etkisiz kılındı."),
            ("Dijital Devlet ve Ulusal Yapay Zeka Stratejisi (2021-2025)", "Kamuda büyük veri ve yerli yapay zeka modelleri geliştirilerek bürokratik işlemler otomatikleştirildi."),
            ("Savunma Sanayiinde Yerlilik Oranının %80'in Üzerine Çıkması", "1990'larda %20 olan yerlilik oranı 30 yılda insansız sistemler, füzeler ve zırhlılarla tarihi zirveye çıktı."),
            ("Paris İklim Anlaşması'nın TBMM Tarafından Onaylanması", "Küresel iklim krizine karşı Türkiye karbon emisyonlarını azaltma ve yeşil kalkınma taahhüdünü onayladı."),
            ("2053 Net Sıfır Emisyon Hedefi ve Yeşil Kalkınma Devrimi", "Sanayide fosil yakıtlar yerine hidrojen, güneş ve nükleer enerjiye geçiş için yol haritası çizildi."),
            ("İklim Değişikliği Kanunu Taslağı ve Emisyon Ticaret Sistemi (ETS)", "Sanayi tesislerine karbon kotası getiren ve yeşil dönüşümü finanse eden piyasa mekanizması kuruldu."),
            ("Avrupa Birliği Sınırda Karbon Düzenleme Mekanizmasına (SKDM) Uyum", "Türk ihracatçısının Avrupa sınırında karbon vergisi ödememesi için fabrikalarda yeşil sertifikaya geçildi."),
            ("Türkiye Uzay Ajansı (TUA) ve Milli Uzay Programı", "Ay'a sert iniş yapacak yerli hibrit roket motorları ve uzay limanı projeleri resmi devlet programı oldu."),
            ("Ay Araştırma Misyonu (AYAP) ve Hibrit Roket Motoru Testleri", "DeltaV tarafından geliştirilen hibrit yakıtlı uzay motoru uzay ortamı testlerini başarıyla geçti."),
            ("Arktik ve Antarktika Bilim Seferleri: Türk Bilim Üssünün Kurulması", "Kutup denizlerinde bilimsel araştırmalar yapan Türk bilim heyeti Beyaz Kıta'da bayrağımızı dalgalandırdı."),
            ("Milli Muharip Uçak KAAN'ın Seri Üretim ve İhracat Planları", "Dost ve müttefik ülkelerle ortak üretim müzakereleri yapılarak ilk filonun teslim tarihi belirlendi."),
            ("KIZILELMA ve ANKA-3'ün TCG Anadolu'ya İniş-Kalkış Testleri", "Dünyada ilk kez insansız savaş uçaklarının kısa pistli amfibi gemiden kalkması için çalışmalar başladı."),
            ("Milli Çip Fabrikası ve 65 Nanometre Üretim Altyapısı", "Gebze'deki temiz odalarda otomotiv ve savunma kartları için yerli silikon çipler basıldı."),
            ("Türkiye'nin Doğrudan Yabancı Yatırım Rüzgarı ve Küresel Hub", "Asya ile Avrupa arasındaki tedarik zincirinde Türkiye küresel üretim ve lojistik üssü oldu."),
            ("Kalkınma Yolu Projesi: Basra Körfezi'nden Avrupa'ya Ticaret Koridoru", "Irak ile imzalanan tarihi anlaşmayla Fav Limanı'ndan Türkiye'ye hızlı demiryolu ve otoyol inşası başladı."),
            ("Zengezur Koridoru Açılışı ve Türk Dünyası Entegrasyonu", "Nahçıvan üzerinden Azerbaycan'ı ve Orta Asya Türk Cumhuriyetlerini bağlayan stratejik hat için adımlar atıldı."),
            ("Türk Devletleri Teşkilatı'nın (TDT) Küresel Güce Dönüşmesi", "Semerkant ve Astana zirveleriyle Türk dünyası ortak alfabe, ortak ordu ve ekonomik serbest bölge kurdu."),
            ("Dâire-i Adliyye Felsefesi: Cumhuriyetin Temeli Adalettir!", "Adalet olmazsa devlet çöker, halk huzur bulmaz, hazine bereketlenmez; adalet cumhuriyetin yegane bekasıdır."),
            ("Milletin Duası ve Devletin Bekası: Tam Bağımsız Türkiye!", "'Egemenlik kayıtsız şartsız milletindir' ilkesiyle Cumhuriyetin ikinci yüzyılı adalet ve refahla mühürlendi.")
        ]
    }
]

print("DOMAINS_21_TO_30 loaded successfully.")
