# -*- coding: utf-8 -*-
"""
Data for Domains 11 to 20 (300 cases: 401 to 700)
"""

DOMAINS_11_TO_20 = [
    {
        "id": 11,
        "name": "6 Şubat 2023 Kahramanmaraş Depremleri ve Asrın Felaketi",
        "source": "AFAD & Kriz Masası",
        "char1": "char_afad_baskani",
        "char2": "char_cevre_sehircilik_bakani",
        "kw": "Deprem ve Yeniden İnşa",
        "cases": [
            ("Pazarcık Depremi (7.7) ve 11 İlde İlk Yıkım", "04.17'de Kahramanmaraş Pazarcık merkezli ilk sarsıntı 11 ilde on binlerce binayı saniyeler içinde yıktı."),
            ("Elbistan Depremi (7.6) ve İkinci Büyük Darbe", "İlk depremden 9 saat sonra 13.24'te vuran ikinci dev sarsıntı hasarlı binaları yerle bir etti ve kurtarma ekiplerini vurdu."),
            ("4. Seviye Uluslararası Alarm ve 93 Ülkenin Yardımı", "Türkiye Cumhuriyet tarihinin en büyük uluslararası yardım çağrısını yaptı; binlerce yabancı arama-kurtarma ekibi sahaya indi."),
            ("11 İlde 3 Ay Süreyle Olağanüstü Hal (OHAL) İlanı", "Yağma olaylarını önlemek ve koordinasyonu hızlandırmak amacıyla afet bölgesinde anayasal OHAL ilan edildi."),
            ("Hatay Antakya Şehir Merkezinin ve Tarihi Dokunun Yok Oluşu", "Antakya'nın tarihi çarşıları, camileri, kiliseleri ve Meclis binası tamamen enkaza dönüştü."),
            ("Rönesans Rezidans Yıkımı ve Müteahhidin Kaçışı", "'Cennetten bir köşe' vaadiyle satılan rezidansın müteahhidi havalimanında kaçarken yakalanıp tutuklandı."),
            ("Adıyaman İsias Otel Faciası ve Şampiyon Melekler", "Kıbrıslı ortaokul voleybol takımının kaldığı kaçak katlı otelin yıkılmasıyla 35 sporcu evladımız şehit oldu."),
            ("Kahramanmaraş Ebrar Sitesi ve Yüzlerce Can Kaybı", "Her biri onlarca cana mezar olan sitenin müteahhitleri ve fenni mesulleri hakkında yakalama kararları çıkarıldı."),
            ("Deprem Bölgesinde Yağmacılık Olayları ve Askeri Devriyeler", "Asayişi sağlamak amacıyla jandarma komandolar ve polis özel harekat timleri şehirlerde 24 saat devriyeye başladı."),
            ("İskenderun Limanı'nda Çıkan Yangın ve Söndürme Gemileri", "Depremle devrilen yüzlerce konteyner alev aldı; yangın TSK İHA'ları ve itfaiye helikopterlerince söndürüldü."),
            ("Hatay Havalimanı Pistinin Kırılması ve Hızlı Onarımı", "Fay hattı üzerindeki pistin yarılması uçuşları durdurdu; İGA ve belediye ekipleri 4 günde pisti uçuşa açtı."),
            ("Konteyner Kent Seferberliği: 1 Milyon Depremzedeye Yuva", "Çadır kentlerden hızla klima, tuvalet ve mutfağı olan 215 bin konteynerlik şehirlere geçiş sağlandı."),
            ("Türkiye Tek Yürek Ortak Yayını ve Rekor Bağış", "200 televizyon kanalının ortak yayınında 115 milyar liralık tarihi bağış toplandı."),
            ("Köy Evleri İnşası: Yöresel Ahır ve Müstakil Konutlar", "Kırsal bölgelerde hayvan yetiştiricilerine özel çelik konstrüksiyon köy evleri hızla teslim edildi."),
            ("450 Bin Kalıcı Konut Hedefi ve Şantiye Ordusu", "Cumhuriyet tarihinin en büyük şantiye seferberliğiyle 110 bin işçi 11 ilde kalıcı konut inşaatına başladı."),
            ("Deprem Bölgesinde Üniversite ve Okul Eğitimi Düzenlemesi", "Öğrencilere ülke genelinde nakil kolaylığı sağlandı; bölgedeki üniversiteler uzaktan eğitime geçti."),
            ("Enkaz Kaldırma ve Asbest Riski Denetimleri", "Milyonlarca ton molozun döküm sahalarında çevre kirliliği ve asbest yayılımına karşı sulama tedbirleri alındı."),
            ("Deprem Bölgesinde Mücbir Sebep ve Vergi Muafiyetleri", "Esnaf ve şirketlerin vergi, SGK ve kredi borçları 1 yıl süreyle faizsiz ertelendi."),
            ("Deprem Bölgesi İstihdam ve İşsizlik Maaşı Desteği", "Fabrikaların kapanmasını önlemek için personele doğrudan Hazine destekli nakdi ücret desteği verildi."),
            ("Adana Çukurova Binalarında Zemin ve Kolon İncelemeleri", "Göl manzaralı lüks binaların yıkılması sonrası kolon kesme iddiaları hakkında adli tahkikat başlatıldı."),
            ("Malatya Tarihi Çarşı ve Yeşilyurt Kentsel Yenilenmesi", "Malatya'nın kalbi olan Bakırcılar Çarşısı ve çarşı merkezi bakanlık tarafından baştan projelendirildi."),
            ("Gaziantep Nurdağı ve İslahiye İlçelerinin Sıfırdan İnşası", "Fay hattı üzerindeki yerleşim yerleri güvenli dağ eteklerine kaydırılarak yeni şehirler kuruldu."),
            ("Şanlıurfa ve Adıyaman'ı Vuran Deprem Sonrası Sel Felaketi", "Çadır ve konteyner kentlerin kurulduğu günlerde taşan dereler 21 vatandaşımızın hayatını kaybetmesine yol açtı."),
            ("Deprem Bölgesi Rezerv Alan Yasası Düzenlemesi", "Şehir merkezlerinin planlı ve sağlam dönüştürülmesi için rezerv yapı alanı yetkileri genişletildi."),
            ("Defin İşlemleri ve DNA Eşleştirme Merkezleri", "Kimliği belirsiz naaşların Adli Tıp ve savcılık gözetiminde parmak izi ve DNA ile kayıt altına alınması sağlandı."),
            ("Refakatsiz Kalan Depremzede Çocukların Korunması", "Ailelerini kaybeden yüzlerce bebek ve çocuk Aile Bakanlığı yurtlarında devlet korumasına alındı."),
            ("Deprem Bölgesi Kardeş Şehir ve Belediye Dayanışması", "Türkiye'nin tüm büyükşehir ve ilçe belediyeleri deprem illerine aşevi, su ve temizlik üsleri kurdu."),
            ("Deprem Davaları: Soruşturulan 1500 Müteahhit ve Mühendis", "Adalet Bakanlığı kurduğu özel Deprem Suçları Soruşturma Bürolarıyla yüzlerce sorumluyu cezaevine koydu."),
            ("Kalıcı Konut Kura Çekilişleri ve İlk Anahtar Teslimleri", "Depremin 1. yıl dönümünde 76 bin konut kura çekilişiyle hak sahibi ailelere teslim edildi."),
            ("11 İlin İmar Planı ve Yeni Fay Yasası Hazırlıkları", "Fay hatlarının üzerine bina yapılmasını kesin olarak yasaklayan imar mevzuatı meclis gündemine taşındı.")
        ]
    },
    {
        "id": 12,
        "name": "Mega Ulaşım ve Altyapı Projeleri (Marmaray, Avrasya, Köprüler, YHT, İGA)",
        "source": "Ulaştırma Bakanlığı",
        "char1": "char_sehir_plancisi",
        "char2": "char_hazine_bakani",
        "kw": "Mega Projeler ve Ulaşım",
        "cases": [
            ("Marmaray: Asya ile Avrupa'yı Bağlayan Asrın Projesi", "İstanbul Boğazı'nın 60 metre derinliğine batırılan tüp tünellerle iki kıta demiryoluyla birleştirildi."),
            ("Marmaray Kazılarında Çıkan Theodosius Limanı Arkeolojisi", "Yenikapı istasyonu kazılarında 37 antik batık gemi ve binlerce tarihi eser ortaya çıkarıldı."),
            ("Avrasya Tüneli: İki Kıta Arasında Araç Geçişi", "Boğaz'ın altından otomobillerin geçişini sağlayan çift katlı tüp tünel trafiği 15 dakikaya indirdi."),
            ("Yavuz Sultan Selim Köprüsü (3. Boğaz Köprüsü)", "59 metre tabliye genişliği ve üzerindeki raylı sistem hattıyla dünyanın en geniş asma köprüsü açıldı."),
            ("Osmangazi Köprüsü: Körfez Geçişi 4 Dakika", "İzmit Körfezi'ni boydan boya geçen asma köprüyle İstanbul-İzmir otoyolu bağlantısı tamamlandı."),
            ("1915 Çanakkale Köprüsü: 2023 Metre Orta Açıklık", "Cumhuriyetin 100. yılını simgeleyen ve kırmızı-beyaz kuleleriyle Çanakkale Boğazı'nı birleştiren köprü açıldı."),
            ("İstanbul Havalimanı (İGA) İnşası ve Dünyanın En Büyükleri", "Karadeniz kıyısında eski kömür ocakları üzerine kurulan mega havalimanı ilk fazıyla hizmete girdi."),
            ("Atatürk Havalimanı'nın Taşınması: Tarihi Büyük Göç", "Cumhuriyet tarihinin en büyük lojistik taşınmasıyla yüzlerce uçak ve binlerce tır 45 saatte İGA'ya geçti."),
            ("Atatürk Havalimanı Pistlerine Şehir Hastanesi Yapımı", "Pandemi döneminde kullanılmayan pistler üzerine 1008 yataklı Prof. Dr. Murat Dilmener Acil Durum Hastanesi açıldı."),
            ("Atatürk Havalimanı Millet Bahçesi Projesi", "Eski havalimanı arazisi 2 milyon metrekarelik dev yeşil alan ve kültür merkezine dönüştürüldü."),
            ("Ankara-Eskişehir Yüksek Hızlı Treninin (YHT) Açılışı (2009)", "Türkiye hızlı tren işleten dünyadaki 8. ülke olarak ilk hızlı tren seferini başlattı."),
            ("Ankara-Konya YHT Hattı ve Seyahat Süresinin Düşmesi", "Konya ovasından geçen hızlı tren başkent ile Mevlana şehrini 1.5 saate bağladı."),
            ("Ankara-İstanbul YHT Hattı ve Doğançay Ripajı", "Bilecik ve Sakarya dağlarını delen tünellerle başkent ile metropol hızlı trenle kavuştu."),
            ("Ankara-Sivas YHT Hattı: Doğuya Açılan Hızlı Raylar", "Kırıkkale ve Yozgat üzerinden geçen 405 kilometrelik hat seyahat süresini 2 saate indirdi."),
            ("Bakü-Tiflis-Kars (BTK) Demiryolu: Demir İpekyolu", "Londra'dan Pekin'e kesintisiz demiryolu yük taşımacılığı sağlayan hat Kafkasları birleştirdi."),
            ("Gayrettepe-İstanbul Havalimanı Hızlı Metrosu (M11)", "Türkiye'nin 120 km/s ile en hızlı giden sürücüsüz metro hattı havalimanını şehir merkezine bağladı."),
            ("Kuzey Marmara Otoyolu ve Akıllı Ulaşım Sistemleri", "Akyazı'dan Kınalı'ya kadar uzanan otoyol transit ağır vasıtaları İstanbul şehir içinden çıkardı."),
            ("İstanbul-İzmir Otoyolu ile 3.5 Saate İnen Seyahat", "Eski yoldaki 8 saatlik yolculuk yeni otoyol ile Ege turizmini ve sanayisini şahlandırdı."),
            ("Zigana Tüneli: Avrupa'nın En Uzun Çift Tüplü Tüneli", "Trabzon ile Gümüşhane arasında 14.5 kilometrelik devasa tünelle kışın geçit vermeyen dağ aşıldı."),
            ("Ovit Tüneli: Rize-Erzurum Arasında 14 Kilometrelik Kış Zaferi", "2 bin 640 rakımlı Ovit Dağı kış aylarında 5 ay kapanırken tünel ile 12 ay açık hale geldi."),
            ("Ilgaz 15 Temmuz İstiklal Tüneli", "Karadeniz'i İç Anadolu'ya bağlayan zorlu Ilgaz Dağı geçişi tünelle güvenli hale getirildi."),
            ("Kamu-Özel İşbirliği (KÖİ) Modeli ve Geçiş Garantileri", "Köprü ve otoyollardaki Hazine araç geçiş garantileri mecliste ve kamuoyunda bütçe tartışmalarına yol açtı."),
            ("Kanal İstanbul ÇED Raporu ve İtiraz Davaları", "Marmara ile Karadeniz'i bağlayacak yapay su yolu projesinin çevre etki raporu tartışıldı."),
            ("Kanal İstanbul Sazlıdere Köprüsü Temel Atma Töreni", "Proje güzergahında inşa edilen ilk köprünün temelleri Cumhurbaşkanı tarafından atıldı."),
            ("Çamlıca Televizyon Kulesi ve Anten Kirliliğinin Sonu", "İstanbul Boğazı tepelerindeki onlarca paslı verici sökülerek tek bir kulede toplandı."),
            ("Galataport İstanbul Kruvaziyer Limanı ve Sahil Erişimi", "200 yıldır kapalı olan Karaköy sahili dünyanın ilk yer altı kruvaziyer terminaliyle halka açıldı."),
            ("Haliç Tersanesi Restorasyonu ve Sanat Üssü", "Fatih Sultan Mehmet'in kurduğu 600 yıllık tersane müzeler ve sanat galerileriyle ihya edildi."),
            ("Haydarpaşa Garı Yangını ve Tarihi Restorasyon", "Çatısında çıkan yangın sonrası gar binası ve çevresindeki antik Khalkedon kalıntıları müzeye bağlandı."),
            ("Rize-Artvin Havalimanı: Deniz Dolgusu Üzerine 2. Meydan", "Karadeniz dalgaları arasına milyonlarca ton taş dökülerek çay bardağı kulesiyle açıldı."),
            ("Ordu-Giresun Havalimanı (OR-Gİ): Avrupa'nın İlk Deniz Havalimanı", "Deniz üzerine inşa edilen Türkiye'nin ilk ada havalimanı iki Karadeniz ilini birleştirdi.")
        ]
    },
    {
        "id": 13,
        "name": "Savunma Sanayii, Havacılık ve Uzay Çağı (KAAN, TB2, Kızılelma, TCG Anadolu)",
        "source": "Savunma Sanayii Başkanlığı",
        "char1": "char_savunma_sanayii_baskani",
        "char2": "char_savunma_bakani",
        "kw": "Milli Teknoloji ve Savunma",
        "cases": [
            ("Milli Muharip Uçak KAAN'ın İlk Uçuşu (21 Şubat 2024)", "5. nesil hayalet savaş uçağı KAAN Mürted meydanından havalanarak Türkiye'yi dünya ligine soktu."),
            ("Bayraktar TB2 SİHA'nın TSK Envanterine Girişi", "Terörle mücadelede ezber bozan yerli SİHA, mağara ve kampları nokta atışıyla imha etti."),
            ("Bayraktar Akıncı TİHA: 40 Bin Feet İrtifada Uçan Kale", "Çift türbin motorlu Akıncı seyir füzeleri ve hassas mühimmat atarak rekorlar kırdı."),
            ("Bayraktar Kızılelma İnsansız Savaş Uçağının İlk Uçuşu", "Jet motorlu insansız savaş uçağı pistten kalkıp ilk manevralarını başarıyla tamamladı."),
            ("TUSAŞ ANKA ve ANKA-3 Uçan Kanat Hayalet SİHA", "Radara yakalanmayan V formundaki hayalet insansız uçak ilk uçuşunu gerçekleştirdi."),
            ("HÜRJET Süpersonik İleri Eğitim ve Taarruz Uçağı", "Ses hızını aşan ilk yerli jet eğitim uçağı test uçuşlarında Mach 1.4 hızına ulaştı."),
            ("HÜRKUŞ Temel Eğitim Uçağının EASA Uluslararası Sertifikasyonu", "Avrupa Havacılık Emniyeti Ajansı'ndan tip sertifikası alan ilk yerli sivil uçak oldu."),
            ("TCG Anadolu Çok Maksatlı Amfibi Hücum Gemisi (LHD)", "Dünyanın ilk SİHA gemisi konseptiyle üretilen donanmanın amiral gemisi hizmete girdi."),
            ("MİLGEM ADA Sınıfı Korvetler (Heybeliada, Büyükada, Burgazada, Kınalıada)", "Milli Gemi Projesi kapsamında yerli imkanlarla üretilen 4 korvet denizlerde göreve başladı."),
            ("TCG İstanbul İstif Sınıfı İlk Milli Fırkateyn", "Yerli dikey atım sistemi MİDLAS ve Atmaca füzeleriyle donatılan milli fırkateyn teslim edildi."),
            ("Reis Sınıfı Denizaltılar: TCG Piri Reis ve Havadan Bağımsız Tahrik", "Haftalarca su yüzüne çıkmadan operasyon yapabilen milli denizaltı suya indirildi."),
            ("Altay Ana Muharebe Tankı Projesi ve Seri Üretim", "Kore güç grubu entegrasyonuyla testleri tamamlanan Altay tankı TSK'ya teslim edilmeye başlandı."),
            ("Roketsan TAYFUN Kısa Menzilli Balistik Füzesi", "Rize'den Sinop açıklarına yapılan test atışıyla 561 kilometre menzile ulaşarak caydırıcılık sağladı."),
            ("Roketsan ATMACA Gemisavar Füzesi", "Amerikan Harpoon füzelerinin yerini alan yerli seyir füzesi hedef gemiyi tam isabetle batırdı."),
            ("Roketsan ÇAKIR Minyatür Seyir Füzesi", "Akıncı TİHA'dan atılan Çakır füzesi hedefini metre hassasiyetiyle imha etti."),
            ("TÜBİTAK SAGE SOM Havadan Atılan Seyir Füzesi Ailesi", "250 km menzilli sığınak delici milli mühimmat F-16'ların ve SİHA'ların ana vurucu gücü oldu."),
            ("ASELSAN KORAL Mobil Elektronik Harp Sistemi", "Sınır ötesindeki düşman radarlarını ve füze sistemlerini kör eden elektronik harp kalkanı sahada parladı."),
            ("ASELSAN SİPER Uzun Menzilli Bölge Hava Savunma Sistemi", "100+ km menzilde yüksek irtifa hedeflerini vuran yerli hava savunma sistemi testleri geçti."),
            ("HİSAR-A+ ve HİSAR-O+ Alçak ve Orta İrtifa Hava Savunma Bataryaları", "Saha birliklerini hava saldırılarına karşı koruyan yerli füze kalkanı seri üretime girdi."),
            ("KORKUT 35 mm İkiz Namlulu Hava Savunma Sistemi", "Parçacıklı akıllı mühimmatıyla kamikaze İHA ve füzeleri havada imha eden sistem birliklere dağıtıldı."),
            ("TÜBİTAK SAGE GÖKDOĞAN ve BOZDOĞAN Hava-Hava Füzeleri", "Görüş içi ve görüş ötesi füze atışlarıyla Amerikan AIM serisine yerli alternatif üretildi."),
            ("T129 ATAK Helikopterinin Seri Üretimi ve İhracatı", "Filipinler ve Nijerya'ya ihraç edilen taarruz helikopteri terörle mücadelede kilit rol oynadı."),
            ("T625 GÖKBEY Helikopterinin Yerli TS1400 Motoruyla Uçuşu", "TEI tarafından üretilen milli turboşaft motoruyla ilk uçuşunu yapan genel maksat helikopteri tarih yazdı."),
            ("Türksat 5A ve Türksat 5B Haberleşme Uyduları", "SpaceX Falcon 9 roketiyle uzaya gönderilen uydular geniş bant internet ve yayın kapasitesini artırdı."),
            ("Türksat 6A İlk Yerli ve Milli Haberleşme Uydusu", "TÜBİTAK UZAY ve ASELSAN ortaklığıyla üretilen milli uydu uzaydaki yerini aldı."),
            ("İMECE Yüksek Çözünürlüklü Yer Gözlem Uydusu", "Metre altı çözünürlükle tüm dünyadan askeri istihbarat görüntüsü alan yerli gözlem uydusu fırlatıldı."),
            ("Alper Gezeravcı'nın Ax-3 ile İlk Türk Uzay İnsanı Olması", "Uluslararası Uzay İstasyonu'nda 14 gün kalarak 13 bilimsel deneyi tamamlayan ilk astronotumuz tarihe geçti."),
            ("Tuva Cihangir Atasever'in Yörünge Altı Bilimsel Uçuşu", "Virgin Galactic mekiğiyle yörünge altı uçuş gerçekleştiren ikinci Türk astronot deneylerini yaptı."),
            ("TEKNOFEST Havacılık Festivali Rekorları", "Milyonlarca gencin yarıştığı havacılık ve uzay festivali dünyanın en büyük teknoloji buluşması oldu."),
            ("TÜBİTAK ÇAKIL Milli İşlemcisi ve Çip Fabrikası Projesi", "Savunma ve otomotiv sektörünün bağımlılığını bitirecek yerli çip üretim tesisi temeli atıldı.")
        ]
    },
    {
        "id": 14,
        "name": "Karadeniz Gazı, Gabar Petrolü, Akkuyu Nükleer ve Enerji Keşifleri",
        "source": "Enerji ve Tabii Kaynaklar Bakanlığı",
        "char1": "char_hazine_bakani",
        "char2": "char_sanayi_bakani",
        "kw": "Enerji Bağımsızlığı",
        "cases": [
            ("Fatih Sondaj Gemisinin Tuna-1 Kuyusunda Doğalgaz Keşfi", "Türkiye'nin ilk yerli sondaj gemisi Karadeniz'de 320 milyar metreküplük tarihi doğalgaz rezervi keşfetti."),
            ("Karadeniz Sakarya Gaz Sahasının 710 Milyar Metreküpe Çıkması", "Yeni kuyuların açılmasıyla Karadeniz'deki toplam keşif trilyon liralık dev bir ekonomik değere ulaştı."),
            ("Filyos Limanı Doğalgaz İşleme Tesisinin Açılışı", "Denizin 2 bin metre altından çekilen borularla karaya ulaştırılan gaz şebekeye bağlandı."),
            ("Konutlara 1 Yıl Boyunca Aylık 25 Metreküp Ücretsiz Gaz Hibesi", "Cumhurbaşkanı kararıyla keşif müjdesi olarak mutfak ve sıcak su tüketimi bedelsiz karşılandı."),
            ("Gabar Dağı Şehit Esma Çevik Sahasında Petrol Keşfi", "Terörden temizlenen Gabar dağında günlük binlerce varil kaliteli ham petrol üretimi başladı."),
            ("Gabar Şehit Aybüke Yalçın Sahası: Günlük 100 Bin Varil Hedefi", "Cumhuriyet tarihinin en büyük kara petrol sahasında 41 gravite rekor kaliteli petrol fışkırdı."),
            ("Akkuyu Nükleer Güç Santrali İnşaatı (4 Reaktör, 4800 MW)", "Türkiye'nin ilk nükleer enerji santralinde reaktör binaları hızla yükseldi."),
            ("Akkuyu Sahasına İlk Nükleer Yakıtın Getirilmesi ve Tören", "Uluslararası Atom Enerjisi Kurumu onayıyla yakıtın tesise girmesiyle Akkuyu 'nükleer tesis' statüsü kazandı."),
            ("TürkAkım Doğalgaz Boru Hattının Açılışı", "Karadeniz derinliklerinden geçen çift hatla Rus gazı doğrudan Trakya Kıyıköy'e ulaştırıldı."),
            ("TANAP (Trans Anadolu Doğalgaz Boru Hattı) Projesi", "Azerbaycan Şahdeniz gazını Türkiye üzerinden Avrupa sınırına taşıyan dev boru hattı hizmete girdi."),
            ("Bakü-Tiflis-Ceyhan (BTC) Boru Hattında Rekor Sevkıyat", "Hazar petrollerini Akdeniz'e taşıyan hat üzerinden yüz milyonlarca varil ham petrol ihraç edildi."),
            ("Mavi Akım Doğalgaz Hattı Kapasite Artışı", "Samsun üzerinden gelen hatta yapılan kompresör iyileştirmeleriyle gaz arz güvenliği sağlandı."),
            ("Kuzey Marmara Silivri Yeraltı Doğalgaz Depolama Tesisi", "Türkiye'nin en büyük deniz üstü doğalgaz deposu tam kapasiteyle kış aylarının sigortası oldu."),
            ("Tuz Gölü Yeraltı Doğalgaz Depolama Tesisinin Genişletilmesi", "Tuz mağaralarında depolanan gaz kapasitesi 5 milyar metreküpe çıkarıldı."),
            ("Yenilenebilir Enerji Kaynak Alanları (YEKA) İhaleleri", "Güneş ve rüzgarda yerli aksam şartıyla dünya çapında düşük fiyat rekorları kırıldı."),
            ("Karapınar GES: Avrupa'nın En Büyük Güneş Tarlası", "Konya çöllerinde kurulan santral 2 milyon hanenin elektrik ihtiyacını tek başına karşıladı."),
            ("Çatılarda Lisanssız Güneş Enerjisi (GES) Kurulum Kolaylığı", "Vatandaşların ve fabrikaların çatılarına güneş paneli kurup fazlasını satması kanunlaştı."),
            ("Rüzgar Enerjisinde 12 Bin Megavat Barajının Aşılması", "Ege ve Marmara rüzgarları Türkiye'nin elektriğinin %11'ini üreten dev bir sektöre dönüştü."),
            ("Aydın ve Ege Jeotermal Enerji Santralleri (JES) Patlaması", "Yerin altından çıkan sıcak suyla hem elektrik üretildi hem de seralar ısıtıldı."),
            ("Bandırma Bor Karbür Üretim Tesisinin Açılışı", "Eti Maden'in çıkardığı ham bor katma değerli zırh ve aşındırıcı tozuna dönüştürüldü."),
            ("Eskişehir Beylikova Nadir Toprak Elementleri Sahası", "Dünyanın en büyük 2. nadir element rezervi keşfedilerek çip ve mıknatıs üretimi için adım atıldı."),
            ("Ilısu Prof. Dr. Veysel Eroğlu Barajı ve HES", "Dicle Nehri üzerine kurulan baraj elektrik üretirken tarihi eserler başarıyla yukarı taşındı."),
            ("Yusufeli Barajı: 275 Metre Gövde Yüksekliğiyle Türkiye Rekoru", "Çoruh Nehri'nin azgın suları üzerinde dünyanın en yüksek 5. kemer barajı elektrik üretmeye başladı."),
            ("GAP Sulama Tünelleri (Suruç ve Silvan) ile Harran Yeşillenmesi", "Fırat'ın suları dev tünellerden geçerek kurak ovaları tarım cennetine çevirdi."),
            ("Doğalgazda Eşel Mobil ve Sübvansiyon Destekleri", "Küresel krizde faturaların %75'i Hazine tarafından karşılanarak vatandaş korundu."),
            ("Elektrik Faturalarında Kademeli Tarife Uygulaması", "Dar gelirli hanelerin düşük tüketimi sübvanse edilirken aşırı tüketime piyasa fiyatı uygulandı."),
            ("Organize Sanayi Bölgelerinde Yaşanan Kış Gaz Kısıntıları", "İran'ın kış ortasında gazı kesmesiyle fabrikalarda 3 günlük üretime ara verildi."),
            ("Oruç Reis Gemisinin Somali Açıklarında Petrol Görevi", "İmzalanan askeri ve ekonomik anlaşmayla Türk sismik gemisi Somali denizlerinde petrol aramaya gitti."),
            ("Libya ile İmzalanan Ortak Hidrokarbon Arama Mutabakatı", "Trablus hükümetiyle Türkiye'nin ortak petrol ve gaz arama protokolü imzalandı."),
            ("Sinop Nükleer Santral Projesi Zemin Etütleri", "Karadeniz kıyısında ikinci nükleer santral için Güney Kore ve Rusya ile müzakereler yürütüldü.")
        ]
    },
    {
        "id": 15,
        "name": "Ekonomi Politikaları, Enflasyon, KKM ve Rasyonel Dönüş",
        "source": "Hazine ve Maliye Bakanlığı & TCMB",
        "char1": "char_hazine_bakani",
        "char2": "char_merkez_bankasi_baskani",
        "kw": "Para Politikası ve İstikrar",
        "cases": [
            ("Berat Albayrak'ın Bakanlığı ve Yeni Ekonomi Modeli (2018)", "Hazine ve Maliye Bakanlığı döneminde düşük faiz ve cari fazla odaklı model hayata geçirildi."),
            ("Berat Albayrak'ın Instagram'dan İstifa Mektubu Paylaşması", "Pazar gecesi sosyal medyadan yayınlanan mektup Türk siyasi tarihinde benzeri görülmemiş kriz yarattı."),
            ("Naci Ağbal'ın Merkez Bankası Başkanlığı ve Şok Faiz Artırımı", "Ağbal döneminde politika faizi %19'a çıkarılarak kur frenlendi ancak 4 ay sonra görevden alındı."),
            ("Şahap Kavcıoğlu Dönemi ve Faiz İndirimi Dalgaları (2021)", "'Faiz sebep, enflasyon neticedir' tezi doğrultusunda politika faizi %19'dan %8.5'e kadar düşürüldü."),
            ("20 Aralık 2021 Gecesi Kur Korumalı Mevduatın (KKM) İlanı", "Dolar 18 TL'yi aşınca açıklanan KKM sistemiyle kur bir gecede 12 TL'ye geriledi."),
            ("KKM'nin Hazine ve Merkez Bankası'na Getirdiği Kur Farkı Yükü", "Milyarlarca liralık kur farkı bütçeden karşılanarak kamu maliyesine devasa fatura bindi."),
            ("Enflasyonun %85 ile Son 25 Yılın Zirvesini Görmesi (2022)", "Gıda, enerji ve konut fiyatlarındaki artışla tüketici enflasyonu tarihi rekor kırdı."),
            ("Mehmet Şimşek'in Kabineye Dönüşü: 'Rasyonel Zemine Döneceğiz'", "2023 seçimleri sonrası göreve gelen Şimşek geleneksel ortodoks para ve maliye politikalarını başlattı."),
            ("Hafize Gaye Erkan'ın İlk Kadın Merkez Bankası Başkanı Olması", "ABD'deki kariyerini bırakıp gelen Erkan faiz artırım döngüsünü başlatarak rasyonel süreci yönetti."),
            ("Politika Faizinin %8.5'ten %50'ye Yükseltilmesi Seferberliği", "Enflasyonu dizginlemek amacıyla Merkez Bankası faizi adım adım tarihi zirveye tırmandırdı."),
            ("Fatih Karahan'ın Merkez Bankası Başkanlığına Atanması", "Erkan'ın istifasının ardından Başkan Yardımcısı Karahan görevi devralarak sıkı duruşu korudu."),
            ("Türkiye'nin FATF Gri Listesinden Çıkarılması (Singapur 2024)", "Kara para ve terör finansmanıyla mücadele yasalarıyla Türkiye uluslararası gri listeden kurtuldu."),
            ("Merkez Bankası Swap Hariç Net Rezervlerinin Artıya Geçmesi", "Eksi 60 milyar dolardan dönen rezervler yabancı sermaye girişiyle tarihi toparlanma kaydetti."),
            ("KKM Stokunun 140 Milyar Dolardan Eritilmesi Programı", "Alınan makroihtiyati tedbirlerle mudiler standart TL mevduata geçirilerek KKM küçültüldü."),
            ("Şirket Bilançolarında Enflasyon Düzeltmesi (Muhasebesi)", "Yüksek enflasyon sebebiyle reel olmayan karların vergilendirilmesini önleyen muhasebe sistemi açıldı."),
            ("Kredi Kartı Nakit Avans ve Taksit Limitlerine Kısıtlamalar", "Tüketim çılgınlığını frenlemek için kredi kartı faizleri ve nakit çekim limitleri daraltıldı."),
            ("İkinci El ve Sıfır Araçta '6 Ay ve 6 Bin Kilometre' Kuralı", "Galericilerin sıfır arabaları stoklayıp fahiş fiyata satmasını engelleyen ticaret genelgesi çıktı."),
            ("Sıfır Araç Bayilerine Aksesuar Zorlaması ve Fahiş Fiyat Cezaları", "Araç yokluğu yaratarak el altından ekstra para isteyen bayilere ağır para cezaları kesildi."),
            ("Konut Kiralarında 2 Yıl Süreyle Uygulanan %25 Zam Tavanı", "Kiracıları korumak amacıyla getirilen kira artış sınırı ev sahibi-kiracı davalarını patlattı."),
            ("Sulh Hukuk Mahkemelerinde Tahliye Davaları Patlaması", "Kira uyuşmazlıkları mahkemeleri kilitledi; binlerce tahliye dosyası yıllara yayıldı."),
            ("Kira Uyuşmazlıklarında Zorunlu Arabuluculuk Sisteminin Başlaması", "Mahkemeye gitmeden önce arabulucuya gitme şartıyla yüz binlerce kira krizi uzlaşmayla çözüldü."),
            ("%25 Kira Artış Tavanının Temmuz 2024'te Sona Ermesi", "İki yılın ardından tavan kuralı kaldırılarak yeniden TÜFE 12 aylık ortalama sınırına dönüldü."),
            ("Asgari Ücret Tespit Komisyonu'nun Yılda İki Kez Toplanması", "Enflasyon karşısında eriyen maaşlar için 2022 ve 2023 yıllarında Temmuz ayında ara zamlar yapıldı."),
            ("Asgari Ücretten Gelir ve Damga Vergisinin Sıfırlanması Kanunu", "Milyonlarca çalışanın maaşından kesilen vergiler kalıcı olarak devlet tarafından karşılandı."),
            ("EYT (Emeklilikte Yaşa Takılanlar) Yasası ve 2 Milyon Yeni Emekli", "Prim gününü dolduranların yaş şartı aranmadan emekli edilmesiyle SGK'ya büyük yük bindi."),
            ("En Düşük Emekli Maaşına Hazine Desteğiyle Taban Tutar", "Kök maaşı düşük kalan emeklilerin aylıkları Hazine sübvansiyonuyla 12.500 TL tabanına bağlandı."),
            ("Altın İthalatına Kota Konulması ve Kaçak Altın Operasyonları", "Cari açığı artıran altın alımlarını kısmak için kota getirildi; havaalanlarında kaçak külçeler yakalandı."),
            ("Borsa İstanbul Halka Arz (IPO) Çılgınlığı ve 8 Milyon Yatırımcı", "Enflasyondan kaçan milyonlarca vatandaş şirket hisselerine akın ederek BIST rekorları kırdı."),
            ("Tanzim Satış Çadırları: İstanbul ve Ankara'da Ucuz Sebze", "Hal komisyoncularının fahiş fiyatlarına karşı belediyeler meydanlarda domates ve patates sattı."),
            ("Tarım Kredi Kooperatif Marketlerinin 3 Bin Şubeye Ulaşması", "Gıda fiyatlarını frenlemek için doğrudan üreticiden alıp indirimli satan marketler ağı kuruldu.")
        ]
    },
    {
        "id": 16,
        "name": "Dijitalleşme, Siber Olaylar, Kripto Vurgunları ve Fenomenler",
        "source": "BTK & MASAK & Emniyet Siber",
        "char1": "char_adalet_bakani",
        "char2": "char_sanayi_bakani",
        "kw": "Siber Güvenlik ve Kripto",
        "cases": [
            ("e-Devlet Kapısı'nın (turkiye.gov.tr) 2008'de Hizmete Açılması", "Vatandaşların tüm kamu işlemlerini tek şifreyle internetten yapmasını sağlayan dijital devrim başladı."),
            ("UYAP Ulusal Yargı Ağı ile Duruşma Tutanaklarının Dijitalleşmesi", "Adliyelerdeki kağıt dosyalar tarihe karıştı; avukatlar ve hakimler ekran başına geçti."),
            ("e-Nabız Kişisel Sağlık Sistemi ve Tüm Tıbbi Geçmişin Ekranı", "Hastanelerdeki tahlil, röntgen ve reçeteler vatandaşın cep telefonuna yüklendi."),
            ("Çipli T.C. Kimlik Kartları ve Ehliyetlerin Çipe Yüklenmesi", "Eski nüfus cüzdanları yerine parmak izi korumalı elektronik çipli kimlikler dağıtıldı."),
            ("Kişisel Verileri Koruma Kurumu'nun (KVKK) Faaliyete Başlaması", "Vatandaşların izinsiz aranan telefonları ve sızdırılan verileri için şirketlere ağır cezalar kesildi."),
            ("Yemeksepeti Veri Tabanı Sızıntısı Soruşturması ve KVKK Cezası", "Milyonlarca kullanıcının adres ve telefon bilgilerinin hacker forumlarında satılması soruşturuldu."),
            ("e-Devlet Veri Sızıntısı İddiaları ve İletişim Başkanlığı İncelemesi", "MERNİS verilerinin çalındığı dedikoduları üzerine siber güvenlik denetimleri en üst düzeye çıkarıldı."),
            ("BTK Ulusal Siber Olaylara Müdahale Merkezi (USOM) Altyapısı", "Türkiye'ye yönelik siber saldırıları 7/24 takip edip engelleyen siber güvenlik kalkanı kuruldu."),
            ("Sosyal Medya Yasası: Küresel Platformlara Temsilci Atama Şartı", "Twitter, Meta, TikTok ve Google'a Türkiye'de muhatap olacak şirket ve temsilci açma mecburiyeti geldi."),
            ("Platformların Temsilcilik Bildirimi ve Reklam Yasaklarının Önlenmesi", "Yasal sürede temsilci atayan sosyal ağ devleri milyonlarca liralık vergi ve ceza yükünü kabul etti."),
            ("Instagram Platformuna Katalog Suçlar Gerekçesiyle Erişim Engeli", "BTK kararıyla günlerce kapatılan Instagram yapılan müzakereler ve taahhütler sonrası açıldı."),
            ("Discord Platformuna Çocuk Güvenliği ve İstismar Gerekçesiyle Yasak", "Şantaj ve istismar çetelerinin kullandığı belirlenen platform Ankara mahkeme kararıyla engellendi."),
            ("Roblox Çevrimiçi Oyun Platformuna Çocuk İstismarı Nedeniyle Engel", "Çocukların cinsel istismara maruz kaldığı iddiaları üzerine Adana sulh ceza hakimliği erişimi kesti."),
            ("Ekşi Sözlük Web Sitesine Mahkeme Kararlarıyla Erişim Engelleri", "Milli güvenlik ve kamu düzeni gerekçesiyle kapatılan platform alan adı değişiklikleriyle devam etti."),
            ("Wikipedia'nın (Vikipedi) 2.5 Yıllık Erişim Engelinin AYM ile Kalkması", "Anayasa Mahkemesi'nin ifade özgürlüğü ihlali kararı sonrası ansiklopedi sitesi yeniden açıldı."),
            ("Kripto Para Borsası THODEX ve Faruk Fatih Özer Vurgunu", "2 milyar dolarlık kripto parayla Arnavutluk'a kaçan borsa kurucusu 400 bin kişiyi mağdur etti."),
            ("Faruk Fatih Özer'in İadesi ve 11.196 Yıl Hapis Cezası", "İnterpol ile yakalanıp Türkiye'ye getirilen zanlıya dolandırıcılıktan rekor hapis cezası verildi."),
            ("Vebitcoin Kripto Borsasının Çöküşü ve Yöneticilerin Tutuklanması", "Nakit çekimleri durduran Muğla merkezli kripto borsasının sahipleri MASAK raporuyla tutuklandı."),
            ("Mehmet Aydın (Tosuncuk) Çiftlik Bank Saadet Zinciri Dolandırıcılığı", "Sanal ineklerle yüksek kar vaat eden saadet zinciriyle yüz binlerce kişiyi dolandıran zanlı kaçtı."),
            ("Mehmet Aydın'ın Brezilya'da Teslim Oluşu ve Kartal Cezaevi", "Brezilya Sao Paulo elçiliğine teslim olan Tosuncuk Türkiye'ye getirilerek yargılanmaya başlandı."),
            ("TBMM Kripto Varlık Yasası: SPK Lisansı ve Ağır Denetim", "Kripto para borsalarını devlet kontrolüne alan ve sermaye şartı getiren yasa kabul edildi."),
            ("Dilan ve Engin Polat Kara Para Aklama ve Güzellik Merkezleri Dosyası", "Lüks arabalar ve şatafatlı hayat paylaşan fenomen çift MASAK ve vergi operasyonuyla tutuklandı."),
            ("Fenomenler Dosyası: MASAK'ın Sosyal Medya Zenginleri İncelemesi", "Güzellik salonları ve e-ticaret üzerinden fatura kesen onlarca fenomenin şirketlerine kayyum atandı."),
            ("Seçil Erzan Özel Bankacılık Fonu: Futbol Dünyasını Sarsan Vurgun", "Fatih Terim, Arda Turan, Emre Belözoğlu gibi ünlüleri gizli yüksek faizli fonla soyan banka müdiresi tutuklandı."),
            ("Ayhan Bora Kaplan Suç Örgütü ve Ankara Emniyetinde Deprem", "Esenboğa Havalimanı'nda kaçarken yakalanan mafya lideri sonrası emniyet müdürleri hakkında davalar açıldı."),
            ("Sinan Ateş Cinayeti: Ankara Çukurambar'da Gün Ortasında Suikast", "Eski Ülkü Ocakları Genel Başkanı'nın sokak ortasında vurularak katledilmesi siyaseti sarstı."),
            ("Dezenformasyonla Mücadele Yasası: TCK 217/A Maddesi Kapsamı", "'Halkı yanıltıcı bilgiyi alenen yayma' suçunu düzenleyen yasa meclisten geçerek yürürlüğe girdi."),
            ("Yasadışı Bahis Sitelerine Yönelik MASAK ve Emniyet Operasyonları", "Yurtdışı merkezli kaçak kumar sitelerinin banka hesaplarına ve pos cihazlarına el konuldu."),
            ("Ünlü İsimlere ve Fenomenlere Yasadışı Bahis Reklamı Soruşturması", "Sosyal medyada yasadışı bahis sitelerini öven şarkıcı ve fenomenler polis operasyonuyla gözaltına alındı."),
            ("Ulusal Siber Güvenlik Başkanlığı Kurulması Hazırlıkları", "Tüm kamu kurumlarının verilerini tek çatı altında koruyacak siber savunma teşkilatı projelendirildi.")
        ]
    },
    {
        "id": 17,
        "name": "Vicdan Davaları ve Toplumsal Adalet (Narin Güran, Yenidoğan Çetesi, Münevver, Özgecan)",
        "source": "Adalet Bakanlığı & Adli Tıp",
        "char1": "char_adalet_bakani",
        "char2": "char_adli_yargi_hakimi",
        "kw": "Adalet ve Toplumsal Vicdan",
        "cases": [
            ("Narin Güran Cinayeti: 19 Gün Sonra Çuvalda Bulunan Melek", "Diyarbakır Tavşantepe köyünde kaybolan 8 yaşındaki Narin dere yatağında çuval içine gizlenmiş bulundu."),
            ("Tavşantepe Köyündeki Sessizlik Duvarı ve Aile Boyu Tutuklamalar", "Cinayeti gizlemek için organize olan muhtar amca Salim Güran, anne, ağabey ve itirafçı tutuklandı."),
            ("Yenidoğan Çetesi Skandalı: Bebek Acil Hastalarını Para İçin Öldüren Ağ", "İstanbul'da 112 sevklerini manipüle ederek bebekleri anlaşmalı özel hastanelerde yoğun bakımda ölüme terk eden çete deşifre oldu."),
            ("Büyükçekmece Savcısı Yavuz Engin'in Makamında Tehdit Edilmesi", "Çete avukatının savcıyı makamında 'seni öldürürüz' tehdidine savcının boyun eğmeyip çeteyi çökertmesi destan oldu."),
            ("Ruhsatları İptal Edilip Mühürlenen 10 Özel Hastane", "Bebek ölümlerine sahne olan ünlü özel hastanelerin ruhsatları Sağlık Bakanlığı'nca iptal edildi ve kapılarına kilit vuruldu."),
            ("Münevver Karabulut Cinayeti (2009) ve Testereli Vahşet", "Bahçeşehir'de cesedi gitar kılıfında çöp konteynerinde bulunan genç kızın davası Türkiye'yi ağlattı."),
            ("Cem Garipoğlu'nun 197 Gün Süren Firarı ve Cezaevinde İntiharı", "Aylarca polisten kaçtıktan sonra teslim olan katil zanlısı Silivri cezaevinde intihar etti."),
            ("Cem Garipoğlu'nun Mezarının Fethi Kabir ile Açılması (2024)", "Ölmediği ve kaçırıldığı iddiaları üzerine savcılık kararıyla mezar açılarak DNA örnekleri incelendi."),
            ("Özgecan Aslan Cinayeti (Tarsus 2015): Kadına Şiddete İsyan", "Minibüste tecavüze direnirken katledilip yakılan üniversite öğrencisi milyonları sokaklara döktü."),
            ("Emine Bulut Cinayeti (Kırıkkale 2019): 'Ölmek İstemiyorum'", "Kızının gözleri önünde boğazı kesilen annenin son feryadı tüm Türkiye'de infiale yol açtı."),
            ("Pınar Gültekin Cinayeti ve Haksız Tahrik İndiriminin Bozulması", "Muğla'da varilde yakılan üniversite öğrencisinin katiline verilen tahrik indirimi Yargıtay'ca iptal edildi."),
            ("Ceren Özdemir Cinayeti (Ordu 2019): Cezaevi Firarisi Katil", "Bale öğrencisi genç kızı evinin kapısında bıçaklayan katilin açık cezaevi firarisi olması tepki çekti."),
            ("Aleyna Çakır ve Esra Hankulu Şüpheli Ölümleri: Ümitcan Uygun", "Şüpheli ölümler sonrası tutuklanan sanık ağır ceza mahkemesinde mahkumiyete çarptırıldı."),
            ("Şule Çet Davası: Plazanın 20. Katından Düşme ve Adli Tıp Mücadelesi", "İntihar süsü verilen cinayeti aydınlatmak için adli tıp uzmanları ve kadın dernekleri tarihi mücadele verdi."),
            ("Rabia Naz Vatan Şüpheli Ölümü ve TBMM Araştırma Komisyonu", "Giresun Eynesil'de şüpheli şekilde vefat eden 11 yaşındaki kız için meclis özel araştırma komisyonu kurdu."),
            ("Manisa Davası (1995): Liseli Gençlere İşkence Yapan Polislerin Cezası", "Yıllar süren yargılama sonunda işkenceci polislere hapis cezaları Yargıtay'ca onandı."),
            ("Metin Göktepe Cinayeti: Gözaltında Öldürülen Gazetecinin Davası", "Polislerin birbirini ele vermesiyle sonuçlanan yargılamada sorumlular hapis cezası aldı."),
            ("Ali İsmail Korkmaz Davası: Gezi Eylemlerinde Eskişehir'de Darp", "Sokak arasında darp edilerek komaya giren üniversite öğrencisinin failleri polis ve esnaf mahkum edildi."),
            ("Berkin Elvan Davası: Gaz Fişeğiyle Vurulan Çocuğun Yargılaması", "Okmeydanı'nda gaz fişeği atan polis memuru ağır ceza mahkemesinde hapis cezasına çarptırıldı."),
            ("Ethem Sarısülük Davası: Kızılay'da Polisin Silah Kullanması", "Ankara'daki gösteriler sırasında ateş açan polis memuru yargılanarak cezalandırıldı."),
            ("Çorlu Tren Faciası Davası (2018): 25 Can Kaybı ve Bürokratlar", "Menfezin altının boşalmasıyla devrilen tren için TCDD üst yöneticileri ağır cezalara çarptırıldı."),
            ("Soma Maden Faciası Davası (2014): 301 Şehit ve Olası Kast", "Maden patronu ve yöneticilerine olası kast ve bilinçli taksirden hapis cezaları verildi."),
            ("Ermenek Kömür Madeni Su Baskını: 'Oğlum Yüzme Bilmezdi'", "Ocağı su basmasıyla şehit olan 18 madenci için yırtık lastik ayakkabılı babanın acısı sembol oldu."),
            ("Bartın Amasra Maden Patlaması (2022): 43 Madencinin Şehadeti", "Grizu patlamasında ihmalleri belirlenen maden müessese müdürü ve mühendisler tutuklandı."),
            ("Hendek Havai Fişek Fabrikası Patlaması ve İş Güvenliği Davası", "Sakarya'da patlayan fabrikada 7 işçi öldü; fabrika sahibi hapis cezasına çarptırıldı."),
            ("Adana Aladağ Kız Öğrenci Yurdu Yangını (2016)", "Yangın merdiveni kilitli olduğu için can veren 11 ortaokul öğrencisi için yurt yöneticileri tutuklandı."),
            ("Ensar Vakfı Karaman Yurdu İstismar Skandalı", "Öğrencilere istismarda bulunan öğretmen hakkında 508 yıl rekor hapis cezası verildi."),
            ("Palu Ailesi Skandalı: TV Programındaki İtiraflar ve Tutuklamalar", "Cinayet, tecavüz ve gasp iddiaları canlı yayında itiraf edilince Kocaeli'de aile boyu tutuklama yapıldı."),
            ("Kadına Karşı Şiddette 6284 Sayılı Koruma Kanunu Uygulaması", "Uzaklaştırma ve koruma kararlarıyla yüz binlerce kadına devlet zırhı sağlandı."),
            ("AYM ile Yargıtay Arasındaki Can Atalay Yetki ve İhlal Çatışması", "AYM'nin tahliye kararına Yargıtay 3. Ceza Dairesi'nin uymaması ve suç duyurusu yargı krizi başlattı.")
        ]
    },
    {
        "id": 18,
        "name": "Eğitim, Üniversiteler, Sınav Skandalları ve Gençlik Politikaları",
        "source": "Milli Eğitim Bakanlığı & YÖK",
        "char1": "char_adalet_bakani",
        "char2": "char_basbakan",
        "kw": "Eğitim ve Gençlik",
        "cases": [
            ("8 Yıllık Kesintisiz Zorunlu İlköğretim Yasası (1997)", "28 Şubat kararları doğrultusunda çıkarılan yasayla ilkokul ve ortaokul birleştirilerek kesintisiz yapıldı."),
            ("İmam Hatip Liselerine Katsayı Engeli Uygulaması", "Meslek liselilerin üniversite sınavında katsayı puanlarının düşürülmesi milyonlarca öğrenciyi mağdur etti."),
            ("Katsayı Engelinin YÖK Tarafından 2009-2011'de Kaldırılması", "Tarihi kararla meslek lisesi ve imam hatip mezunlarının alan dışı tercih yapma hakkı teslim edildi."),
            ("Üniversitelerde Başörtüsü Yasağı ve İkna Odaları Travması", "Üniversite kapılarında başörtülü öğrencilerin peruk takmaya veya başını açmaya zorlanması kriz yarattı."),
            ("2010 YÖK Genelgesiyle Üniversitelerde Başörtüsü Yasağının Sonu", "YÖK Başkanı Yusuf Ziya Özcan'ın genelgesiyle kampüslerdeki fiili yasak tamamen kalktı."),
            ("2013 Demokratikleşme Paketiyle Kamuda Başörtüsü Serbestliği", "Memur, öğretmen, doktor ve mühendislerin kamuda başörtüsüyle çalışabilmesi yasalaştı."),
            ("TSK, Emniyet ve Yargı Mensuplarına Başörtüsü Düzenlemesi", "Kadın polislerin, askerlerin ve hakimlerin başörtüsü takabilmesi yönetmeliklerle güvenceye bağlandı."),
            ("4+4+4 Kademeli Zorunlu Eğitim Sistemine Geçiş (2012)", "Eğitim 12 yıla çıkarılarak ilkokul, ortaokul ve lise olarak 4'er yıllık kademelere ayrıldı."),
            ("Dershanelerin Kapatılması ve Özel Liseye Dönüştürülmesi Krizi", "Hükümetin dershaneleri kapatma kararı cemaat yapılanmasıyla iplerin kopmasına neden oldu."),
            ("2010 KPSS Eğitim Bilimleri Sınavı Soru Hırsızlığı ve İptali", "Soruların cemaat evlerine sızdırıldığı belgelenince sınav iptal edildi; savcılık dev soruşturma açtı."),
            ("2022 KPSS Lisans Sınavında Soru Benzerliği Skandalı", "Bir yayınevinin deneme sınavındaki soruların birebir çıkması üzerine ÖSYM Başkanı gece görevden alındı."),
            ("Üniversite Sınavında ÖSS'den YGS-LYS Sistemine Geçiş (2010)", "Tek aşamalı sınav yerine iki aşamalı, çok oturumlu sınav modeli uygulanmaya başlandı."),
            ("YGS-LYS Sisteminden YKS (TYT-AYT) Sistemine Geçiş (2018)", "Müfredatı sadeleştiren ve temel yeterliliği ölçen Yükseköğretim Kurumları Sınavı getirildi."),
            ("Üniversite Giriş Sınavlarında Baraj Puanının Kaldırılması (2022)", "Ön lisans ve lisans programları için uygulanan 150 ve 180 baraj puanları tamamen kaldırıldı."),
            ("81 İle Üniversite Hamlesi: Her İlde En Az Bir Devlet Üniversitesi", "Hakkari'den Şırnak'a, Iğdır'dan Ardahan'a kadar tüm illerde devlet üniversiteleri açıldı."),
            ("Öğrenci Yurtları Yetersizliği ve 'Barınamıyoruz' Eylemleri (2021)", "Kira artışları sonrası parklarda yatan öğrencilerin eylemleri yurt kapasitesini gündeme getirdi."),
            ("KYK Yurt Kapasitesinin 950 Bin Yatağa Ulaştırılması Seferberliği", "Yeni yurt binaları açılarak Türkiye dünyada en yüksek devlet yurdu kapasitesine sahip ülke oldu."),
            ("KYK Öğrenim Kredisi Faizlerinin Silinmesi Kanunu (2022)", "Milyonlarca mezunun borcuna binen TÜFE ve gecikme faizleri silinerek sadece ana para ödemesi getirildi."),
            ("FATİH Projesi: Akıllı Tahta ve Tablet Bilgisayar Dağıtımı", "Tüm okulların sınıflarına fiber internet ve etkileşimli akıllı tahtalar kuruldu."),
            ("EBA (Eğitim Bilişim Ağı): Pandemide Uzaktan Eğitimin Omurgası", "Koronavirüs salgınında TRT ve internet üzerinden milyonlarca çocuğa uzaktan eğitim verildi."),
            ("Öğretmenlik Meslek Kanunu (ÖMK): Uzman ve Başöğretmenlik", "Kariyer basamakları sınavıyla yüz binlerce öğretmene uzman ve başöğretmen tazminatı verildi."),
            ("Boğaziçi Üniversitesi Rektör Atamaları ve Akademisyen Eylemleri", "Prof. Dr. Melih Bulu'nun rektör atanması sonrası akademisyenlerin sırt dönme eylemleri aylarca sürdü."),
            ("ODTÜ Kampüsünden Yol Geçirilmesi ve Ağaç Sökümü Tartışması", "Ankara Büyükşehir Belediyesi'nin gece yarısı yol açma operasyonu öğrencilerle polisi karşı karşıya getirdi."),
            ("Türkiye Yüzyılı Maarif Modeli: Yeni Müfredat Reformu", "Bilgi ezberletmek yerine beceri ve erdem temelli yeni ders müfredatı kademeli olarak başlatıldı."),
            ("Mesleki Eğitim Merkezleri (MESEM) Hamlesi ve Çıraklık Teşvikleri", "Haftada 1 gün okul, 4 gün işyeri modeliyle sanayiye yüz binlerce çırak kazandırıldı."),
            ("Üniversite Hastanelerinin Mali Krizleri ve Hazine Destekleri", "Tıbbi cihaz borçları sebebiyle kilitlenen üniversite tıp fakülteleri borç yapılandırmasıyla kurtarıldı."),
            ("Tıpta Uzmanlık Sınavı (TUS) ve Sağlıkçıların Branş Tercihleri", "Malpraktis davaları ve şiddet sebebiyle cerrahi branşların boş kalması acil teşvik paketini getirdi."),
            ("Okullarda Ücretsiz Yemek ve Temiz İçme Suyu Seferberliği", "Taşımalı eğitim ve okul öncesi öğrencilerine her gün sıcak yemek dağıtımı başlatıldı."),
            ("Özel Okul Fiyatlarındaki Fahiş Artışlar ve MEB Tavanı", "Özel okul ücretlerine getirilen TEFE-TÜFE zam tavanı veliler ile okul sahipleri arasında tartışıldı."),
            ("Liselerde Telefon Yasağı ve Dijital Detoks Genelgesi", "Sınıflarda dikkat dağınıklığını önlemek için derse telefonla girilmesi kesin olarak yasaklandı.")
        ]
    },
    {
        "id": 19,
        "name": "Sağlık Sistemi, Şehir Hastaneleri, Pandemi ve Salgınlar",
        "source": "Sağlık Bakanlığı & Bilim Kurulu",
        "char1": "char_saglik_bakani",
        "char2": "char_icisleri_bakani",
        "kw": "Sağlıkta Dönüşüm ve Salgın",
        "cases": [
            ("SSK Hastaneleri Çilesi ve Sabah 4'te Reçete Kuyrukları", "1990'larda işçilerin SSK hastanesi kapılarında numara ve ilaç için günlerce beklemesi tarihe karıştı."),
            ("Sağlıkta Dönüşüm Programı: SSK Hastanelerinin Devri (2005)", "Tüm SSK ve kurum hastaneleri Sağlık Bakanlığı'na devredilerek tek çatı altında birleştirildi."),
            ("Sosyal Güvenlik Kurumu'nun (SGK) Kurulması", "SSK, Bağ-Kur ve Emekli Sandığı birleştirilerek tüm vatandaşlar eşit sağlık sigortasına kavuşturuldu."),
            ("Genel Sağlık Sigortası (GSS) ile 85 Milyonun Kapsanması", "Geliri brüt asgari ücretin üçte birinden az olanların primini devletin ödediği evrensel sigorta kuruldu."),
            ("Aile Hekimliği Uygulamasının 81 İle Yaygınlaştırılması", "Her mahalleye aile hekimi atanarak birinci basamak sağlık hizmetleri ücretsiz hale getirildi."),
            ("İlaç Takip Sistemi (İTS): İlaçta Sahteciliği Bitiren Karekod", "Kupür kesme sahtekarlığını önleyen dünyadaki ilk uçtan uca ilaç takip karekod sistemi kuruldu."),
            ("MEDULA Provizyon Sistemi: Eczaneler ile SGK Arasında Canlı Ağ", "Hastaneler ve eczaneler tüm işlemleri internetten onaylatarak fatura kuyruklarını bitirdi."),
            ("Kamu-Özel İşbirliği (KÖİ) Şehir Hastaneleri Hamlesi", "Yozgat, Adana, Mersin, Isparta ve Kayseri'den başlayarak dev şehir hastaneleri zinciri açıldı."),
            ("Başakşehir Çam ve Sakura Şehir Hastanesinin Açılışı", "Pandemi felaketinin en ağır günlerinde açılan dev kompleks binlerce yoğun bakım yatağı sağladı."),
            ("Ankara Bilkent ve Etlik Şehir Hastaneleri Kampüsleri", "Eski ihtisas hastanelerini tek devasa kampüste toplayan şehir hastaneleri başkentin omurgası oldu."),
            ("112 Acil Filosuna Ambulans Uçak ve Helikopterlerin Katılması", "Dağ başındaki hastalardan yeni doğan bebeklere kadar herkes için ücretsiz hava ambulansı sağlandı."),
            ("Kuş Gribi Salgını (H5N1 - 2006) ve Tavuk İtlafları", "Doğubayazıt'ta başlayan ve çocuk ölümlerine yol açan salgında milyonlarca kanatlı hayvan itlaf edildi."),
            ("Domuz Gribi Salgını (H1N1 - 2009) ve Aşı Kampanyası", "Dünyayı saran salgında aşı alımı Başbakan ve Sağlık Bakanı arasında polemiklere sahne oldu."),
            ("11 Mart 2020: Türkiye'de İlk Resmi COVID-19 Vakasının İlanı", "Sağlık Bakanı Fahrettin Koca gece yarısı ilk vakayı açıklayarak pandemi sürecini resmen başlattı."),
            ("Koronavirüs Bilim Kurulu'nun Oluşturulması ve Günlük Tablo", "Uzman tıp hocalarından oluşan kurul her gün toplanarak vaka ve ölüm sayılarını canlı yayınla duyurdu."),
            ("65 Yaş ve Üstü Vatandaşlara Sokağa Çıkma Kısıtlaması", "Risk grubundaki yaşlıların korunması için başlatılan yasakta ihtiyaçları Vefa Destek Grupları karşıladı."),
            ("Hafta Sonu ve Bayram Sokağa Çıkma Yasakları", "Büyükşehirlerde ilan edilen tam kapanma kararlarıyla cadde ve meydanlar sessizliğe büründü."),
            ("HES (Hayat Eve Sığar) Kodu Zorunluluğu", "Toplu taşıma, AVM ve kamu binalarına girişlerde temaslı takibi yapan karekod zorunlu kılındı."),
            ("Ücretsiz Cerrahi Maske Dağıtımı Krizleri", "PTT Kargo ve eczaneler üzerinden yapılan ücretsiz maske dağıtımı sonrası tavan fiyatlı satışa geçildi."),
            ("CoronaVac (Sinovac) ve BioNTech Aşı Kampanyaları", "Türkiye 150 milyon doz aşı uygulayarak nüfusun büyük kısmını kısa sürede aşıladı."),
            ("Yerli COVID-19 Aşısı TURKOVAC'ın Geliştirilmesi", "Erciyes Üniversitesi'nde geliştirilen yerli inaktif aşı Faz-3 testlerini geçerek acil kullanım onayı aldı."),
            ("Pandemi Dönemi Kısa Çalışma Ödeneği ve İşten Çıkarma Yasağı", "Ekonomik çöküşü önlemek için yüz milyarlarca liralık sosyal koruma kalkanı devreye sokuldu."),
            ("Sağlıkta Şiddet Yasası ve Hekime Saldıranların Tutuklanması", "Hastanelerde doktor ve hemşirelere saldıranlara yönelik cezalar artırılarak tutuklama zorunlu kılındı."),
            ("'Beyaz Kod' Sistemi ve Hastanelere X-Ray Cihazı Kurulması", "Sağlık personeline fiziki saldırı anında güvenlik güçlerini çağıran acil alarm butonu kuruldu."),
            ("Hekimlerin Kamudan Özel Sektöre ve Yurt Dışına Göçü", "Ağır nöbet şartları ve maaş yetersizliği nedeniyle doktorların istifaları 'Giderlerse gitsinler' polemiği yarattı."),
            ("Beyaz Reform Paketi ve Hekim Maaşlarında İyileştirme", "Döner sermaye yerine taban ek ödeme getirilerek kamu hekimlerinin gelirleri iki katına çıkarıldı."),
            ("Özel Hastaneler Yönetmeliği ve Muayenehane Sözleşme Sınırı", "Muayenehane doktorlarının özel hastanelerde ameliyat yapmasına getirilen kota hekimleri sokağa döktü."),
            ("SMA Hastası Çocuklar ve Zolgensma Gen Tedavisi Kampanyaları", "Milyonlarca dolarlık gen tedavisi için sosyal medyada toplanan bağışlar ve SGK kapsamı tartışıldı."),
            ("Sahte İçki (Metil Alkol) Zehirlenmeleri ve Körlük Vakaları", "Yüksek ÖTV nedeniyle merdiven altı sahte içki üreten şebekelerin yüzlerce vatandaşın ölümüne yol açması önlendi."),
            ("SGK Sahte Reçete ve Medikal Yolsuzluk Teftişleri", "Yazılmayan pahalı kanser ilaçlarını devlete fatura eden organize şebekeler mali polisçe çökertildi.")
        ]
    },
    {
        "id": 20,
        "name": "Spor Zaferleri, Olimpiyatlar, Şike ve Stadyum Krizleri",
        "source": "Gençlik ve Spor Bakanlığı & TFF",
        "char1": "char_cumhurbaskani",
        "char2": "char_icisleri_bakani",
        "kw": "Spor ve Tribün Asayişi",
        "cases": [
            ("17 Mayıs 2000: Galatasaray'ın UEFA Kupasını Kazanması", "Kopenhag'da Arsenal'i penaltılarla 4-1 mağlup eden Galatasaray Türk futbol tarihinin ilk Avrupa kupasını kaldırdı."),
            ("25 Ağustos 2000: Galatasaray'ın UEFA Süper Kupa Şampiyonluğu", "Monako'da Real Madrid'i Jardel'in altın golüyle 2-1 deviren sarı-kırmızılılar Süper Kupa'yı Türkiye'ye getirdi."),
            ("2002 FIFA Dünya Kupası: A Milli Takımın Dünya Üçüncülüğü", "Şenol Güneş yönetimindeki Milliler Güney Kore'yi yenerek bronz madalya kazandı; tüm ülke sokaklara taştı."),
            ("Hakan Şükür'ün Güney Kore'ye 11. Saniyede Attığı Tarihi Gol", "Dünya Kupası tarihinin en hızlı golü olarak rekorlar kitabına geçen gol dünya basınında manşet oldu."),
            ("Sertab Erener'in 'Everyway That I Can' ile Eurovision Zaferi (2003)", "Riga'da düzenlenen 48. Eurovision Şarkı Yarışması'nda Türkiye ilk ve tek birinciliğini elde etti."),
            ("Euro 2008 Futbol Şampiyonası Yarı Final Mucizesi", "İsviçre, Çekya ve Hırvatistan maçlarındaki son saniye geri dönüşleriyle Fatih Terim'in ekibi yarı finale çıktı."),
            ("3 Temmuz 2011 Şike Soruşturması ve Kulüp Başkanları", "Fenerbahçe Başkanı Aziz Yıldırım ve yöneticilerin şafak operasyonuyla tutuklanması Türk futbolunu sarstı."),
            ("UEFA'nın Türk Takımlarına Şampiyonlar Ligi Men Cezaları", "Şike soruşturması gerekçesiyle Fenerbahçe ve Beşiktaş Avrupa kupalarından men edildi; yıllarca hukuk savaşı verildi."),
            ("Yargıtay Beraat Kararları ve Kumpasın Tescillenmesi", "Yıllar süren yargılama sonunda şike davasının kumpas olduğu tescillendi ve tüm sanıklar beraat etti."),
            ("Passolig Elektronik Bilet Sistemine Geçiş ve Tribün Boykotu", "6222 sayılı sporda şiddet yasasıyla gelen e-bilet sistemi taraftar gruplarınca tribünleri boşaltarak protesto edildi."),
            ("A Milli Kadın Voleybol Takımı (Filenin Sultanları) Avrupa Şampiyonu", "Brüksel'de Sırbistan'ı 3-2 yenen Filenin Sultanları 2023 CEV Avrupa Şampiyonu ve VNL şampiyonu oldu."),
            ("Melissa Vargas ve Ebrar Karakurt'un Küresel Başarısı", "Vargas turnuvanın en değerli oyuncusu (MVP) seçilirken milli voleybolcular dünya sıralamasında 1 numaraya oturdu."),
            ("Mete Gazoz'un Tokyo 2020 Olimpiyat Şampiyonluğu", "Klasik yay okçulukta altın madalya kazanan Mete Gazoz ardından 2023'te Dünya Şampiyonu oldu."),
            ("Yusuf Dikeç'in Paris 2024 Olimpiyatlarındaki Ekipmansız Duruşu", "Kulaklıksız, özel gözlüksüz ve cebinde eliyle gümüş madalya kazanan milli atıcı tüm dünyada viral mem oldu."),
            ("Naim Süleymanoğlu'nun Atlanta 1996'da 3. Olimpiyat Altını", "Cep Herkülü üst üste üçüncü kez olimpiyat şampiyonu olarak dünya spor tarihine adını altın harflerle yazdırdı."),
            ("Halil Mutlu'nun Sydney 2000 ve Atina 2004 Olimpiyat Altınları", "Halterde rekorları altüst eden Dinamo Halil üst üste olimpiyat altın madalyalarıyla gururumuz oldu."),
            ("Rıza Kayaalp ve Taha Akgül'ün Güreşte Rekor Şampiyonlukları", "Grekoromen ve serbest stilde onlarca Avrupa ve Dünya şampiyonluğu kazanan güreşçiler olimpiyat madalyaları aldı."),
            ("Servet Tazegül'ün Londra 2012 Tekvando Olimpiyat Altını", "Akrobatik tekmeleriyle tekvando dünyasında efsaneleşen sporcu olimpiyat kürsüsünün zirvesine çıktı."),
            ("Busenaz Sürmeneli ve Buse Naz Çakıroğlu'nun Boks Zaferleri", "Tokyo'da olimpiyat şampiyonu olan boksör kadınlarımız Türk sporunda tarihi bir çığır açtı."),
            ("Ampute Futbol Milli Takımı'nın 2022 Dünya Şampiyonluğu", "İstanbul'da Angola'yı yenerek Dünya Kupası'nı kaldıran milli takım azmin ve inancın sembolü oldu."),
            ("Anadolu Efes ve Fenerbahçe Beko'nun Basketbol EuroLeague Zaferleri", "Ergin Ataman ve Zeljko Obradovic yönetiminde Türk takımları Avrupa'nın en büyük basketbol kupasını kazandı."),
            ("Trabzonspor'un 2021-2022 Sezonunda 38 Yıl Sonra Şampiyonluğu", "Karadeniz fırtınasının şampiyonluk kutlamaları Yenikapı ve Trabzon meydanlarında görsel şölene dönüştü."),
            ("Ankaragücü Başkanı Faruk Koca'nın Hakem Meler'e Yumruğu", "Çaykur Rizespor maçı bitiminde sahaya inip hakem Halil Umut Meler'e yumruk atan başkan tutuklandı."),
            ("TFF'nin Ligleri Süresiz Tatil Etmesi ve Ömür Boyu Men Cezası", "Hakeme yönelik saldırı sonrası tüm futbol ligleri durduruldu; kulüp başkanına futboldan ömür boyu men verildi."),
            ("2023 Süper Kupa Suudi Arabistan Riyad Krizi", "Fenerbahçe ve Galatasaray'ın Atatürk tişörtü ve pankartına izin verilmemesi üzerine sahaya çıkmayıp dönmesi milli gurur oldu."),
            ("Şanlıurfa'da Oynanan Ertelenmiş Süper Kupa Maçı", "Fenerbahçe'nin TFF'yi protesto için U19 takımıyla çıkıp 2. dakikada sahadan çekilmesiyle kupa Galatasaray'a tescillendi."),
            ("TFF Başkanlık Seçimleri ve Kulüpler Birliği Çatışması", "Hakem atamaları ve yabancı kuralı krizleri sebebiyle TFF genel kurulları büyük kulis savaşlarına sahne oldu."),
            ("Futbolda Yabancı Oyuncu Kuralı Değişiklikleri Tartışması", "Kulüplerin talebiyle sahada 8+3 kuralından sınırsız yabancı tescili modellerine geçişler denendi."),
            ("İstanbul Park Formula 1 Türkiye Grand Prix'si Yarışları", "Tuzla'daki pistte yapılan nefes kesen F1 yarışları motor sporları tutkunlarını Türkiye'ye çekti."),
            ("Kırkpınar Yağlı Güreşleri'nde Altın Kemer Mücadeleleri", "Tarihi Sarayiçi er meydanında başpehlivanlık kemeri için kıran kırana geçen güreşler lig usulüne bağlandı.")
        ]
    }
]

print("DOMAINS_11_TO_20 loaded successfully.")
