# -*- coding: utf-8 -*-
"""
Data for Domains 1 to 10 (300 cases: 101 to 400)
"""

DOMAINS_1_TO_10 = [
    {
        "id": 1,
        "name": "1990'lar Koalisyonlar ve Siyasi Krizler (1995-2002)",
        "source": "Başbakanlık & TBMM",
        "char1": "char_basbakan",
        "char2": "char_milletvekili",
        "kw": "Siyasi Kriz ve Koalisyon",
        "cases": [
            ("Refahyol Hükümeti Protokolü ve Güvenoyu Çalkantısı", "54. Hükümetin güvenoyu sürecinde transfer iddiaları ve meclis gerilimi patlak verdi."),
            ("Aydınlık İçin Bir Dakika Karanlık Eylemleri", "Susurluk sonrası her akşam 21:00'de evlerde ışıkların kapatılmasıyla temiz toplum talep edildi."),
            ("28 Şubat 1997 MGK Bildirisi ve 18 Maddelik Talimat Listesi", "9 saat süren tarihi MGK toplantısında askeri kanat, hükümete 18 maddelik tedbir paketini sundu."),
            ("Batı Çalışma Grubu (BÇG) Fişleme Belgeleri", "Deniz Kuvvetleri bünyesindeki BÇG'nin kamu görevlilerini fişlediği belgelerin sızması ortalığı karıştırdı."),
            ("Sincan'da Kudüs Gecesi ve Tankların Yürütülmesi", "Sincan Belediyesi'nin etkinliği sonrası zırhlı birlik tanklarının caddelerden geçmesi tansiyonu fırlattı."),
            ("Fazilet Partisi'nin Kurulması ve Kapatılması Davası", "Refah Partisi'nin ardından kurulan Fazilet Partisi hakkında odak olma gerekçesiyle kapatma davası açıldı."),
            ("18 Nisan 1999 Seçimleri ve 57. Hükümet Protokolü", "DSP, MHP ve ANAP koalisyonu kurulurken bakanlık paylaşımları ve Meclis Başkanlığı pazarlığı kızıştı."),
            ("Merve Kavakçı'nın TBMM Yemin Töreni Gerilimi", "Başörtüsüyle genel kurula gelen milletvekiline yönelik protestolar meclis çalışmalarını kilitledi."),
            ("Çankaya Köşkü'nde Anayasa Kitapçığı Fırlatılması (Şubat 2001)", "MGK toplantısında Cumhurbaşkanı ile Başbakan arasındaki kavga sonrası gecelik faizler %7500'e fırladı."),
            ("Abdullah Öcalan'ın Kenya'da Yakalanması ve Getirilişi", "Nairobi'deki operasyonla terör elebaşı Türkiye'ye getirildi; ülke genelinde tarihi bir coşku yaşandı."),
            ("İmralı Duruşmaları ve Ağırlaştırılmış Müebbet Kararı", "İmralı Adası'nda kurulan özel mahkemede terör elebaşı yargılanarak idam cezasına çarptırıldı."),
            ("1999 Topluma Kazandırma Kanunu (Pişmanlık Yasası)", "Örgütten kopmaları hızlandırmak amacıyla hazırlanan Pişmanlık Yasası mecliste hararetli tartışmalara yol açtı."),
            ("Şartlı Salıverme Yasası (Rahşan Affı) ve Cezaevi Tahliyeleri", "Cezaevlerindeki doluluğu azaltmak amacıyla çıkarılan af sonrası binlerce adli mahkum tahliye oldu."),
            ("Hayata Dönüş Operasyonu ve F Tipi Cezaevleri", "20 cezaevindeki ölüm oruçlarını kırmak ve oda sistemine geçmek amacıyla düzenlenen operasyonda çatışmalar çıktı."),
            ("Manisa Davası ve Polis İşkencesi İddiaları", "Manisa'da gözaltına alınan 16 liseli gence işkence yapıldığı iddiası Türkiye gündemine oturdu."),
            ("Metin Göktepe Davası ve Gazeteci Cinayeti Yargılaması", "Gözaltında darp edilerek öldürülen gazetecinin davası, kamuoyu baskısıyla ilden ile nakledildi."),
            ("3 Kasım 2002 Erken Genel Seçimleri ve Siyasetin Tasfiyesi", "Ekonomik kriz sonrası gidilen erken seçimde merkez sağ ve solun köklü partileri baraj altında kaldı."),
            ("Recep Tayyip Erdoğan'ın Siirt Seçimi ile Başbakanlığı", "Siyasi yasağı anayasa değişikliğiyle kalkan AK Parti lideri Siirt yenileme seçimiyle meclise girip hükümeti kurdu."),
            ("1 Mart 2003 Tezkeresi ve TBMM Tarihi Ret Kararı", "ABD birliklerinin Türkiye üzerinden Irak'a girmesine izin veren tezkere TBMM'de salt çoğunluğu sağlayamadı."),
            ("Süleymaniye'de Çuval Olayı (4 Temmuz 2003)", "Irak Süleymaniye'de Türk Özel Kuvvetleri karargahını basan ABD askerleri subaylarımızın başına çuval geçirdi."),
            ("Kıbrıs Annan Planı Referandumu (2004)", "BM'nin Kıbrıs planı Türk tarafından %65 'Evet', Rum tarafından %75 'Hayır' oyu aldı."),
            ("AB Uyum Yasaları ve DGM'lerin Kaldırılması (2004)", "AB katılım müzakereleri çerçevesinde 8 uyum paketiyle Devlet Güvenlik Mahkemeleri tarihe karıştı."),
            ("İdam Cezasının Tamamen Kaldırılması (2002-2004)", "AİHS protokolleri uyarınca barış ve savaş zamanında ölüm cezası anayasa ve yasalardan tamamen çıkarıldı."),
            ("Farklı Dil ve Lehçelerde Yayın İzni (TRT 6 ve Özel Radyolar)", "AB uyum yasalarıyla geleneksel olarak kullanılan yerel dillerde yayın hakkı yasal güvenceye kavuştu."),
            ("Gayrimüslim Cemaat Vakıfları Mülk İadesi Yasası", "1936 Beyannamesi sonrası azınlık vakıflarının elinden çıkan taşınmazların iadesi yasalaştı."),
            ("Yeni Türk Ceza Kanunu (TCK 5237) Reformu (2004-2005)", "79 yıllık eski ceza kanunu yerine kişi hak ve hürriyetlerini merkeze alan çağdaş ceza kanunu kabul edildi."),
            ("Yeni Ceza Muhakemesi Kanunu (CMK 5271) ve Çapraz Sorgu", "Savunma hakkını güçlendiren ve delilden sanığa gitmeyi şart koşan modern CMK sistemi yürürlüğe girdi."),
            ("Kabahatler Kanunu (5326) ve İdari Para Cezaları", "Adliyeleri boğan küçük suçların mahkemeler yerine idari yaptırımlara bağlanmasıyla yargı rahatlatıldı."),
            ("Bilgi Edinme Hakkı Kanunu (4982) ile Şeffaflık Çağı", "Vatandaşların kamu kurumlarındaki her türlü idari işlem ve belgeye erişimini sağlayan yasa kabul edildi."),
            ("Kamu İhale Kurumu (KİK) ve 4734 Sayılı İhale Devrimi", "Devlet ihalelerindeki yolsuzlukları önlemek amacıyla özerk Kamu İhale Kurumu kurularak EKAP'a geçildi.")
        ]
    },
    {
        "id": 2,
        "name": "Bankacılık Krizleri, Hortumlama ve TMSF Operasyonları (1998-2006)",
        "source": "BDDK & TMSF",
        "char1": "char_hazine_bakani",
        "char2": "char_merkez_bankasi_baskani",
        "kw": "Bankacılık ve Mali Denetim",
        "cases": [
            ("Demirbank Fonlama Krizi ve Hazine Müdahalesi", "Kasım 2000'de gecelik faizlerin fırlamasıyla bono portföyünü fonlayamayan Demirbank'ın batışı piyasayı kilitledi."),
            ("İmar Bankası Çifte Kayıt Skandalı ve Uzan Grubu Tasfiyesi", "İmar Bankası'nda resmi kayıtların arkasında milyarlarca dolarlık kayıtdışı mevduat tutulduğu belgelendi."),
            ("Türkbank İhalesi ve Çakıcı Kasetleri Skandalı", "Özelleştirme ihalesine yeraltı dünyasının müdahale ettiğini gösteren kasetler hükümeti istifaya sürükledi."),
            ("Bank Ekspres ve Korkmaz Yiğit Soruşturması", "Bankanın içinin haksız kredi aktarımlarıyla boşaltıldığı gerekçesiyle DGM'de tutuklamalar yapıldı."),
            ("Yurtbank Tasfiyesi ve Ali Balkaner Dosyası", "Yurtbank'ın içi boşaltılarak off-shore hesaplar üzerinden paraların buharlaştırılması mudileri isyan ettirdi."),
            ("Egebank ve 'Kasırga Operasyonu'", "Gece yarısı operasyonuyla Egebank kasalarının boşaltıldığı ve evrakların kaçırıldığı tespit edildi."),
            ("Pamukbank'ın Fona Devri ve Çukurova Grubu Borçları", "Sermaye yeterliliği eksiye düşen Pamukbank'a el konulması Turkcell ve Yapı Kredi hisselerinde krize yol açtı."),
            ("Bankacılık Düzenleme ve Denetleme Kurumu'nun (BDDK) Kurulması", "Bankaların siyasetçilerin emrinden çıkarılıp bağımsız bir kurulla denetlenmesi amacıyla BDDK kuruldu."),
            ("Kemal Derviş Reformları: 15 Günde 15 Kanun Paketi", "Dünya Bankası'ndan çağrılan Derviş'in programı kapsamında meclis gece gündüz çalışarak 15 reformu kabul etti."),
            ("Merkez Bankası Kanunu Reformu ve Fiyat İstikrarı", "Nisan 2001 kanunuyla TCMB'ye Hazine'ye avans verme yasağı getirildi ve temel amaç fiyat istikrarı oldu."),
            ("Kamu İhale Kanunu (4734) ve AB Standartlarına Uyum", "Kamudaki ihale usulsüzlüklerini bitirmek amacıyla hazırlanan kanun ihale süreçlerini şeffaflaştırdı."),
            ("Kamu Mali Yönetimi ve Kontrol Kanunu (5018)", "Devlet harcamalarında performans esaslı bütçelemeyi ve Sayıştay denetimini getiren temel kanun kabul edildi."),
            ("TMSF'ye Devredilen 20 Özel Bankanın Tasfiyesi", "Batan 20 özel bankanın borçlarını temizlemek ve varlıklarını satmak amacıyla TMSF dev bir holdinge dönüştü."),
            ("Banka Batıklarının Hazineye Maliyeti ve Özel Tertip Tahviller", "Batan bankaların 40 milyar doları aşan maliyetini üstlenen Hazine devasa kamu borcu altına girdi."),
            ("Off-Shore Hesapzedelere Devlet Garantisi Tartışması", "Yurt dışındaki paravan bankalara yüksek faizle para yatıranların devlet güvencesi talep etmesi kriz yarattı."),
            ("Beyaz Enerji Operasyonu: TEAŞ ve TEDAŞ İhaleleri", "Enerji santralleri ve iletim hatları ihalelerinde rüşvet çarkı kurulduğu iddiasıyla DGM operasyonu başlatıldı."),
            ("Mavi Hat Operasyonu: BOTAŞ Doğalgaz Rüşvet İddiaları", "Doğalgaz boru hatları ve kompresör istasyonu ihalelerinde rüşvet alındığı iddiasıyla bürokratlar tutuklandı."),
            ("Balina Operasyonu: İzmir Gümrüklerinde Hayali İhracat", "İzmir gümrüklerinden kum ve taş yüklü konteynerlerle trilyonluk KDV iadesi alan şebeke çökertildi."),
            ("Paraşüt Operasyonu: Sahte Fatura ve Naylon İhracat", "Gaziantep ve İstanbul üçgeninde yüzlerce tabela şirketi üzerinden trilyonluk naylon fatura kesildiği belirlendi."),
            ("Örümcek Ağı Operasyonu: Naylon Fatura Baronları", "Devleti hayali ihracatla soyan uluslararası şebekeye yönelik cumhuriyet tarihinin en büyük mali baskını yapıldı."),
            ("Vurgun Operasyonu: Bayındırlık Bakanlığı İhale Şebekesi", "Deprem konutları ihalelerinde bürokratlar ile müteahhitler arasında rüşvet ağı kurulduğu deşifre edildi."),
            ("Bumerang Operasyonu: Hazine Teşviklerinin Suistimali", "Fabrika kurma taahhüdüyle alınan yatırım teşviklerini faizde ve borsada değerlendiren şirketler yakalandı."),
            ("Kentbank ve Sümerbank Tasfiye Süreçleri", "Fona devredilen tarihi bankaların borçlarının tahsili için uzun soluklu haciz ve dava süreçleri işletildi."),
            ("İktisat Bankası ve Erol Aksoy Borç Protokolü", "Krizde batan İktisat Bankası'nın hakim ortağının televizyon kanalları ve gayrimenkulleri TMSF tarafından satıldı."),
            ("Yaşarbank ve DYO Grubu Borç Yapılandırması", "İzmirli sanayi devinin bankası batınca üretim tesislerini korumak için 10 yıllık kurtarma protokolü yapıldı."),
            ("Toprakbank ve Halis Toprak Gayrimenkul Satışları", "Toprakbank'ın borçları karşılığında Boğaz'daki Aslanlı Köşk ve fabrikalar açık artırmayla satışa çıkarıldı."),
            ("Gelir İdaresi Başkanlığı'nın (GİB) Yeniden Yapılanması (2005)", "Maliye Bakanlığı Gelirler Genel Müdürlüğü lağvedilerek yarı-özerk ve modern Gelir İdaresi Başkanlığı kuruldu."),
            ("Vergi Barışı Kanunları ve Varlık Barışı Uygulamaları", "Kayıtdışı sermayeyi sisteme çekmek ve yargıdaki milyonlarca vergi davasını temizlemek için aflar çıkarıldı."),
            ("KEY (Konut Edindirme Yardımı) Hak Sahiplerine İadesi", "Yıllarca çalışanların maaşlarından kesilen KEY paraları 8.5 milyon hak sahibine nakit olarak ödendi."),
            ("Zorunlu Tasarruf Fonu (NEMA) Kesintilerinin Tasfiyesi", "1988'den beri maaşlardan kesilen zorunlu tasarruf fonu lağvedilerek nemalar çalışanlara iade edildi.")
        ]
    },
    {
        "id": 3,
        "name": "2002-2007 Erken Seçimler, 1 Mart, Annan Planı, AB Uyum",
        "source": "TBMM & Dışişleri",
        "char1": "char_basbakan",
        "char2": "char_diplomat",
        "kw": "Dış Politika ve Uyum",
        "cases": [
            ("Türkiye-AB Katılım Müzakerelerinin Başlaması (3 Ekim 2005)", "Lüksemburg'da sabaha kadar süren pazarlıklar sonrası Türkiye AB ile tam üyelik müzakerelerine resmen başladı."),
            ("Müzakere Çerçeve Belgesi ve 'Açık Uçlu' Tartışması", "AB belgesinde tam üyelik garantisi yerine açık uçlu süreç ifadesinin yer alması diplomasiyi gerdi."),
            ("Kıbrıs Ek Protokolü ve Limanların Açılması Baskısı", "AB'nin Türkiye'den liman ve havaalanlarını Güney Kıbrıs Rum yönetimine açmasını şart koşması kriz yarattı."),
            ("Türk Ceza Kanunu Zina Maddesi Tartışması (2004)", "Yeni TCK hazırlanırken zina suçunun kanuna eklenmesi girişimi Brüksel ile Ankara arasında tansiyonu yükseltti."),
            ("Kopenhag Siyasi Kriterleri Uyum Raporları", "Avrupa Komisyonu'nun Türkiye İlerleme Raporlarında temel haklar ve yargı bağımsızlığı eleştirileri öne çıktı."),
            ("Devlet Planlama Teşkilatı ve AB Bölgesel Kalkınma Ajansları", "81 ilde yerel kalkınmayı finanse etmek amacıyla 26 Kalkınma Ajansı kurularak AB fonları aktarıldı."),
            ("Kamu Denetçiliği Kurumu (Ombudsman) Tasarısı Tartışması", "Vatandaşın idareyle uyuşmazlığını mahkemesiz çözecek ombudsmanlık tasarısı veto ve onay turlarına takıldı."),
            ("Ankara Düşünce Özgürlüğü ve TCK 301. Madde Davaları", "'Türklüğü aşağılama' suçunu düzenleyen 301. madde kapsamında yazarlar ve aydınlar hakkında davalar açıldı."),
            ("Orhan Pamuk Hakkında Açılan TCK 301 Davası ve Düşürülmesi", "Nobel ödüllü yazarın demeçleri sebebiyle açılan dava uluslararası tepkiler üzerine Adalet Bakanlığı izniyle düştü."),
            ("Hrant Dink Hakkındaki TCK 301 Mahkumiyeti ve Tehditler", "Agos Gazetesi Genel Yayın Yönetmeni'nin yargılandığı dava ve ardından başlayan linç kampanyası gerilimi tırmandırdı."),
            ("Vakıflar Kanunu Veto Krizi ve Çankaya Köşkü", "Cumhurbaşkanı Sezer'in cemaat vakıflarına mülk edinme hakkı tanıyan kanunu veto etmesi meclisi kilitledi."),
            ("Dernekler Kanunu Reformu ve Sivil Toplumun Güçlenmesi", "Eski dernekler masası kaldırılarak derneklerin yurtdışından fon almasını kolaylaştıran modern yasa kabul edildi."),
            ("Gümrüklerde Modernizasyon ve Kaçakçılıkla Mücadele Kanunu", "Sınır kapılarındaki işlemlerin hızlandırılması ve kaçakçılık cezalarının artırılması için yasa yenilendi."),
            ("Tohumculuk Kanunu ve Islah Edilmiş Yerli Tohum Standartları", "Tarımda sertifikalı tohum kullanımını zorunlu kılan yasa köylüler ve ziraat odalarınca tartışıldı."),
            ("Sosyal Güvenlik Reformu İlk Taslağı ve Emeklilik Yaşı", "SSK, Bağ-Kur ve Emekli Sandığı'nı tek çatı altında birleştiren ilk reform taslağı sendikaları ayağa kaldırdı."),
            ("Genel Sağlık Sigortası (GSS) Yasasının İlk Kabülü", "Tüm vatandaşların sağlık güvencesine alınmasını öngören tarihi kanun meclisten geçirildi."),
            ("Özel Öğretim Kurumları Kanunu ve Yabancı Okullar Tartışması", "Azınlık ve yabancı okulların taşınmaz edinimi ve şube açma şartları meclis kulislerini hareketlendirdi."),
            ("Radyo ve Televizyon Üst Kurulu (RTÜK) Yayın İlkeleri Reformu", "Yayın lisansları ve ceza sistemini AB görsel-işitsel direktiflerine uyumlu hale getiren yasa onaylandı."),
            ("Çevre Kanunu Değişikliği ve Kirleten Öder İlkesi", "Sanayi tesislerine arıtma tesisi zorunluluğu ve ağır çevre kirliliği para cezaları getirildi."),
            ("Tüketici Mahkemeleri ve Hakem Heyetlerinin Yaygınlaştırılması", "Tüketici uyuşmazlıklarında hakem heyetlerinin yetki sınırları artırılarak yargı yükü azaltıldı."),
            ("Bankacılık Kanunu (5411) ile BDDK Yetkilerinin Tahkimi", "2001 krizinden çıkarılan derslerle hazırlanan kapsamlı yeni bankacılık yasası kabul edildi."),
            ("Sermaye Piyasası Kanunu Manipülasyon Cezaları", "Borsada yapay fiyat oluşturan spekülatörlere yönelik hapis cezaları ve işlem yasakları ağırlaştırıldı."),
            ("Kişisel Verilerin Korunması İlk Taslağı ve Çankaya Görüşmeleri", "Vatandaşların kişisel verilerinin korunmasını anayasal teminata bağlayacak ilk taslak hazırlandı."),
            ("Elektronik İmza Kanunu (5070) ve Dijital Dönüşüm", "Islak imza ile aynı hukuki geçerliliğe sahip e-imza yasası kamu ve özel sektörde devrim başlattı."),
            ("Milli Seferberlik ve Asker Alma Kanunu Değişiklikleri", "Zorunlu askerlik sürelerinin kademeli olarak düşürülmesi TSK ve hükümet arasında müzakere edildi."),
            ("Askeri Ceza Kanunu Uyum Düzenlemeleri", "Sivil mahkemelerin yetki alanına giren suçlarda asker kişilerin yargılanma usulleri netleştirildi."),
            ("Maden Kanunu (5177) ve Yabancı Yatırımcılara Maden İzni", "Maden arama ruhsatlarının kolaylaştırılması çevre dernekleri ile madencileri karşı karşıya getirdi."),
            ("Kıyı Kanunu İhlalleri ve Kaçak İskelelerin Yıkılması", "Ege ve Akdeniz kıyılarında kamuya ait sahillere kurulan kaçak iskeleler dozerlerle yıkıldı."),
            ("Organize Sanayi Bölgeleri (OSB) Teşvik Kanunu", "Anadolu kaplanları olarak anılan sanayi şehirlerine bedelsiz arsa ve vergi teşviki sağlandı."),
            ("Doğrudan Yabancı Yatırımlar Kanunu (4875) ile Yatırım Patlaması", "Yabancı sermayeye yerli yatırımcıyla eşit muamele tanıyan kanun sonrası ülkeye rekor döviz girişi oldu.")
        ]
    },
    {
        "id": 4,
        "name": "2007-2010 367 Krizi, E-Muhtıra, Başörtüsü, Kapatma Davası",
        "source": "Anayasa Mahkemesi & TBMM",
        "char1": "char_anayasa_mahkemesi_baskani",
        "char2": "char_tbmm_baskani",
        "kw": "Anayasa ve Yargı Krizi",
        "cases": [
            ("Sabih Kanadoğlu'nun 367 Nisap Tezi", "Eski Yargıtay Başsavcısı cumhurbaşkanlığı seçimi için genel kurulda en az 367 vekilin bulunması gerektiğini savundu."),
            ("TBMM'de 1. Tur Cumhurbaşkanlığı Seçimi ve Oylama", "Abdullah Gül 357 oy alırken CHP toplantı yeter sayısı bulunmadığı gerekçesiyle Anayasa Mahkemesi'ne başvurdu."),
            ("Anayasa Mahkemesi'nin 367 Kararı ve Meclisin Kilitlenmesi", "AYM ilk tur oylamayı iptal ederek cumhurbaşkanlığı seçimini imkansız kıldı; erken seçim kararı alındı."),
            ("27 Nisan 2007 Gece Yarısı Genelkurmay E-Muhtırası", "Genelkurmay Başkanlığı internet sitesinde cumhurbaşkanlığı seçimi ve laiklik konusunda sert bir bildiri yayınladı."),
            ("Hükümetin E-Muhtıraya Karşı Tarihi Dik Duruş Yanıtı", "Hükümet sözcüsü Genelkurmay'ın Başbakanlığa bağlı bir kurum olduğunu vurgulayarak muhtırayı reddetti."),
            ("Cumhuriyet Mitingleri (Tandoğan, Çağlayan, Gündoğdu)", "Milyonlarca vatandaş meydanlara inerek 'Cumhuriyete Sahip Çık' sloganlarıyla gösteriler düzenledi."),
            ("22 Temmuz 2007 Erken Genel Seçimleri", "Siyasi krizin ardından gidilen seçimde iktidar partisi %46.6 oy alarak tek başına iktidarını perçinledi."),
            ("Abdullah Gül'ün 11. Cumhurbaşkanı Olarak Seçilmesi", "MHP'nin genel kurula girerek 367 krizini çözmesiyle Abdullah Gül Çankaya Köşkü'ne çıktı."),
            ("2007 Anayasa Referandumu: Cumhurbaşkanını Halkın Seçmesi", "Cumhurbaşkanının 5+5 sistemiyle doğrudan halk tarafından seçilmesini öngören değişiklik %68 oyla kabul edildi."),
            ("Üniversitelerde Başörtüsü Serbestliği Anayasa Değişikliği (2008)", "AK Parti ve MHP'nin 411 oyla kabul ettiği Anayasa'nın 10 ve 42. madde değişiklikleri üniversite kapılarını açtı."),
            ("411 El Kaosa Kalktı Manşeti ve Medya Gerilimi", "Anayasa değişikliği sonrası atılan gazete manşetleri siyaset ve medya arasında sert polemik başlattı."),
            ("Anayasa Mahkemesi'nin Başörtüsü Düzenlemesini İptali", "AYM teklif dahi edilemez maddelere aykırılık gerekçesiyle Meclis'in anayasa değişikliğini esastan iptal etti."),
            ("AK Parti'ye Yönelik 2008 Kapatma Davası İddianamesi", "Yargıtay Başsavcısı Abdurrahman Yalçınkaya iktidar partisinin 'laikliğe aykırı eylemlerin odağı' olduğu iddiasıyla dava açtı."),
            ("71 Siyasetçiye Siyasi Yasak Talebi Kriz", "Başbakan ve Cumhurbaşkanı dahil 71 üst düzey isme 5 yıl siyaset yasağı istenmesi piyasaları sarstı."),
            ("Anayasa Mahkemesi'nin Tarihi Kapatma Kararı (30 Temmuz 2008)", "AYM 6'ya 5 oyla partiyi kapatmadı; ancak Hazine yardımının yarısının kesilmesine karar verdi."),
            ("Şemdinli Umut Kitabevi Bombalanması Olayı", "Hakkari Şemdinli'de bir kitabevine el bombası atılması ve astsubayların suçüstü yakalanması ortalığı karıştırdı."),
            ("Savcı Ferhat Sarıkaya'nın Şemdinli İddianamesi", "Van Savcısı Kara Kuvvetleri Komutanı Yaşar Büyükanıt'ı suçlayınca HSYK tarafından meslekten ihraç edildi."),
            ("Danıştay 2. Dairesi Saldırısı ve Mustafa Yücel Özbilgin Cinayeti", "Avukat Alparslan Arslan Danıştay toplantı odasını basarak türban kararı veren üyeleri taradı; bir üye şehit oldu."),
            ("Danıştay Saldırısının Türban Kararıyla İlişkilendirilmesi", "Saldırının ardından düzenlenen cenaze töreninde hükümete karşı sert protestolar ve sloganlar yükseldi."),
            ("Hrant Dink Suikastı (19 Ocak 2007)", "Agos Gazetesi önünde Ogün Samast tarafından vurulan gazetecinin ölümü sonrası yüz binler 'Hepimiz Hrant'ız' dedi."),
            ("Dink Cinayetinde Kamu Görevlileri ve İstihbarat İhmali", "Cinayetin aylar öncesinden ihbar edilmesine rağmen Emniyet ve Jandarma istihbaratının harekete geçmediği belirlendi."),
            ("Malatya Zirve Yayınevi Katliamı", "İncil basımı yapan yayınevinde üç kişinin boğazı kesilerek öldürülmesi misyonerlik tartışmalarını alevlendirdi."),
            ("Ümraniye'de Gecekonduda Bulunan 27 El Bombası (Haziran 2007)", "Bir ihbar üzerine gecekonduda ele geçirilen mühimmat Ergenekon soruşturmasının fitilini ateşledi."),
            ("Ergenekon Dalgaları ve Emekli Komutanların Gözaltına Alınması", "Emekli orgeneraller Hurşit Tolon ve Şener Eruygur darbe teşebbüsü suçlamasıyla tutuklandı."),
            ("İlhan Selçuk ve Doğu Perinçek'in Gece Yarısı Gözaltıları", "Cumhuriyet Gazetesi Başyazarı ve parti liderinin sabaha karşı gözaltına alınması aydınları ayağa kaldırdı."),
            ("Balyoz Harekât Planı İddiaları ve Taraf Gazetesi Manşeti", "1. Ordu Komutanlığı'nda düzenlenen seminerde camilerin bombalanacağı ve darbe yapılacağı iddiaları manşet oldu."),
            ("Poyrazköy Kazıları ve Deniz Kuvvetleri Mühimmatları", "Beykoz Poyrazköy'de yapılan kazılarda yer altına gömülü lav silahları ve patlayıcılar ortaya çıkarıldı."),
            ("Kafes Eylem Planı ve Gayrimüslimlere Suikast İddiası", "Gayrimüslim azınlıklara yönelik bombalı eylem planlandığı iddia edilen belgeler yargıya taşındı."),
            ("Albay Dursun Çiçek ve Islak İmzalı Belge Tartışması", "'İrtica ile Mücadele Eylem Planı' belgesinin altındaki imzanın orijinal olup olmadığı adli tıpta incelendi."),
            ("Kozmik Oda Araması: Bülent Arınç'a Suikast İddiası", "Seferberlik Tetkik Kurulu'nun kozmik odalarında hakim Kadir Kayan tarafından haftalarca gizli arama yapıldı.")
        ]
    },
    {
        "id": 5,
        "name": "Ergenekon, Balyoz, Poyrazköy, Askeri Casusluk ve Kozmik Oda",
        "source": "Özel Yetkili Ağır Ceza Mahkemeleri",
        "char1": "char_adli_yargi_hakimi",
        "char2": "char_genelkurmay_baskani",
        "kw": "Kumpas ve Askeri Yargı",
        "cases": [
            ("Genelkurmay Eski Başkanı İlker Başbuğ'un Tutuklanması", "İnternet Andıcı davası kapsamında ifadeye çağrılan eski Genelkurmay Başkanı terör örgütü yöneticiliğinden tutuklandı."),
            ("Silivri Cezaevi Duruşma Salonları ve Dev Davalar", "Yüzlerce sanıklı Ergenekon ve Balyoz davaları için Silivri'de dev duruşma salonları ve kampüs inşa edildi."),
            ("Gölcük Donanma Komutanlığı Zeminindeki Gizli Belgeler", "Donanma İstihbarat Şubesi döşeme altından çıkarılan çuvallar dolusu dijital veri Balyoz davasına eklendi."),
            ("İzmir Askeri Casusluk Davası ve Bürokratların Fişlenmesi", "Yüzlerce subay ve bürokratın fuhuş ve şantaj çetesi marifetiyle askeri sırları sızdırdığı iddiasıyla dava açıldı."),
            ("İstanbul Askeri Casusluk ve Şantaj Davası", "Deniz Harp Okulu ve TÜBİTAK görevlilerinin askeri casusluk suçlamasıyla tutuklandığı süreç başladı."),
            ("TÜBİTAK Sahte Raporları ve Dijital Delil Manipülasyonları", "Balyoz belgelerindeki fontların 2007'de üretildiği ancak belgenin 2003 tarihli olduğu bilirkişilerce saptandı."),
            ("5 No'lu Harddisk Sahteciliği ve Adli Bilişim Çelişkileri", "Donanmadan çıkan harddiske sonradan dosya yüklendiği ve sistem saatinin manipüle edildiği ortaya çıktı."),
            ("Yarbay Ali Tatar'ın İntiharı ve Amirallere Suikast Dosyası", "Hakkında ikinci kez tutuklama kararı çıkarılan Deniz Yarbay Ali Tatar mektup bırakarak canına kıydı."),
            ("Kuddusi Okkır'ın Cezaevinde Kansere Yakalanıp Vefatı", "Ergenekon'un finansörü iddiasıyla tutuklanan iş adamı hastane sevki gecikince cezaevinde hayatını kaybetti."),
            ("Türkan Saylan'ın Evinde Arama ve ÇYDD Belgeleri", "Kanser tedavisi gören Çağdaş Yaşamı Destekleme Derneği Başkanı'nın evi sabaha karşı polislerce arandı."),
            ("Eskişehir'de Çıkan Flash Bellek ve İlhan Cihaner Davası", "Erzincan Cumhuriyet Başsavcısı makamında gözaltına alınarak Ergenekon sanığı yapıldı."),
            ("Gizli Tanık 'Efe' ve 'Deniz' Skandalları", "Davalarda kimliği gizlenen tanıkların çelişkili ve asılsız ifadeleriyle komutanların tutuklandığı belirlendi."),
            ("Zekeriya Öz'ün Zırhlı Aracı ve Soruşturma Yetkileri", "Özel Yetkili Cumhuriyet Savcısı'nın yetkileri ve Başbakanlıkça tahsis edilen zırhlı araç kamuoyunu böldü."),
            ("Fikret Seçkin ve Mehmet Murat Yönder'in İddianameleri", "Özel Yetkili Başsavcıvekilliği yüzlerce sayfalık dijital klasörlerle yeni dalgalar başlattı."),
            ("Hasdal Cezaevi'nin Muvazzaf Generallerle Dolması", "TSK'daki general ve amirallerin üçte birinin tutuklanması nedeniyle Hasdal Cezaevi karargaha dönüştü."),
            ("YAŞ Toplantılarında Tutuklu Askerlerin Terfi Krizi", "Yüksek Askeri Şura toplantılarında tutuklu subayların terfi ettirilip ettirilmeyeceği tartışıldı."),
            ("Genelkurmay Başkanı Işık Koşaner ve Kuvvet Komutanlarının İstifası (2011)", "Davalarda silah arkadaşlarının haklarının korunamadığını belirten komuta kademesi topluca emeklilik istedi."),
            ("Necdet Özel'in Genelkurmay Başkanlığına Atanması", "Komutanların istifası sonrası Jandarma Genel Komutanı derhal Genelkurmay Başkanı olarak atandı."),
            ("Ergenekon Davasında Karar: Yüzlerce Yıl Hapis ve Müebbet", "Silivri'deki mahkeme İlker Başbuğ, Doğu Perinçek ve komutanlara ağırlaştırılmış müebbet ve hapisler yağdırdı."),
            ("Balyoz Davası Kararları: 361 Sanığa Ağır Mahkumiyetler", "İstanbul 10. Ağır Ceza Mahkemesi Çetin Doğan ve komutanları darbe teşebbüsünden 20 yıl hapse mahkum etti."),
            ("Anayasa Mahkemesi'nin Balyoz Hak İhlali Kararı (2014)", "AYM dijital delillerin sıhhati ve tanık dinlenmemesi gerekçesiyle sanıkların adil yargılanmadığına hükmetti."),
            ("Silivri ve Hasdal Tahliyeleri ve Kumpasın Çöküşü", "AYM kararının ardından cezaevindeki yüzlerce subay ve general alkışlarla tahliye oldu."),
            ("Ergenekon Davasının Yargıtay'ca Bozulması ve Beraatler", "Yargıtay 16. Ceza Dairesi Ergenekon örgütünün varlığına dair somut delil bulunmadığını ilan etti."),
            ("Kumpas Savcı ve Hakimlerinin Yurt Dışına Firarı", "Soruşturmaları yürüten Zekeriya Öz, Celal Kara ve hakimler haklarında tutuklama çıkınca Gürcistan'a kaçtı."),
            ("TÜBİTAK Sahte Raporcu Bilirkişilerinin Tutuklanması", "Sahte dijital delillere onay veren bilirkişiler hakkında kumpas ve evrakta sahtecilikten davalar açıldı."),
            ("Askeri Casusluk Mağduru Subayların Hak İadeleri", "Beraat eden denizci subaylar görevlerine dönerek Mavi Vatan ve sınır ötesi operasyonlarda görev aldı."),
            ("Kumpas Şehitleri ve Mağdurlarına Devlet Tazminatları", "Haksız yere yıllarca hapis yatan subaylara ve vefat edenlerin ailelerine maddi-manevi tazminat ödendi."),
            ("Özel Yetkili Mahkemelerin (ÖYM) Görevine Son Verilmesi", "Hükümet CMK 250 ve TMK 10 ile yetkili mahkemeleri lağvederek dosyaları genel mahkemelere devretti."),
            ("Yargı Etiği ve Bilirkişilik Müessesesi Reformu", "Dijital delil incelemelerinde uluslararası akreditasyon ve bağımsız laboratuvar şartı getirildi."),
            ("Askeri Yargının Tamamen Kaldırılması Hazırlıkları", "Askeri Yargıtay ve Askeri Yüksek İdare Mahkemesi'nin sivil yargıyla birleştirilmesi süreci başladı.")
        ]
    },
    {
        "id": 6,
        "name": "2010 Referandumu, HSYK, 7 Şubat MİT Krizi, 17-25 Aralık",
        "source": "Adalet Bakanlığı & TBMM",
        "char1": "char_adalet_bakani",
        "char2": "char_adli_yargi_hakimi",
        "kw": "Yargı Mücadelesi ve Emniyet",
        "cases": [
            ("12 Eylül 2010 Anayasa Referandumu Paketi (26 Madde)", "Anayasa Mahkemesi ve HSYK'nın yapısını değiştiren, bireysel başvuru hakkı getiren paket %58 oyla kabul edildi."),
            ("Anayasa Mahkemesi'ne Bireysel Başvuru Hakkının Getirilmesi", "Vatandaşların AİHM'e gitmeden önce temel hak ihlallerini doğrudan AYM'ye taşıyabilmesi kabul edildi."),
            ("2010 HSYK Seçimleri ve Blok Liste Zaferi", "HSYK'nın yeni yapısında yapılan seçimlerde cemaat destekli blok listenin 10 asıl üyeliği kazanması sistemi kilitledi."),
            ("Yargıtay ve Danıştay Üye Sayılarının Artırılması Kanunu", "Yargıtay ve Danıştay'daki dosya yükünü eritmek gerekçesiyle yüzlerce yeni daire ve üye kadrosu açıldı."),
            ("7 Şubat 2012 MİT Krizi: Hakan Fidan'ın İfadeye Çağrılması", "Özel Yetkili Savcı Sadrettin Sarıkaya MİT Müsteşarı ve eski yöneticilerini KCK soruşturmasında ifadeye çağırdı."),
            ("MİT Müsteşarının Savcılığa Gitmemesi Talimatı", "Başbakan Erdoğan ameliyata girmeden önce Fidan'a kesinlikle ifade vermeye gitmemesi talimatını verdi."),
            ("MİT Kanunu'nda Gece Yarısı Değişikliği (17 Şubat 2012)", "MİT mensuplarının soruşturulması doğrudan Başbakan'ın iznine bağlanarak yargı darbesi girişimi önlendi."),
            ("Savcı Sadrettin Sarıkaya'nın Dosyadan El Çektirilmesi", "HSYK soruşturmayı yetkisiz ve habersiz yürüten savcıyı görevden alarak başka ile tayin etti."),
            ("Dershanelerin Kapatılması Tartışması ve İlk Çatlak (2013)", "Hükümetin özel dershaneleri kapatıp temel liseye dönüştürme planı cemaat ile iktidar arasındaki savaşı başlattı."),
            ("17 Aralık 2013 Sabahı Şafak Operasyonları", "Emniyet Mali ve Organize Şube ekipleri bakan çocukları, bürokratlar ve iş adamlarını eşzamanlı gözaltına aldı."),
            ("Bakan Çocuklarının Evlerindeki Kasalar ve Paralar", "Bakan çocuklarının yatak odalarındaki para kasaları ve Halkbank Genel Müdürü'nün evindeki kutular manşet oldu."),
            ("Dört Bakanın İstifası ve Kabine Revizyonu (25 Aralık 2013)", "Muammer Güler, Zafer Çağlayan, Egemen Bağış ve Erdoğan Bayraktar bakanlık görevlerinden ayrıldı."),
            ("25 Aralık 2013 İkinci Dalga ve Savcı Muammer Akkaş Bildirisi", "Başbakan'ın oğlu ve iş adamlarını hedef alan gözaltı talimatını emniyet uygulamayınca savcı adliye önünde bildiri dağıttı."),
            ("Emniyet Müdürlerinin Gece Yarısı Görevden Alınması", "Operasyonu amirlerinden gizleyen İstanbul Emniyet Müdürü ve şube müdürleri sabaha karşı görevden alındı."),
            ("TIR Krizleri: Adana ve Kırıkhan'da MİT TIR'larının Durdurulması", "Suriye Türkmenlerine insani yardım taşıyan MİT tırları savcı ve jandarma ekiplerince yolda silah zoruyla durduruldu."),
            ("MİT Görevlilerinin Yere Yatırılıp Kelepçelenmesi Skandalı", "Devlet sırrı taşıyan tırların aranması ve MİT personelinin darp edilmesi devlet krizine dönüştü."),
            ("İnternete Sızdırılan Kriptolu Ses Kayıtları ve 'Sıfırlama' Kaseti", "Başbakan ve bakanların kriptolu telefonlarının dinlenerek montajlandığı iddia edilen ses kayıtları Youtube'a yüklendi."),
            ("Kriptolu Telefonların TÜBİTAK ve TİB Tarafından Dinlenmesi", "Devlet ricalinin kullandığı güvenli telefonların TİB üzerinden yasadışı kaydedildiği belgelendi."),
            ("TİB'in (Telekomünikasyon İletişim Başkanlığı) Kapatılması", "Yasadışı dinleme üssüne dönüştüğü tespit edilen TİB binası mühürlenerek yetkileri BTK'ya devredildi."),
            ("Yargıda Birlik Platformu'nun (YBP) Kurulması (2014)", "Muhafazakar, sosyal demokrat ve milliyetçi yargı mensupları cemaat vesayetine karşı ortak liste kurdu."),
            ("2014 HSYK Seçimleri: Hükümet Destekli Listenin Zaferi", "Yargıda Birlik Platformu seçimleri kazanarak HSYK yönetimini devraldı; paralel yapı tasfiyesi başladı."),
            ("Sulh Ceza Hakimliklerinin Kurulması (Haziran 2014)", "Arama, el koyma ve tutuklama kararlarını vermek üzere ihtisaslaşmış Sulh Ceza Hakimlikleri ihdas edildi."),
            ("Bank Asya'ya BDDK ve TMSF Tarafından El Konulması", "Mali yapısı bozulan ve şeffaf ortaklık yapısını sunamayan Bank Asya'nın yönetimi TMSF'ye geçti."),
            ("Koza İpek Grubu Şirketlerine ve Medyasına Kayyum Atanması", "Terör örgütünü finanse ettiği gerekçesiyle holding bünyesindeki maden ve televizyon kanallarına kayyum girdi."),
            ("Zaman Gazetesi ve Feza Gazetecilik'e Kayyum Görevlendirilmesi", "Örgütün amiral gemisi konumundaki Zaman Gazetesi yönetimi mahkeme kararıyla kayyuma devredildi."),
            ("Samanyolu Yayın Grubu Kanallarının Türksat'tan Çıkarılması", "Yayın ilkelerini ihlal eden ve terör propagandası yapan televizyon kanallarının uydudan yayını kesildi."),
            ("Tahşiyeciler Davası ve Hidayet Karaca'nın Tutuklanması", "Dini bir gruba yönelik kumpas kurdukları iddiasıyla emniyet müdürleri ve medya yöneticileri tutuklandı."),
            ("Selam Tevhid Kudüs Ordusu Kumpası ve VIP Dinlemeler", "Binlerce siyasetçi, gazeteci ve akademisyenin uydurma terör örgütü bahanesiyle dinlendiği ortaya çıktı."),
            ("Milli Güvenlik Siyaset Belgesine PDY/FETÖ Tehdidinin Girmesi", "Kırmızı Kitap olarak bilinen belgeye Paralel Devlet Yapılanması milli güvenliği tehdit eden unsur olarak yazıldı."),
            ("Savcı Mehmet Selim Kiraz'ın Çağlayan Adliyesinde Şehit Edilmesi", "DHKP-C'li teröristler Berkin Elvan dosyasını yürüten savcıyı makamında rehin alıp şehit etti.")
        ]
    },
    {
        "id": 7,
        "name": "Terörle Mücadele, Oslo, Habur, Hendek Operasyonları (2005-2017)",
        "source": "İçişleri Bakanlığı & MSB",
        "char1": "char_icisleri_bakani",
        "char2": "char_genelkurmay_baskani",
        "kw": "Güvenlik ve Çözüm Arayışı",
        "cases": [
            ("Dağlıca Karakolu Baskını ve 12 Şehit (Ekim 2007)", "Hakkari Dağlıca taburuna ağır silahlarla saldıran teröristler 12 askerimizi şehit etti, 8 askeri kaçırdı."),
            ("Aktütün Karakolu Saldırısı (Ekim 2008)", "Sınırın sıfır noktasındaki Aktütün karakoluna düzenlenen hain saldırı sınır güvenliğini yeniden tartışmaya açtı."),
            ("Güneş Sınır Ötesi Kara Harekâtı (Şubat 2008)", "TSK kış ortasında Kuzey Irak Hakurk ve Zap kamplarına kara harekâtı düzenleyerek örgüt üslerini yerle bir etti."),
            ("Demokratik Açılım ve Milli Birlik ve Kardeşlik Projesi", "Kürt meselesini silah yerine siyasetle çözmek amacıyla İçişleri Bakanlığı koordinasyonunda açılım başlatıldı."),
            ("Oslo Görüşmeleri ve MİT Heyeti Ses Kayıtlarının Sızması", "MİT Müsteşarı ve örgüt temsilcileri arasında Norveç'te yapılan gizli görüşmelerin ses kasetleri internete sızdırıldı."),
            ("Habur Sınır Kapısından Girişler ve Seyyar Mahkeme", "Kandil ve Mahmur'dan gelen 34 kişilik grubun otobüs üstündeki şovu ve sınırda kurulan mahkeme tepki çekti."),
            ("Silvan Saldırısı ve 13 Askerin Şehit Olması (Temmuz 2011)", "Diyarbakır Silvan'da pusuya düşürülen 13 askerin şehadeti açılım sürecine en ağır darbeyi vurdu."),
            ("Demokratik Özerklik İlanları ve KCK Operasyonları", "Güneydoğu'da özerklik ilan eden belediye başkanları ve KCK şehir yapılanması yöneticileri tutuklandı."),
            ("Akil İnsanlar Heyeti'nin 7 Bölgede Sahaya İnmesi (2013)", "Sanatçı, yazar ve akademisyenlerden oluşan 63 kişilik heyet halkla buluşarak barış sürecini anlattı."),
            ("Nevruz 2013 Diyarbakır Mektubu ve Silahlı Unsurların Çekilmesi", "Diyarbakır meydanında okunan mektupta örgütün Türkiye topraklarından sınır dışına çekileceği duyuruldu."),
            ("Çözüm Süreci Çerçeve Kanunu'nun (6551) TBMM'de Kabulü", "Müzakere yürüten kamu görevlilerine cezai muafiyet sağlayan tarihi çerçeve yasa meclisten geçti."),
            ("6-8 Ekim 2014 Kobani Olayları ve Şiddet Dalgası", "HDP'nin sokak çağrısı sonrası 35 ilde çıkan olaylarda 53 kişi hayatını kaybetti; şehirler yakıldı."),
            ("Yasin Börü ve Arkadaşlarının Katledilmesi", "Diyarbakır'da kurban eti dağıtırken vahşice katledilen gençlerin davası tüm Türkiye'nin vicdanını kanattı."),
            ("Dolmabahçe Mutabakatı (28 Şubat 2015)", "Hükümet temsilcileri ve HDP heyeti Dolmabahçe Başbakanlık Ofisi'nde 10 maddelik ortak deklarasyonu okudu."),
            ("Cumhurbaşkanı Erdoğan'ın Dolmabahçe Mutabakatını Kabul Etmemesi", "Cumhurbaşkanı ortak açıklamayı doğru bulmadığını belirterek sürecin suistimal edildiğini vurguladı."),
            ("7 Haziran 2015 Seçimleri ve Tek Başına İktidarın Kaybı", "HDP'nin barajı aşmasıyla AK Parti 13 yıl sonra meclis çoğunluğunu kaybetti; koalisyon kurulamadı."),
            ("Ceylanpınar'da İki Polis Memurunun Evinde Şehit Edilmesi", "Şanlıurfa Ceylanpınar'da teröristlerce uykularında şehit edilen polisler çözüm sürecinin kesin sonu oldu."),
            ("Suruç Kültür Merkezi Canlı Bomba Katliamı (Temmuz 2015)", "Kobani'ye yardım götürmek için toplanan gençlerin arasında DEAŞ canlı bombası kendini patlattı; 34 kişi öldü."),
            ("Ankara Tren Garı Terör Saldırısı (10 Ekim 2015)", "Barış mitingi öncesi garda patlatılan iki canlı bomba 104 vatandaşın hayatını kaybetmesine yol açtı."),
            ("Hendek ve Barikat Olayları: Şehir Savaşları", "Sur, Cizre, Silopi, Nusaybin ve Yüksekova'da PKK sokaklara hendekler kazıp EYP'ler yerleştirerek özerklik ilan etti."),
            ("Aylarca Süren Sokağa Çıkma Yasakları ve Tahliyeler", "Sivillerin zarar görmemesi için ilçe merkezlerinde 24 saatlik sokağa çıkma yasakları uygulandı."),
            ("TSK ve Polis Özel Harekâtın Ortak Meskun Mahal Harekâtı", "Mehmetçik ve PÖH timleri omuz omuza vererek sokak sokak, ev ev hendekleri temizledi; yüzlerce şehit verildi."),
            ("Sur Tarihi Dokusunun Yıkımı ve Yeniden İhya Projesi", "Çatışmalarda tahrip olan tarihi Diyarbakır Sur ilçesi acele kamulaştırmayla TOKİ tarafından aslına uygun inşa edildi."),
            ("Ankara Merasim Sokak Askeri Servis Konvoyu Saldırısı (Şubat 2016)", "Genelkurmay yakınında askeri personel servislerine düzenlenen bombalı araç saldırısında 29 can şehit düştü."),
            ("Ankara Kızılay Güvenpark Otobüs Durakları Saldırısı (Mart 2016)", "Otobüs bekleyen sivillerin arasına dalan bombalı araç 36 masum vatandaşın hayatını kopardı."),
            ("İstanbul Atatürk Havalimanı Dış Hatlar Saldırısı (Haziran 2016)", "Terminal binasını basıp sivilleri tarayan ve kendilerini patlatan üç canlı bomba 45 kişiyi katletti."),
            ("Beşiktaş Vodafone Park Çevik Kuvvet Şehitleri Saldırısı (Aralık 2016)", "Maç çıkışı görevli polislere düzenlenen çifte bombalı saldırıda 39'u polis 46 vatan evladı şehit oldu."),
            ("Kayseri Komando Tugayı Çarşı İzni Servisi Saldırısı", "Hafta sonu iznine çıkan silahsız erleri taşıyan halk otobüsüne bombalı araç çarptı; 15 Mehmetçik şehit düştü."),
            ("İzmir Adliyesi Saldırısı ve Şehit Polis Fethi Sekin", "Adliyeye sızmak isteyen teröristlerle tek başına çatışıp mermisi bitene kadar direnen kahraman polis katliamı önledi."),
            ("Reina Gece Kulübü Katliamı ve Teröristin Canlı Yakalanması", "Yılbaşı gecesi 39 kişiyi katleden DEAŞ'lı terörist Abdulgadir Masharipov Esenyurt'ta canlı ele geçirildi.")
        ]
    },
    {
        "id": 8,
        "name": "15 Temmuz Darbe Girişimi, OHAL ve Yeni Hükümet Sistemi",
        "source": "Cumhurbaşkanlığı & TBMM",
        "char1": "char_cumhurbaskani",
        "char2": "char_tbmm_baskani",
        "kw": "Darbe ve Anayasal Sistem",
        "cases": [
            ("Boğaziçi Köprüsü'nün Askeri Birliklerce Kapatılması (22:00)", "Zırhlı askeri araçların Boğaziçi ve FSM köprülerini tek taraflı trafiğe kapatması darbe girişimini başlattı."),
            ("TRT Stüdyolarının İşgali ve Korsan Bildirinin Okutulması", "Kendilerine 'Yurtta Sulh Konseyi' diyen cuntacılar spikere silah zoruyla korsan darbe bildirisini okuttu."),
            ("Cumhurbaşkanı Erdoğan'ın CNN Türk FaceTime Canlı Bağlantısı", "Hande Fırat'ın telefonundan bağlanan Cumhurbaşkanı milleti meydanlara ve havalimanlarına direnişe çağırdı."),
            ("Gölbaşı Özel Harekât Dairesine F-16 Bombardımanı", "Darbeci pilotların attığı lazer güdümlü bombayla 51 özel harekat polisi şehit düşerek tarihi bir destan yazdı."),
            ("TBMM Genel Kurulu'nun Bombalanması Sırasında Milletvekilleri", "Meclis Başkanı ve milletvekilleri sığınakta toplantıyı sürdürürken gazi meclis binası uçaklarca vuruldu."),
            ("Şehit Astsubay Ömer Halisdemir'in Tarihi Kurşunu", "Özel Kuvvetler Karargahını ele geçirmeye gelen darbeci general Semih Terzi'yi alnından vurarak darbenin seyrini değiştirdi."),
            ("Akıncı 4. Ana Jet Üssü ve Kazan Köylülerinin Direnişi", "Kazan halkı uçakların kalkışını engellemek için tarlalardaki saman balyalarını yakıp üssün elektriklerini kesti."),
            ("Kışlaların Önüne Çekilen Belediye Kamyonları ve İş Makineleri", "Tankların sokağa çıkmasını engellemek için askeri birlik nizamiyeleri hafriyat kamyonlarıyla barikatlandı."),
            ("16 Temmuz Sabahı Boğaziçi Köprüsünde Darbecilerin Teslim Oluşu", "Güneşin doğuşuyla birlikte halkın ve polisin üzerine yürüyen darbeci askerler silah bırakıp teslim oldu."),
            ("15 Temmuz Şehitler Köprüsü İsim Değişikliği", "Milli direnişin simgesi haline gelen Boğaziçi Köprüsü Bakanlar Kurulu kararıyla '15 Temmuz Şehitler Köprüsü' yapıldı."),
            ("Yenikapı Tarihi Mitingi ve Milli Mutabakat", "5 milyon vatandaşın katıldığı mitingde Cumhurbaşkanı, Başbakan ve muhalefet liderleri aynı sahnede birlik mesajı verdi."),
            ("Üç Ay Süreyle Olağanüstü Hal (OHAL) İlanı (20 Temmuz 2016)", "Darbe kalıntılarını temizlemek ve devleti arındırmak amacıyla anayasal OHAL ilan edilerek KHK dönemi başladı."),
            ("Askeri Liselerin ve Harp Akademilerinin Kapatılması", "Darbelerin insan kaynağı haline gelen askeri okullar kapatılarak Milli Savunma Üniversitesi (MSÜ) kuruldu."),
            ("Genelkurmay Başkanlığı'nın Milli Savunma Bakanlığı'na Bağlanması", "TSK üzerinde sivil denetimi sağlamak amacıyla kuvvet komutanlıkları doğrudan MSB'ye bağlandı."),
            ("GATA ve Askeri Hastanelerin Sağlık Bakanlığı'na Devri", "Gülhane Askeri Tıp Akademisi ve tüm askeri dispanserler sivil kamu sağlık sistemine entegre edildi."),
            ("Kanun Hükmünde Kararnameler (KHK) ile Kamudan İhraçlar", "TSK, Emniyet, Yargı ve bürokrasiden örgüt iltisaklı 120 binden fazla kamu görevlisi ihraç edildi."),
            ("OHAL İşlemleri İnceleme Komisyonu'nun Kurulması", "KHK ihraçlarına karşı yargı yolunu açmak ve haksızlıkları gidermek amacıyla 7 üyeli bağımsız komisyon kuruldu."),
            ("16 Nisan 2017 Anayasa Referandumu Kampanyası", "Parlamenter sistemden Cumhurbaşkanlığı Hükümet Sistemine geçişi öngören 18 maddelik paket oylamaya sunuldu."),
            ("YSK'nın Mühürsüz Oyların Geçerli Sayılması Kararı", "Referandum akşamı dışarıdan getirildiği kanıtlanmadıkça mühürsüz pusulaların geçerli sayılacağı açıklandı."),
            ("%51.4 Oyla Cumhurbaşkanlığı Hükümet Sisteminin Kabulü", "Türkiye cumhuriyet tarihinin en köklü yönetim sistemi değişikliğini sandıkta onaylayarak yeni döneme girdi."),
            ("Başbakanlık Makamının 2018 İtibarıyla Tarihe Karışması", "Yeni sistemin yürürlüğe girmesiyle cumhuriyetle yaşıt 98 yıllık Başbakanlık makamı resmen lağvedildi."),
            ("24 Haziran 2018 Seçimleri: Yeni Sistemin İlk Cumhurbaşkanı", "Erdoğan %52.6 oyla yeni anayasal sistemin yürütme yetkilerine sahip ilk Cumhurbaşkanı seçildi."),
            ("Yeni Bakanlık Yapılanmaları ve Cumhurbaşkanlığı Kararnameleri", "Başkanlık ofisleri ve kurulları kurularak yürütme organı kararnamelerle yeniden dizayn edildi."),
            ("31 Mart 2019 Yerel Seçimleri ve İstanbul İtirazları", "İstanbul'da 13 bin oy farkla biten seçim sonrası geçersiz oylar günlerce sayıldı; olağanüstü itiraz yapıldı."),
            ("YSK'nın 6 Mayıs 2019 İstanbul Seçimlerini İptal Kararı", "Sandık kurulu başkanlarının kamu görevlisi olmaması gerekçesiyle İstanbul Büyükşehir seçimi iptal edildi."),
            ("23 Haziran 2019 Yenilenen İstanbul Büyükşehir Seçimi", "Tekrarlanan seçimde Ekrem İmamoğlu 806 bin oy farkla (%54.2) İstanbul Büyükşehir Belediye Başkanı seçildi."),
            ("Terör İltisakı Gerekçesiyle Belediyelere Kayyum Atamaları", "Diyarbakır, Van, Mardin başta olmak üzere onlarca HDP'li belediye başkanının yerine valiler görevlendirildi."),
            ("Altılı Masa ve Millet İttifakı Protokolleri", "Güçlendirilmiş Parlamenter Sistem vaadiyle 6 muhalefet partisi genel başkanı ortak mutabakat imzaladı."),
            ("14 ve 28 Mayıs 2023 Cumhurbaşkanlığı Seçimleri", "İki turlu seçim maratonu sonunda Cumhurbaşkanı Erdoğan %52.18 oy alarak güven tazeledi."),
            ("31 Mart 2024 Yerel Seçimleri ve Değişen Siyasi Harita", "CHP 47 yıl sonra ilk kez Türkiye genelinde birinci parti çıkarak büyükşehirlerin çoğunu kazandı.")
        ]
    },
    {
        "id": 9,
        "name": "Dış Politika Krizleri: Kardak, Mavi Marmara, S-400, Mavi Vatan",
        "source": "Dışişleri Bakanlığı & Milli Savunma",
        "char1": "char_diplomat",
        "char2": "char_savunma_bakani",
        "kw": "Diplomasi ve Savunma",
        "cases": [
            ("Kardak Kayalıkları Krizi (Ocak 1996)", "Figen Akad gemisinin karaya oturmasıyla başlayan gerilimde SAT komandoları gece yarısı İkizce kayalığına bayrak dikti."),
            ("Davos 2009 'One Minute' Çıkışı", "Cumhurbaşkanı Erdoğan Dünya Ekonomik Forumu'nda Şimon Peres'e ve moderatör David Ignatius'a sert tepki gösterdi."),
            ("Mavi Marmara Baskını ve 10 Şehit (Mayıs 2010)", "Gazze'ye insani yardım götüren sivil gemiye uluslararası sularda İsrail komandolarınca helikopterden ateş açıldı."),
            ("İsrail ile İlişkilerin Maslahatgüzar Seviyesine İndirilmesi", "Özür ve tazminat şartları kabul edilene kadar büyükelçi geri çağrıldı ve askeri işbirlikleri askıya alındı."),
            ("İsrail Başbakanı Netanyahu'nun Resmi Özrü (2013)", "ABD Başkanı Obama'nın arabuluculuğunda Netanyahu Erdoğan'ı telefonla arayarak operasyonel hatalardan ötürü özür diledi."),
            ("Suriye Hava Sahasında RF-4E Türk Keşif Jetinin Düşürülmesi (2012)", "Akdeniz üzerinde silahsız keşif uçuşu yapan F-4 jeti Suriye hava savunması tarafından vuruldu; iki pilot şehit oldu."),
            ("Angajman Kurallarının Değiştirilmesi", "Türkiye Suriye sınırına yaklaşan her askeri unsuru tehdit kabul edeceğini ilan ederek yeni angajman kurallarını işletti."),
            ("Şah Fırat Operasyonu ve Süleyman Şah Türbesinin Nakli (2015)", "Karakolu kuşatan DEAŞ tehdidine karşı Süleyman Şah'ın naaşı ve Mehmetçik Suriye Eşmesi'ne güvenle taşındı."),
            ("Rus Su-24 Savaş Uçağının Türk F-16'ları Tarafından Düşürülmesi (Kasım 2015)", "Hatay Yayladağı sınırını 17 saniye ihlal eden ve uyarılara yanıt vermeyen Rus savaş uçağı F-16 devriyesince vuruldu."),
            ("Rusya'nın Türkiye'ye Yönelik Ekonomik Ambargoları", "Uçak krizi sonrası Moskova Türk inşaat firmalarını durdurdu, charter uçuşları ve domates ithalatını yasakladı."),
            ("Cumhurbaşkanı Erdoğan'ın Putin'e Gönderdiği Normalleşme Mektubu", "Haziran 2016'da gönderilen mektup ve başsağlığı dileğiyle iki ülke arasındaki derin diplomatik kriz aşıldı."),
            ("Ankara'da Rus Büyükelçi Andrey Karlov Suikastı (Aralık 2016)", "Resim sergisinde polis memuru Mevlüt Mert Altıntaş tarafından vurulan Rus elçi Moskova-Ankara hattını sarsamadı."),
            ("Astana ve Soçi Süreçleri: Rusya ve İran ile Suriye Masası", "Cenevre'nin tıkandığı sahada Türkiye, Rusya ve İran garantörlüğünde gerilimi azaltma bölgeleri kuruldu."),
            ("Fırat Kalkanı Harekâtı (Ağustos 2016 - Mart 2017)", "Cerablus ve El-Bab TSK ve SMO birliklerince DEAŞ terör örgütünden temizlenerek güvenli bölge yapıldı."),
            ("Zeytin Dalı Harekâtı ve Afrin'in Kurtarılması (2018)", "PKK/YPG terör koridorunu parçalamak amacıyla Afrin dağları ve şehir merkezi 58 günde kontrol altına alındı."),
            ("Barış Pınarı Harekâtı (Ekim 2019)", "Fırat'ın doğusunda Resulayn ve Tel Abyad arasındaki 120 kilometrelik hat teröristlerden arındırıldı."),
            ("Bahar Kalkanı Harekâtı ve İdlib SİHA Destanı (Mart 2020)", "İdlib'de 34 şehit verilmesi sonrası Türk SİHA'ları rejim ordusuna ait yüzlerce tank ve zırhlı aracı imha etti."),
            ("S-400 Triumf Hava Savunma Sisteminin Alınması ve Sevkiyatı", "NATO'nun Patriot vermemesi üzerine Rusya'dan alınan S-400 bataryaları Mürted Üssü'ne indi."),
            ("ABD'nin Türkiye'ye CAATSA Yaptırımları Uygulaması", "S-400 gerekçesiyle ABD Savunma Sanayii Başkanlığı'na ve başkan İsmail Demir'e yaptırım kararı aldı."),
            ("Türkiye'nin F-35 Müşterek Taarruz Uçağı Programından Çıkarılması", "Program ortağı ve üreticisi olduğumuz halde parasını ödediğimiz 6 adet F-35 jetimiz teslim edilmedi."),
            ("ABD'den 40 Adet F-16 Blok 70 Alımı ve Modernizasyon Onayı", "F-35 yerine TSK'nın ara çözüm olarak talep ettiği Blok 70 F-16 ve kit alımı ABD Kongresi'nce onaylandı."),
            ("Rahip Andrew Brunson Krizi ve Trump'ın Yaptırım Tweetleri (2018)", "İzmir'de tutuklu yargılanan ABD'li rahip için Trump'ın 'Ekonominizi mahvederim' tehdidiyle kur krizi patladı."),
            ("Cemal Kaşıkçı'nın Suudi Arabistan Konsolosluğunda Katledilmesi", "Washington Post yazarı gazetecinin İstanbul Başkonsolosluğu'nda infaz edilmesi ve ses kayıtları dünyayı sarstı."),
            ("Suudi Arabistan ve BAE ile Yaşanan Soğukluk ve Normalleşme", "Yıllar süren boykot ve gerilimin ardından liderler düzeyinde ziyaretlerle ekonomik ve diplomatik bahar başladı."),
            ("Mısır ile 10 Yıllık Gerilimin Ardından Sisi ile Tarihi Zirve", "Doha'daki el sıkışmanın ardından Ankara ve Kahire büyükelçileri atandı; Akdeniz ortaklığı tazelendi."),
            ("Libya ile İmzalanan Deniz Yetki Alanları Sınırlandırma Mutabakatı", "Trablus hükümetiyle imzalanan tarihi anlaşma ile Yunanistan'ın Akdeniz'i kapatma planı çöpe atıldı."),
            ("Mavi Vatan Doktrini ve Oruç Reis'in Sismik Arama Görevleri", "Doğu Akdeniz'de Türk donanmasının fırkateynleri eşliğinde sismik ve sondaj gemileri bayrak dalgalandırdı."),
            ("İkinci Karabağ Savaşı ve Şuşa Beyannamesi (2020)", "Azerbaycan'a verilen İHA/SİHA ve askeri strateji desteğiyle 30 yıllık Ermeni işgali 44 günde sonlandırıldı."),
            ("Karadeniz Tahıl Koridoru Anlaşması (İstanbul Girişimi)", "Ukrayna ve Rusya savaşırken açlık krizini önlemek için Dolmabahçe'de 33 milyon ton tahılın sevki sağlandı."),
            ("İsveç ve Finlandiya'nın NATO Üyeliği ve Madrid Muhtırası", "Terörle mücadele taahhütleri ve silah ambargolarının kalkması şartıyla iki İskandinav ülkesinin üyeliği onaylandı.")
        ]
    },
    {
        "id": 10,
        "name": "Doğal Afetler: Marmara, Düzce, Van, Elazığ, İzmir Depremleri, Sel ve Yangınlar",
        "source": "Kriz Masası & AFAD",
        "char1": "char_afad_baskani",
        "char2": "char_cevre_sehircilik_bakani",
        "kw": "Afet Yönetimi ve İmar",
        "cases": [
            ("17 Ağustos 1999 Gölcük Depremi (7.4) ve Asrın Felaketi", "Gece 03.02'de meydana gelen 45 saniyelik deprem Kocaeli, Sakarya, Yalova ve İstanbul'da 18 bin can aldı."),
            ("Gölcük Donanma Komutanlığı'nın Ağır Hasar Alması", "Deprem üssündeki tersane binaları çöktü; donanma komutanları ve Mehmetçikler enkaz altında kaldı."),
            ("Veli Göçer Çınarcık Konutları ve Çürük Müteahhit Davaları", "Yalova'da deniz kumuyla yapılan siteleri iskambil kağıdı gibi çöken müteahhit yargılanarak mahkum edildi."),
            ("Özel İletişim Vergisi'nin (Deprem Vergisi) İhdas Edilmesi", "Deprem yaralarını sarmak ve telekomünikasyonu güçlendirmek amacıyla geçici olarak çıkarılan vergi kalıcı oldu."),
            ("Doğal Afet Sigortaları Kurumu'nun (DASK) Kurulması", "Ev sahiplerini zorunlu deprem sigortasına bağlayan sistem kurularak afet fonu oluşturuldu."),
            ("12 Kasım 1999 Düzce Depremi (7.2)", "Marmara depreminin yaraları sarılmadan Düzce ve Kaynaşlı'yı vuran ikinci sarsıntı Bolu tüneli inşaatını çökertti."),
            ("2003 Bingöl Depremi ve Çeltiksuyu YİBO Faciası", "Bingöl'de çöken Yatılı İlköğretim Bölge Okulu pansiyonunda 84 öğrenci ve öğretmen hayatını kaybetti."),
            ("2011 Van Depremi (7.2) ve Erciş Enkazları", "Erciş ve Van merkezde yüzlerce bina yıkıldı; kış soğuğunda çadır kentler ve konteyner kentler kuruldu."),
            ("Atsushi Miyazaki: Japon Yardım Gönüllüsünün Vefatı", "İkinci Van depreminde Bayram Oteli'nin yıkılmasıyla Japon doktor hayatını kaybetti; adı parklarda yaşatıldı."),
            ("Van Depremi Sonrası TOKİ Kalıcı Konut Seferberliği", "Bir yıl gibi rekor sürede dağ yamaçlarına 17 bin deprem konutu inşa edilerek hak sahiplerine teslim edildi."),
            ("24 Ocak 2020 Elazığ Sivrice Depremi (6.8)", "Elazığ ve Malatya'da 41 kişinin vefat ettiği deprem sonrası kış ortasında hızlı çadır ve konteyner desteği sağlandı."),
            ("30 Ekim 2020 İzmir Seferihisar Depremi ve Bayraklı Enkazları", "Merkez üssü deniz olan depremde Bayraklı'da zemin sıvılaşması sebebiyle binalar çöktü; minik Ayda ve İdil kurtarıldı."),
            ("Rıza Bey Apartmanı Davası ve Yapı Denetim İhmalleri", "Altındaki dükkanlar için kolonları kesildiği iddia edilen apartmanın sorumluları hakkında ağır ceza davaları açıldı."),
            ("2021 Manavgat Yangını: Türkiye'nin En Büyük Orman Yangını", "Antalya Manavgat'ta başlayıp günlerce süren yangında yüz binlerce hektar orman kül oldu, köyler yandı."),
            ("Marmaris, Bodrum ve Milas Orman Yangınları Kuşatması", "Alevlerin Kemerköy Termik Santrali nizamiyesine kadar dayanmasıyla tahliye operasyonları başlatıldı."),
            ("Türk Hava Kurumu (THK) Canadair Uçakları Polemiği", "Hangarlarda bekletilen yangın söndürme uçaklarının motor bakımı ve su kapasitesi siyasi tartışmaya dönüştü."),
            ("Azerbaycan ve Rusya'dan Gelen Yangın Söndürme Uçakları", "Dost ülkelerin gönderdiği amfibik Beriev uçakları ve yüzlerce itfaiyeci alevlerle mücadeleye katıldı."),
            ("Orman Yangınları Sonrası Köy Evleri Yapım Hamlesi", "Yangında evlerini kaybeden köylülere yöresel mimariye uygun tek katlı müstakil afet konutları yapıldı."),
            ("2021 Batı Karadeniz Sel Felaketi: Bozkurt Ezine Çayı", "Kastamonu Bozkurt'ta derenin taşmasıyla ilçe merkezini su bastı; dere yatağındaki 8 katlı binalar çöktü."),
            ("Sinop Ayancık ve Bartın Sel Felaketleri", "Köprülerin yıkıldığı, tomrukların sahile vurduğu afette helikopterlerle çatılardan tahliyeler yapıldı."),
            ("Ezine Çayı Islahı ve Dere Yatağı Yapılaşma Yasakları", "Sel sonrası dere yataklarındaki binalar kamulaştırılarak yıkıldı; yeni taşkın kanalları inşa edildi."),
            ("2021 Marmara Denizi Müsilaj (Deniz Salyası) Krizi", "Deniz suyu sıcaklığı ve atık kirliliği sebebiyle Marmara'yı saran tabaka balıkçılığı ve turizmi felç etti."),
            ("Marmara Denizi Eylem Planı ve Oksijenlendirme Operasyonu", "Çevre Bakanlığı 22 maddelik eylem planı açıklayarak 81 gemiyle deniz yüzeyindeki salyayı topladı."),
            ("Marmara Denizi'nin Özel Çevre Koruma Bölgesi İlan Edilmesi", "Marmara havzasındaki tüm organize sanayi bölgelerine ileri biyolojik arıtma tesisi zorunluluğu getirildi."),
            ("Erzincan İliç Altın Madeni Liç Yığını Kayması (2024)", "Çöpler Altın Madeni'nde siyanürlü liç tepesinin çökmesiyle 9 maden işçisi tonlarca toprağın altında kaldı."),
            ("Fırat Nehri'ne Siyanür Karışması Tehlikesi ve Menfez Kapatma", "Kaymanın Fırat Nehri'ne ulaşmasını engellemek için Sabırlı Deresi menfezleri betonla kapatıldı."),
            ("İliç Maden Şirketi Yöneticilerinin Tutuklanması ve Ruhsat İptali", "Kanadalı ve yerli şirket yöneticileri tutuklandı; Çevre Bakanlığı madenin işletme ruhsatını tamamen iptal etti."),
            ("Kaz Dağları Kirazlı Altın Madeni Eylemleri (2019)", "Alamos Gold şirketinin yüz binlerce ağacı kestiği iddiasıyla binlerce çevreci aylarca çadır nöbeti tuttu."),
            ("Akbelen Ormanı Linyit Madeni Direnişi ve İkizköy Nöbeti", "Muğla'da termik santrale kömür sağlamak için kesilmek istenen çam ağaçları için köylüler jandarmayla karşı karşıya geldi."),
            ("Salda Gölü Koruma Alanı ve Beyaz Kumulların Kurtarılması", "Türkiye'nin Maldivleri olarak bilinen gölün beyaz kumullarına araç girişi ve ayakkabıyla basılması yasaklandı.")
        ]
    }
]

print("DOMAINS_1_TO_10 loaded successfully.")
